/* 新題材（美、日、韓）：量子運算、SaaS、資料平台、資安、IT 服務、電信媒體、AdTech、交易所、另類資產、支付、加密貨幣、醫療保險、美國房市、關鍵礦產、油氣、重工機械、日本 NAND、日本銅箔、韓國電子元件 */
INDUSTRY_PACK.push(
  { id: "us-quantum", mk: "us", cat: "量子運算", name: "量子運算", icon: "chip",
    desc: "用量子位元取代一般的 0 與 1 來計算，目標是解決傳統電腦算不完的化學、材料與最佳化問題；目前仍在研發與早期商用階段。",
    flow: ["量子位元晶片", "極低溫冷卻", "微波控制與讀出", "錯誤更正", "雲端提供算力"],
    segs: [{ n: "量子硬體新創", c: [["IONQ", "IonQ", "離子阱量子電腦"], ["RGTI", "Rigetti Computing", "超導量子電腦"], ["QBTS", "D-Wave Quantum", "量子退火"]] },
      { n: "大型科技公司", c: [["IBM", "IBM", "超導量子電腦與雲端平台"], ["GOOGL", "Alphabet", "Google 量子 AI 晶片"], ["HON", "Honeywell", "持有 Quantinuum"]] }],
    fig: { w: 360, h: 230, alt: "量子運算：量子位元晶片放在稀釋冷凍機裡，用微波控制、讀出後交給古典電腦處理", items: [
      { t: "group", x: 8, y: 14, w: 136, h: 150, label: "稀釋冷凍機", c: "blue" },
      { t: "cyl", x: 34, y: 34, w: 80, h: 92, c: "cyan" },
      { t: "chip", x: 52, y: 66, w: 44, h: 30, label: "量子位元", s: 8, c: "purple" },
      { t: "text", x: 74, y: 148, s: 8, label: "接近 -273°C", muted: true },
      { t: "box", x: 176, y: 30, w: 80, h: 40, label: "控制電子", sub: "發出微波脈衝", c: "orange" },
      { t: "arrow", pts: [[176, 50], [116, 50]], c: "orange" },
      { t: "box", x: 176, y: 96, w: 80, h: 40, label: "古典電腦", sub: "錯誤更正、排程", c: "gray" },
      { t: "arrow", pts: [[116, 116], [176, 116]], c: "blue" },
      { t: "arrow", pts: [[216, 96], [216, 72]], c: "gray" },
      { t: "arrow", pts: [[256, 116], [300, 116], [300, 72]], c: "purple" },
      { t: "box", x: 268, y: 30, w: 84, h: 40, label: "雲端存取", sub: "按使用量付費", c: "purple" },
      { t: "text", x: 268, y: 160, s: 9, label: "可能的用途", b: true },
      { t: "icon", x: 186, y: 168, s: 20, k: "flask", c: "green" }, { t: "text", x: 196, y: 198, s: 8, label: "新材料", muted: true },
      { t: "icon", x: 230, y: 168, s: 20, k: "pill", c: "green" }, { t: "text", x: 240, y: 198, s: 8, label: "新藥", muted: true },
      { t: "icon", x: 274, y: 168, s: 20, k: "chart", c: "green" }, { t: "text", x: 284, y: 198, s: 8, label: "最佳化", muted: true },
      { t: "icon", x: 318, y: 168, s: 20, k: "lock", c: "green" }, { t: "text", x: 328, y: 198, s: 8, label: "密碼學", muted: true },
      { t: "legend", x: 16, y: 214, items: [["orange", "控制訊號"], ["blue", "量測結果"]] },
    ] },
    how: [
      ["在做什麼", "一般電腦用 0 或 1 計算，量子電腦用「量子位元」，可以同時處在多種狀態的疊加，適合模擬分子、材料或找最佳解這類傳統電腦要算非常久的問題。"],
      ["怎麼運作", "量子位元很脆弱，超導路線要放進接近絕對零度的稀釋冷凍機；外面的控制電子用微波脈衝操作它，再把量測結果讀出來交給一般電腦處理。另有離子阱、光子、中性原子等不同路線。"],
      ["關鍵名詞", "量子位元（qubit）：計算的基本單位。退相干：量子狀態被雜訊破壞。錯誤更正：用很多實體位元組成一個穩定的「邏輯位元」，是能否實用的關鍵。"],
      ["景氣看什麼", "邏輯位元數量與錯誤率的進展、政府與大企業的研發預算、雲端量子服務的使用量；目前多數公司仍在虧損、靠募資推進，消息面波動很大。"],
      ["代表公司", "IBM、Google 走超導路線，IonQ 走離子阱，D-Wave 做量子退火，Honeywell 持有 Quantinuum；台灣則有中研院與學界在研發，產業鏈仍很早期。"],
    ] },

  { id: "us-saas", mk: "us", cat: "軟體", name: "企業軟體與 SaaS", icon: "code",
    desc: "把企業軟體做成線上服務按月或按年收訂閱費，客戶不用自己裝伺服器；收入可預期、毛利高，近年再加上 AI 助理功能加價收費。",
    flow: ["開發軟體平台", "放上雲端", "企業訂閱", "續約與加購", "AI 功能加值"],
    segs: [{ n: "企業應用", c: [["CRM", "Salesforce", "客戶關係管理"], ["NOW", "ServiceNow", "IT 與企業流程"], ["WDAY", "Workday", "人資與財務"], ["SAP", "SAP", "企業資源規劃 ERP"]] },
      { n: "其他軟體", c: [["ADBE", "Adobe", "創意與文件軟體"], ["INTU", "Intuit", "會計與報稅"], ["ORCL", "甲骨文", "資料庫與 ERP"]] }],
    fig: { w: 360, h: 230, alt: "SaaS：企業按月付訂閱費，軟體平台跑在雲端，提供各種功能模組與 AI 助理", items: [
      { t: "icon", x: 20, y: 38, s: 28, k: "person", c: "gray" }, { t: "text", x: 34, y: 76, s: 8, label: "企業客戶", muted: true },
      { t: "arrow", pts: [[54, 46], [120, 46]], c: "green", label: "每月訂閱費", lx: 87, ly: 40 },
      { t: "arrow", pts: [[120, 66], [54, 66]], c: "blue", label: "線上軟體服務", lx: 87, ly: 80 },
      { t: "box", x: 122, y: 28, w: 110, h: 50, label: "SaaS 平台", sub: "多家客戶共用", c: "blue", fill: true },
      { t: "arrow", pts: [[232, 46], [284, 46]], c: "gray", dash: true, label: "跑在上面", lx: 258, ly: 40 },
      { t: "icon", x: 288, y: 30, s: 32, k: "cloud", c: "cyan" }, { t: "text", x: 304, y: 72, s: 8, label: "雲端機房", muted: true },
      { t: "group", x: 104, y: 92, w: 158, h: 50, label: "功能模組", c: "blue" },
      { t: "box", x: 112, y: 108, w: 44, h: 26, label: "CRM", s: 9, c: "blue" },
      { t: "box", x: 161, y: 108, w: 44, h: 26, label: "人資", s: 9, c: "blue" },
      { t: "box", x: 210, y: 108, w: 44, h: 26, label: "財務", s: 9, c: "blue" },
      { t: "arrow", pts: [[177, 78], [177, 92]], c: "blue" },
      { t: "box", x: 280, y: 100, w: 70, h: 40, label: "AI 助理", sub: "加價收費", c: "purple", fill: true },
      { t: "line", pts: [[262, 120], [280, 120]], c: "purple", dash: true },
      { t: "text", x: 180, y: 170, s: 9.5, label: "客戶數 × 單價 × 續約率 ＝ 經常性收入", b: true },
      { t: "text", x: 180, y: 188, s: 8, label: "軟體寫一次可以賣很多次，所以毛利高", muted: true },
      { t: "legend", x: 16, y: 216, items: [["green", "客戶付的錢"], ["blue", "提供的服務"]] },
    ] },
    how: [
      ["在做什麼", "以前企業買軟體要一次付一大筆授權費、自己裝在機房；SaaS（軟體即服務）改成放在雲端，企業用瀏覽器登入就能用，按人數或用量每月、每年付訂閱費。"],
      ["怎麼運作", "軟體公司開發一套平台，很多客戶共用同一套系統（多租戶），平台通常跑在 AWS、Azure 等雲端上；客戶先買基本功能，用順了再加購人數與模組，近年再推 AI 助理加價。"],
      ["關鍵名詞", "ARR：年度經常性收入。淨留存率：老客戶今年比去年多付多少，超過 100% 代表老客戶越用越多。流失率：取消訂閱的比例。"],
      ["景氣看什麼", "企業 IT 預算、新客戶簽約與續約狀況、淨留存率；也要看 AI 是否讓客戶需要的帳號數變少，或反過來帶來新的加購收入。"],
      ["代表公司", "Salesforce（CRM）、ServiceNow（IT 流程）、Workday（人資）、SAP 與甲骨文（ERP）、Adobe（創意軟體）、Intuit（會計報稅）；台灣上市公司多是代理或系統整合，較少大型 SaaS。"],
    ] },

  { id: "us-dataplat", mk: "us", cat: "軟體", name: "資料平台與可觀測性", icon: "server",
    desc: "資料平台幫企業把散在各處的資料集中、整理、查詢並拿去訓練 AI；可觀測性軟體則即時監控系統的日誌與指標，出事時第一時間告警。",
    flow: ["蒐集資料", "存進資料湖倉", "查詢分析", "AI 應用", "監控與告警"],
    segs: [{ n: "資料平台", c: [["SNOW", "Snowflake", "雲端資料倉儲"], ["MDB", "MongoDB", "文件型資料庫"], ["PLTR", "Palantir", "資料整合與分析平台"]] },
      { n: "可觀測性", c: [["DDOG", "Datadog", "雲端監控"], ["DT", "Dynatrace", "應用程式監控"], ["ESTC", "Elastic", "搜尋與日誌分析"]] }],
    fig: { w: 360, h: 230, alt: "資料平台把各種資料存進資料湖倉再分析或訓練 AI；可觀測性收集日誌、指標、追蹤做監控告警", items: [
      { t: "group", x: 8, y: 8, w: 344, h: 100, label: "資料平台", c: "blue" },
      { t: "box", x: 16, y: 32, w: 70, h: 44, label: "各種資料", sub: "交易、App", c: "gray" },
      { t: "arrow", pts: [[86, 54], [110, 54]], c: "blue" },
      { t: "cyl", x: 112, y: 28, w: 70, h: 52, label: "資料湖倉", c: "blue" },
      { t: "arrow", pts: [[182, 54], [206, 54]], c: "blue" },
      { t: "box", x: 208, y: 32, w: 66, h: 44, label: "分析查詢", sub: "SQL、報表", c: "cyan" },
      { t: "arrow", pts: [[274, 54], [294, 54]], c: "blue" },
      { t: "box", x: 296, y: 32, w: 50, h: 44, label: "AI", sub: "訓練模型", c: "purple" },
      { t: "group", x: 8, y: 116, w: 344, h: 88, label: "可觀測性", c: "orange" },
      { t: "rack", x: 18, y: 134, w: 40, h: 62, n: 4, c: "gray" },
      { t: "box", x: 80, y: 132, w: 58, h: 18, label: "日誌", s: 9, c: "orange" },
      { t: "box", x: 80, y: 155, w: 58, h: 18, label: "指標", s: 9, c: "orange" },
      { t: "box", x: 80, y: 178, w: 58, h: 18, label: "追蹤", s: 9, c: "orange" },
      { t: "arrow", pts: [[58, 141], [78, 141]], c: "orange" },
      { t: "arrow", pts: [[58, 164], [78, 164]], c: "orange" },
      { t: "arrow", pts: [[58, 187], [78, 187]], c: "orange" },
      { t: "arrow", pts: [[138, 164], [170, 164]], c: "orange" },
      { t: "box", x: 172, y: 141, w: 80, h: 46, label: "監控平台", sub: "找出異常", c: "orange", fill: true },
      { t: "arrow", pts: [[252, 164], [282, 164]], c: "red" },
      { t: "box", x: 284, y: 145, w: 62, h: 38, label: "告警", sub: "工程師處理", c: "red" },
      { t: "legend", x: 16, y: 222, items: [["blue", "業務資料"], ["orange", "系統運作訊號"], ["red", "告警"]] },
    ] },
    how: [
      ["在做什麼", "企業的資料散在交易系統、App、網站、感測器裡。資料平台把它們集中整理，讓人能查詢、做報表、訓練 AI；可觀測性軟體則盯著每台伺服器與程式，確保服務不當機。"],
      ["怎麼運作", "資料先被匯入雲端的資料倉儲或資料湖（兩者合稱湖倉），整理成表格後用 SQL 查詢或拿去訓練模型。監控端則在伺服器裝探針，持續送出日誌、指標與追蹤紀錄，平台比對後發出告警。"],
      ["關鍵名詞", "資料倉儲：整理好的結構化資料庫。資料湖：先存原始資料再說。日誌（log）、指標（metric）、追蹤（trace）：可觀測性的三種訊號。多數平台按用量計費。"],
      ["景氣看什麼", "企業雲端用量是否成長、AI 專案帶來的資料量、按用量計費的消耗速度；景氣差時客戶會先優化用量，營收成長會放慢。"],
      ["代表公司", "Snowflake、MongoDB、Palantir 屬資料平台，Datadog、Dynatrace、Elastic 屬監控與日誌；另有未上市的 Databricks。它們大多跑在 AWS、Azure、Google Cloud 上。"],
    ] },

  { id: "us-security", mk: "us", cat: "資安", name: "資安防護", icon: "code",
    desc: "保護企業的網路、帳號、電腦與雲端資料不被駭客入侵或勒索；從防火牆、身分驗證到端點防護層層把關，再由資安監控中心集中分析告警。",
    flow: ["網路防火牆", "身分驗證", "端點防護", "雲端安全", "監控與應變"],
    segs: [{ n: "平台與網路", c: [["PANW", "Palo Alto Networks", "防火牆與資安平台"], ["FTNT", "Fortinet", "防火牆設備"], ["CHKP", "Check Point", "防火牆"], ["NET", "Cloudflare", "網路安全與 CDN"]] },
      { n: "端點與身分", c: [["CRWD", "CrowdStrike", "端點防護"], ["ZS", "Zscaler", "雲端安全存取"], ["OKTA", "Okta", "身分驗證"]] }],
    fig: { w: 360, h: 230, alt: "資安防護：駭客攻擊要穿過網路、身分、端點、雲端多層防護，各層告警集中到資安監控中心處理", items: [
      { t: "icon", x: 12, y: 40, s: 28, k: "person", c: "red" }, { t: "text", x: 26, y: 78, s: 8, label: "駭客", muted: true },
      { t: "arrow", pts: [[44, 54], [76, 54]], c: "red", label: "攻擊", lx: 60, ly: 48 },
      { t: "group", x: 72, y: 8, w: 280, h: 86, label: "層層防護", c: "green" },
      { t: "box", x: 80, y: 26, w: 60, h: 58, label: "網路", sub: "防火牆", c: "orange" },
      { t: "box", x: 147, y: 26, w: 60, h: 58, label: "身分", sub: "登入驗證", c: "orange" },
      { t: "box", x: 214, y: 26, w: 60, h: 58, label: "端點", sub: "電腦手機", c: "orange" },
      { t: "box", x: 281, y: 26, w: 64, h: 58, label: "雲端", sub: "資料與帳號", c: "blue", fill: true },
      { t: "arrow", pts: [[110, 84], [110, 112]], c: "cyan", dash: true },
      { t: "arrow", pts: [[177, 84], [177, 112]], c: "cyan", dash: true },
      { t: "arrow", pts: [[244, 84], [244, 112]], c: "cyan", dash: true },
      { t: "arrow", pts: [[313, 84], [313, 112]], c: "cyan", dash: true },
      { t: "box", x: 80, y: 114, w: 265, h: 38, label: "資安監控中心", sub: "AI 判讀告警", c: "cyan", fill: true },
      { t: "arrow", pts: [[212, 152], [212, 170]], c: "green" },
      { t: "box", x: 152, y: 172, w: 120, h: 30, label: "隔離、修補", c: "green" },
      { t: "icon", x: 22, y: 132, s: 30, k: "shield", c: "green" }, { t: "text", x: 37, y: 172, s: 8, label: "零信任", muted: true },
      { t: "legend", x: 16, y: 222, items: [["red", "攻擊"], ["cyan", "告警資料"], ["green", "處置"]] },
    ] },
    how: [
      ["在做什麼", "企業的帳號、電腦、伺服器和雲端資料都可能被駭客入侵、竊取或勒索加密。資安公司提供軟體和設備，在每一層把關，並在出事時快速找出、隔離問題。"],
      ["怎麼運作", "網路入口用防火牆過濾流量；登入時用多因素驗證確認身分；每台電腦裝端點防護偵測異常程式；雲端再檢查設定與權限。各層的告警送到資安監控中心，由分析師和 AI 判斷要不要處理。"],
      ["關鍵名詞", "零信任：不因為在公司內網就信任，每次存取都要驗證。EDR：端點偵測與回應。SASE：把網路與資安服務搬到雲端。勒索軟體：把資料加密後要贖金。"],
      ["景氣看什麼", "重大資安事件（通常會帶動預算）、企業 IT 預算、法規要求、平台整合趨勢（客戶想少用幾家廠商），以及訂閱收入與續約率。"],
      ["代表公司", "Palo Alto Networks、Fortinet、Check Point 做防火牆與平台，CrowdStrike 做端點防護，Zscaler 與 Cloudflare 做雲端存取，Okta 做身分驗證。台灣也有資安股，但規模小很多。"],
    ] },

  { id: "us-itservice", mk: "us", cat: "軟體", name: "系統整合與委外", icon: "link",
    desc: "幫企業規劃、導入並維運資訊系統的顧問與委外公司，把新舊系統、雲端與 AI 串在一起；靠大量工程師的人力與多年合約賺錢。",
    flow: ["顧問規劃", "系統整合", "導入雲端與 AI", "委外維運", "長期續約"],
    segs: [{ n: "顧問與整合", c: [["ACN", "Accenture", "全球最大 IT 顧問之一"], ["IBM", "IBM", "顧問與混合雲"]] },
      { n: "委外與開發", c: [["CTSH", "Cognizant", "IT 委外"], ["INFY", "Infosys", "印度 IT 委外"], ["EPAM", "EPAM Systems", "軟體開發外包"]] }],
    fig: { w: 360, h: 230, alt: "系統整合與委外：顧問規劃、串接 ERP 雲端與 AI，再接手長期維運，人力主要來自海外交付中心", items: [
      { t: "box", x: 10, y: 30, w: 70, h: 44, label: "企業客戶", sub: "想導入 AI", c: "gray" },
      { t: "arrow", pts: [[80, 52], [104, 52]], c: "green" },
      { t: "box", x: 106, y: 30, w: 70, h: 44, label: "顧問規劃", sub: "畫出藍圖", c: "blue" },
      { t: "arrow", pts: [[176, 52], [198, 52]], c: "blue" },
      { t: "box", x: 200, y: 30, w: 70, h: 44, label: "系統整合", sub: "串接新舊系統", c: "cyan", fill: true },
      { t: "arrow", pts: [[270, 52], [290, 52]], c: "blue" },
      { t: "box", x: 292, y: 30, w: 60, h: 44, label: "委外維運", sub: "多年合約", c: "purple" },
      { t: "line", pts: [[235, 74], [235, 148]], c: "gray" },
      { t: "box", x: 186, y: 94, w: 44, h: 22, label: "ERP", s: 9, c: "cyan" },
      { t: "box", x: 240, y: 94, w: 44, h: 22, label: "雲端", s: 9, c: "cyan" },
      { t: "box", x: 186, y: 124, w: 44, h: 22, label: "資料", s: 9, c: "cyan" },
      { t: "box", x: 240, y: 124, w: 44, h: 22, label: "AI", s: 9, c: "cyan" },
      { t: "icon", x: 70, y: 98, s: 26, k: "globe", c: "orange" }, { t: "text", x: 83, y: 134, s: 8, label: "海外交付", muted: true },
      { t: "icon", x: 120, y: 98, s: 26, k: "person", c: "orange" }, { t: "text", x: 133, y: 134, s: 8, label: "工程師", muted: true },
      { t: "text", x: 190, y: 172, s: 9.5, label: "營收 ≈ 投入人力 × 收費費率", b: true },
      { t: "arrow", pts: [[322, 74], [322, 190], [45, 190], [45, 76]], c: "green", dash: true, label: "長期續約", lx: 184, ly: 204 },
      { t: "legend", x: 16, y: 222, items: [["green", "合約與收費"], ["blue", "專案進行"]] },
    ] },
    how: [
      ["在做什麼", "大企業的系統往往新舊混雜，自己沒有足夠工程師。IT 服務公司幫忙規劃要怎麼改、把 ERP、雲端、資料和 AI 串在一起，之後再接手長期維運。"],
      ["怎麼運作", "先由顧問了解需求、提出藍圖，再派工程師團隊導入與整合系統；完成後常簽多年委外合約，負責維護與升級。大量人力放在印度、東歐等成本較低的交付中心。"],
      ["關鍵名詞", "系統整合（SI）：把不同廠商的系統接起來。委外（outsourcing）：把 IT 工作整包交給外部公司。訂單簽約金額（bookings）：未來營收的領先指標。"],
      ["景氣看什麼", "企業是否願意花錢做轉型專案、新簽約金額、員工使用率與人力成本；也要留意 AI 寫程式工具是否會減少按人力計價的工作量。"],
      ["代表公司", "Accenture、IBM 偏顧問與大型整合，Cognizant、Infosys、EPAM 偏委外開發與維運。台灣的系統整合商規模較小，多服務本地企業與政府。"],
    ] },

  { id: "us-telecom", mk: "us", cat: "網通", name: "電信與數位媒體", icon: "wave",
    desc: "電信業者鋪設基地台與光纖收取每月通話與寬頻費，現金流穩定但投資龐大；數位媒體則製作內容，透過串流平台賺取訂閱與廣告收入。",
    flow: ["鋪設網路", "用戶月費", "內容製作", "串流平台", "訂閱與廣告"],
    segs: [{ n: "電信與寬頻", c: [["TMUS", "T-Mobile US", "行動通訊"], ["VZ", "Verizon", "行動與光纖"], ["T", "AT&T", "行動與光纖"], ["CMCSA", "Comcast", "有線寬頻與 NBC"]] },
      { n: "串流媒體", c: [["NFLX", "Netflix", "影音串流"], ["DIS", "迪士尼", "內容與串流"], ["SPOT", "Spotify", "音樂串流"]] }],
    fig: { w: 360, h: 230, alt: "電信靠基地台與光纖收月費；媒體製作內容放上串流平台，收訂閱費與廣告費", items: [
      { t: "group", x: 8, y: 8, w: 344, h: 98, label: "電信：鋪網路、收月費", c: "blue" },
      { t: "icon", x: 22, y: 34, s: 30, k: "tower", c: "blue" }, { t: "text", x: 37, y: 74, s: 8, label: "基地台", muted: true },
      { t: "arrow", pts: [[54, 52], [74, 52]], c: "blue" },
      { t: "box", x: 76, y: 32, w: 70, h: 40, label: "核心網路", sub: "光纖骨幹", c: "blue" },
      { t: "arrow", pts: [[146, 52], [174, 52]], c: "blue" },
      { t: "icon", x: 178, y: 38, s: 24, k: "phone", c: "cyan" }, { t: "text", x: 190, y: 72, s: 8, label: "手機", muted: true },
      { t: "icon", x: 220, y: 38, s: 24, k: "house", c: "cyan" }, { t: "text", x: 232, y: 72, s: 8, label: "家用寬頻", muted: true },
      { t: "arrow", pts: [[254, 52], [288, 52]], c: "green" },
      { t: "box", x: 290, y: 32, w: 56, h: 40, label: "月費", sub: "穩定現金流", c: "green" },
      { t: "group", x: 8, y: 114, w: 344, h: 90, label: "媒體：做內容、賣訂閱與廣告", c: "purple" },
      { t: "box", x: 18, y: 140, w: 70, h: 44, label: "內容製作", sub: "影集、體育", c: "purple" },
      { t: "arrow", pts: [[88, 162], [116, 162]], c: "purple" },
      { t: "box", x: 118, y: 140, w: 80, h: 44, label: "串流平台", sub: "App 播放", c: "purple", fill: true },
      { t: "arrow", pts: [[198, 152], [236, 148]], c: "green" },
      { t: "arrow", pts: [[198, 172], [236, 176]], c: "orange" },
      { t: "box", x: 238, y: 134, w: 104, h: 26, label: "訂閱費", s: 9, c: "green" },
      { t: "box", x: 238, y: 164, w: 104, h: 26, label: "廣告費", s: 9, c: "orange" },
      { t: "legend", x: 16, y: 222, items: [["blue", "網路訊號"], ["green", "用戶付費"], ["orange", "廣告收入"]] },
    ] },
    how: [
      ["在做什麼", "電信公司蓋基地台、拉光纖，把手機和家裡連上網路，每月收通話與上網費；數位媒體公司拍影集、買體育轉播權，放上串流平台賺訂閱費和廣告費。"],
      ["怎麼運作", "電信要先花大錢買頻譜、建 5G 與光纖網路，之後靠數千萬用戶的月費慢慢回收，所以現金流穩、配息常見。串流平台則是先砸錢做內容吸引會員，會員夠多後再漲價、加廣告方案。"],
      ["關鍵名詞", "ARPU：每個用戶平均每月貢獻多少錢。流失率：退租或退訂的比例。頻譜：政府拍賣的無線電頻段。廣告方案：較便宜但會插廣告的訂閱等級。"],
      ["景氣看什麼", "電信看用戶淨增加數、資本支出與負債、價格競爭；媒體看訂閱人數、漲價後是否流失、廣告市場景氣，以及熱門內容與體育轉播權的成本。"],
      ["代表公司", "電信有 T-Mobile、Verizon、AT&T，有線寬頻有 Comcast；串流有 Netflix、迪士尼、Spotify。台灣對應的是中華電、台灣大、遠傳三大電信，以及供應網通設備的台廠。"],
    ] },

  { id: "us-adtech", mk: "us", cat: "網路平台", name: "數位廣告 AdTech", icon: "globe",
    desc: "網路廣告的買賣系統：廣告主透過買方平台出價，媒體透過賣方平台提供版位，在不到一秒內完成即時競價；Google、Meta 等平台則在自家生態內一手包辦。",
    flow: ["廣告主預算", "買方平台 DSP", "即時競價", "媒體版位", "成效數據回饋"],
    segs: [{ n: "封閉平台", c: [["GOOGL", "Alphabet", "搜尋與 YouTube 廣告"], ["META", "Meta", "社群廣告"], ["AMZN", "亞馬遜", "電商廣告"]] },
      { n: "開放網路廣告", c: [["TTD", "The Trade Desk", "買方平台 DSP"], ["APP", "AppLovin", "行動 App 廣告"], ["MGNI", "Magnite", "賣方平台 SSP"]] }],
    fig: { w: 360, h: 230, alt: "數位廣告：廣告主的預算經買方平台進入即時競價，買到媒體版位讓使用者看到，點擊與購買數據再回饋給廣告主", items: [
      { t: "box", x: 10, y: 30, w: 62, h: 44, label: "廣告主", sub: "品牌、電商", c: "green" },
      { t: "arrow", pts: [[72, 52], [94, 52]], c: "green" },
      { t: "box", x: 96, y: 30, w: 62, h: 44, label: "買方平台", sub: "DSP", c: "blue" },
      { t: "arrow", pts: [[158, 52], [180, 52]], c: "green" },
      { t: "box", x: 182, y: 24, w: 74, h: 56, label: "即時競價", sub: "0.1 秒內成交", c: "orange", fill: true },
      { t: "arrow", pts: [[256, 52], [276, 52]], c: "green" },
      { t: "box", x: 278, y: 30, w: 74, h: 44, label: "媒體版位", sub: "網站、App", c: "purple" },
      { t: "arrow", pts: [[315, 74], [315, 98]], c: "purple" },
      { t: "icon", x: 303, y: 100, s: 24, k: "person", c: "gray" }, { t: "text", x: 315, y: 134, s: 8, label: "使用者", muted: true },
      { t: "arrow", pts: [[300, 114], [40, 114], [40, 76]], c: "cyan", dash: true, label: "點擊、購買數據", lx: 170, ly: 108 },
      { t: "group", x: 8, y: 146, w: 262, h: 58, label: "封閉生態：自己有用戶也賣廣告", c: "gray" },
      { t: "box", x: 18, y: 166, w: 76, h: 28, label: "搜尋廣告", s: 9, c: "blue" },
      { t: "box", x: 101, y: 166, w: 76, h: 28, label: "社群廣告", s: 9, c: "blue" },
      { t: "box", x: 184, y: 166, w: 76, h: 28, label: "電商廣告", s: 9, c: "blue" },
      { t: "legend", x: 16, y: 222, items: [["green", "廣告預算"], ["cyan", "成效數據"]] },
    ] },
    how: [
      ["在做什麼", "你打開網頁或 App 看到的廣告，大多是在你載入頁面的瞬間，由很多廣告主自動出價搶來的。AdTech 就是讓這場買賣自動化、精準化的系統。"],
      ["怎麼運作", "廣告主把預算和目標客群設定在買方平台（DSP）；媒體把版位放上賣方平台（SSP）；使用者一打開頁面，系統在零點幾秒內完成競價、顯示得標廣告，之後的點擊與購買數據再回饋去調整出價。"],
      ["關鍵名詞", "DSP／SSP：買方與賣方平台。程式化購買：用系統自動買廣告。封閉生態：Google、Meta、亞馬遜自己有用戶和廣告系統。ROAS：每花 1 元廣告帶回多少營收。"],
      ["景氣看什麼", "整體廣告預算（跟景氣和消費高度相關）、AI 讓廣告投放更準的效果、隱私規則變化（例如追蹤限制），以及聯網電視、零售媒體等新版位的成長。"],
      ["代表公司", "Alphabet、Meta、亞馬遜是封閉生態的大廣告平台；The Trade Desk 是獨立買方平台，Magnite 是賣方平台，AppLovin 專攻手機遊戲與 App 廣告。"],
    ] },

  { id: "us-exchange", mk: "us", cat: "金融", name: "交易所與金融資料", icon: "link",
    desc: "股票、期貨、選擇權的交易所負責撮合買賣並收手續費，同時把即時報價、指數與信用評級賣給全世界的金融機構，資料授權收入越來越重要。",
    flow: ["投資人下單", "券商送單", "交易所撮合", "結算交割", "資料與指數授權"],
    segs: [{ n: "交易所", c: [["ICE", "洲際交易所", "紐約證交所與期貨"], ["CME", "CME Group", "期貨與選擇權"], ["NDAQ", "Nasdaq", "交易所與金融軟體"], ["CBOE", "Cboe Global Markets", "選擇權"]] },
      { n: "資料、指數與評級", c: [["SPGI", "標普全球", "指數與信用評級"], ["MCO", "穆迪", "信用評級"], ["MSCI", "MSCI", "指數與分析工具"]] }],
    fig: { w: 360, h: 230, alt: "交易所：買賣單經券商送進交易所撮合，再由結算所交割；報價資料與指數授權也帶來收入", items: [
      { t: "icon", x: 14, y: 26, s: 24, k: "person", c: "green" }, { t: "text", x: 26, y: 60, s: 8, label: "買方", muted: true },
      { t: "icon", x: 14, y: 94, s: 24, k: "person", c: "red" }, { t: "text", x: 26, y: 128, s: 8, label: "賣方", muted: true },
      { t: "arrow", pts: [[40, 40], [70, 62]], c: "green" },
      { t: "arrow", pts: [[40, 106], [70, 86]], c: "red" },
      { t: "box", x: 72, y: 52, w: 58, h: 44, label: "券商", sub: "送出委託", c: "gray" },
      { t: "arrow", pts: [[130, 74], [150, 74]], c: "gray" },
      { t: "box", x: 152, y: 46, w: 80, h: 56, label: "交易所", sub: "撮合買賣", c: "blue", fill: true },
      { t: "arrow", pts: [[232, 60], [258, 48]], c: "blue" },
      { t: "arrow", pts: [[232, 88], [258, 100]], c: "purple" },
      { t: "box", x: 260, y: 26, w: 92, h: 38, label: "結算清算", sub: "保證交割", c: "cyan" },
      { t: "box", x: 260, y: 82, w: 92, h: 38, label: "市場資料", sub: "即時報價", c: "purple" },
      { t: "arrow", pts: [[306, 120], [306, 140]], c: "purple" },
      { t: "box", x: 252, y: 142, w: 100, h: 38, label: "指數、評級", sub: "收授權費", c: "purple" },
      { t: "text", x: 120, y: 152, s: 9, label: "三種主要收入", b: true },
      { t: "box", x: 12, y: 162, w: 72, h: 26, label: "交易手續費", s: 9, c: "orange" },
      { t: "box", x: 90, y: 162, w: 66, h: 26, label: "資料訂閱", s: 9, c: "purple" },
      { t: "box", x: 162, y: 162, w: 66, h: 26, label: "指數授權", s: 9, c: "purple" },
      { t: "text", x: 180, y: 212, s: 8, label: "成交量越大、波動越大，手續費收入通常越多", muted: true },
    ] },
    how: [
      ["在做什麼", "交易所是買賣雙方見面的市場，負責把買單和賣單配對成交；它和指數、評級公司也把市場上產生的報價、指數和信用資訊包裝成資料產品，賣給基金和銀行。"],
      ["怎麼運作", "投資人透過券商下單，交易所的電腦依價格與時間優先撮合；成交後由結算所確保錢和股票（或期貨部位）真的交割。過程中產生的即時報價、成交資料會被賣給各金融機構。"],
      ["關鍵名詞", "撮合：把買賣單配對。結算所：站在買賣中間保證交割。指數授權：ETF 追蹤某個指數就要付費給指數公司。信用評級：替公司與債券的違約風險打分數。"],
      ["景氣看什麼", "市場成交量與波動度（波動大時交易多）、利率期貨等避險需求、ETF 資產規模（影響指數授權費）、企業發債量（影響評級收入）。"],
      ["代表公司", "洲際交易所（旗下紐約證交所）、CME（期貨）、Nasdaq、Cboe（選擇權）；標普全球、穆迪、MSCI 做指數與評級。台灣對應的是臺灣證交所與期交所，以及上市的台灣指數公司相關業務。"],
    ] },

  { id: "us-altasset", mk: "us", cat: "金融", name: "另類資產與私募信貸", icon: "layers",
    desc: "向退休基金、保險公司與富裕個人募資，投資未上市公司、直接放款給企業、買不動產與基礎建設（含資料中心），收取管理費與績效分成。",
    flow: ["向出資人募資", "成立基金", "投資或放款", "管理與退出", "收管理費與分成"],
    segs: [{ n: "另類資產管理", c: [["BX", "Blackstone", "私募股權、不動產"], ["KKR", "KKR", "私募股權與基礎建設"], ["APO", "Apollo", "私募信貸與保險"], ["ARES", "Ares Management", "私募信貸"], ["BAM", "Brookfield Asset Management", "基礎建設與再生能源"], ["OWL", "Blue Owl", "私募信貸、資料中心融資"]] }],
    fig: { w: 360, h: 230, alt: "另類資產：退休基金、保險公司與富裕個人出資，資產管理公司投資私募股權、私募信貸、不動產與基礎建設，收管理費與績效分成", items: [
      { t: "group", x: 8, y: 8, w: 84, h: 160, label: "出資人", c: "green" },
      { t: "icon", x: 38, y: 26, s: 24, k: "bank", c: "green" }, { t: "text", x: 50, y: 60, s: 8, label: "退休基金", muted: true },
      { t: "icon", x: 38, y: 76, s: 24, k: "shield", c: "green" }, { t: "text", x: 50, y: 110, s: 8, label: "保險公司", muted: true },
      { t: "icon", x: 38, y: 124, s: 24, k: "person", c: "green" }, { t: "text", x: 50, y: 158, s: 8, label: "富裕個人", muted: true },
      { t: "arrow", pts: [[92, 87], [118, 87]], c: "green" },
      { t: "box", x: 120, y: 58, w: 84, h: 58, label: "資產管理", sub: "基金經理人 GP", c: "blue", fill: true },
      { t: "line", pts: [[222, 33], [222, 159]], c: "blue" },
      { t: "line", pts: [[204, 87], [222, 87]], c: "blue" },
      { t: "arrow", pts: [[222, 33], [238, 33]], c: "blue" },
      { t: "arrow", pts: [[222, 75], [238, 75]], c: "blue" },
      { t: "arrow", pts: [[222, 117], [238, 117]], c: "blue" },
      { t: "arrow", pts: [[222, 159], [238, 159]], c: "blue" },
      { t: "box", x: 240, y: 16, w: 112, h: 34, label: "私募股權", sub: "買公司再改造", c: "purple" },
      { t: "box", x: 240, y: 58, w: 112, h: 34, label: "私募信貸", sub: "直接借錢給企業", c: "purple" },
      { t: "box", x: 240, y: 100, w: 112, h: 34, label: "不動產", sub: "倉庫、公寓", c: "purple" },
      { t: "box", x: 240, y: 142, w: 112, h: 34, label: "基礎建設", sub: "資料中心、電網", c: "purple" },
      { t: "arrow", pts: [[162, 116], [162, 172]], c: "orange" },
      { t: "box", x: 100, y: 174, w: 124, h: 28, label: "管理費＋績效分成", s: 9, c: "orange" },
      { t: "legend", x: 16, y: 222, items: [["green", "資金流入"], ["blue", "投資去向"], ["orange", "公司收入"]] },
    ] },
    how: [
      ["在做什麼", "退休基金、保險公司和有錢人想找股票、公債以外的投資。另類資產管理公司替他們成立基金，去買未上市公司、直接放款給企業、買不動產和資料中心等基礎建設。"],
      ["怎麼運作", "資產管理公司（GP）向出資人（LP）募資成立基金，鎖定期間常長達數年；投資後慢慢改善、收租或收利息，最後賣出或到期回收。公司每年收管理費，賺錢時再抽績效分成。"],
      ["關鍵名詞", "私募股權：買下或入股未上市公司。私募信貸：不透過銀行、直接借錢給企業。AUM：管理資產規模。永續資本：保險資金等不用定期還給出資人的長期資金。"],
      ["景氣看什麼", "募資速度與 AUM 成長、利率（影響信貸收益與資產估值）、併購與 IPO 市場是否熱絡（決定能不能順利退出）、私募信貸的違約率，以及資料中心融資需求。"],
      ["代表公司", "Blackstone、KKR、Apollo、Ares、Brookfield、Blue Owl 是代表業者，近年大量投入資料中心與電力基礎建設的融資；台灣的壽險公司與退休基金也是這類基金常見的出資人。"],
    ] },

  { id: "us-payment", mk: "us", cat: "金融", name: "金融科技與支付", icon: "link",
    desc: "刷卡、手機支付與線上付款背後的系統：卡組織提供清算網路，發卡銀行負責授權，收單與金流業者幫商店收款，每筆交易都會抽一小部分手續費。",
    flow: ["消費者付款", "商店收款", "收單機構", "卡組織網路", "發卡銀行授權"],
    segs: [{ n: "卡組織", c: [["V", "Visa", "全球卡片清算網路"], ["MA", "Mastercard", "全球卡片清算網路"], ["AXP", "American Express", "發卡兼網路"]] },
      { n: "金流與錢包", c: [["PYPL", "PayPal", "線上支付與錢包"], ["XYZ", "Block", "Square 收款與 Cash App"], ["AFRM", "Affirm", "先買後付"]] }],
    fig: { w: 360, h: 230, alt: "支付：消費者刷卡，交易經商店、收單機構、卡組織送到發卡行授權，核准結果再一路傳回；手續費由各方分配", items: [
      { t: "icon", x: 10, y: 40, s: 24, k: "person", c: "gray" }, { t: "text", x: 22, y: 74, s: 8, label: "消費者", muted: true },
      { t: "arrow", pts: [[36, 52], [62, 52]], c: "blue", label: "刷卡", lx: 49, ly: 46 },
      { t: "box", x: 64, y: 32, w: 62, h: 40, label: "商店", sub: "POS、網店", c: "gray" },
      { t: "arrow", pts: [[126, 52], [146, 52]], c: "blue" },
      { t: "box", x: 148, y: 32, w: 62, h: 40, label: "收單機構", sub: "金流服務", c: "cyan" },
      { t: "arrow", pts: [[210, 52], [230, 52]], c: "blue" },
      { t: "box", x: 232, y: 32, w: 60, h: 40, label: "卡組織", sub: "清算網路", c: "purple", fill: true },
      { t: "arrow", pts: [[292, 52], [310, 52]], c: "blue" },
      { t: "box", x: 312, y: 32, w: 44, h: 40, label: "發卡行", s: 9, sub: "授權", c: "green" },
      { t: "arrow", pts: [[334, 72], [334, 92], [44, 92], [44, 80]], c: "green", dash: true, label: "核准結果（約 1～2 秒）", lx: 190, ly: 106 },
      { t: "text", x: 180, y: 128, s: 9, label: "每筆手續費怎麼分", b: true },
      { t: "box", x: 40, y: 138, w: 90, h: 34, label: "發卡行", sub: "交換費", c: "green" },
      { t: "box", x: 135, y: 138, w: 90, h: 34, label: "收單機構", sub: "收單服務費", c: "cyan" },
      { t: "box", x: 230, y: 138, w: 90, h: 34, label: "卡組織", sub: "網路使用費", c: "purple" },
      { t: "text", x: 180, y: 194, s: 8, label: "還有：電子錢包、先買後付、跨境匯款", muted: true },
      { t: "legend", x: 16, y: 218, items: [["blue", "交易請求"], ["green", "核准回傳"]] },
    ] },
    how: [
      ["在做什麼", "你刷卡或用手機付款時，錢要從你的銀行帳戶安全地移到商店手上。支付產業提供這條「金流高速公路」，每經過一筆交易就收一點過路費。"],
      ["怎麼運作", "商店的刷卡機或網店把交易送給收單機構，再經 Visa、Mastercard 等卡組織的網路傳到你的發卡銀行，銀行確認額度後核准，一兩秒內傳回；之後幾天再完成實際的資金清算。"],
      ["關鍵名詞", "發卡行：發信用卡給你的銀行。收單機構：幫商店收款的業者。交換費：商店手續費中付給發卡行的部分。先買後付（BNPL）：把一筆消費分期、通常免息。"],
      ["景氣看什麼", "消費支出與通膨、跨境旅遊交易量（手續費較高）、現金轉數位的速度、各國對手續費的監管，以及新支付方式的競爭。"],
      ["代表公司", "Visa、Mastercard、American Express 是卡組織；PayPal、Block、Affirm 做線上支付、錢包與先買後付。台灣有信用卡收單銀行、電子支付業者，以及做刷卡機的硬體廠。"],
    ] },

  { id: "us-crypto", mk: "us", cat: "金融", name: "加密貨幣與比特幣生態", icon: "chip",
    desc: "比特幣靠全球礦工用專用晶片與大量電力維護公開帳本；投資人透過交易所、現貨 ETF 或持幣公司參與，相關股票隨幣價大幅波動。",
    flow: ["電力與礦機", "挖礦記帳", "新幣獎勵", "交易所買賣", "ETF 與公司持有"],
    segs: [{ n: "交易與持有", c: [["COIN", "Coinbase", "加密貨幣交易所"], ["HOOD", "Robinhood", "券商與加密交易"], ["MSTR", "Strategy", "大量持有比特幣"], ["CRCL", "Circle", "穩定幣 USDC"]] },
      { n: "挖礦", c: [["MARA", "MARA Holdings", "比特幣挖礦"], ["RIOT", "Riot Platforms", "比特幣挖礦"], ["CLSK", "CleanSpark", "比特幣挖礦"]] }],
    fig: { w: 360, h: 230, alt: "比特幣：礦工用電力驅動 ASIC 礦機搶著記帳，成功就拿到新幣獎勵；區塊串成公開帳本，投資人透過交易所、ETF 或公司持有", items: [
      { t: "group", x: 8, y: 8, w: 170, h: 96, label: "挖礦", c: "orange" },
      { t: "icon", x: 18, y: 36, s: 22, k: "bolt", c: "yellow" }, { t: "text", x: 29, y: 68, s: 8, label: "電力", muted: true },
      { t: "arrow", pts: [[42, 47], [60, 47]], c: "yellow" },
      { t: "rack", x: 62, y: 26, w: 42, h: 52, n: 4, c: "orange", label: "ASIC 礦機" },
      { t: "arrow", pts: [[104, 52], [122, 52]], c: "orange" },
      { t: "box", x: 124, y: 32, w: 46, h: 40, label: "算題", s: 9, sub: "搶記帳", c: "orange", fill: true },
      { t: "arrow", pts: [[170, 44], [200, 44]], c: "yellow" },
      { t: "icon", x: 204, y: 30, s: 28, k: "coin", c: "yellow" }, { t: "text", x: 218, y: 68, s: 8, label: "新幣獎勵", muted: true },
      { t: "arrow", pts: [[147, 72], [147, 118]], c: "blue" },
      { t: "box", x: 14, y: 120, w: 44, h: 26, label: "區塊", s: 9, c: "blue" },
      { t: "box", x: 72, y: 120, w: 44, h: 26, label: "區塊", s: 9, c: "blue" },
      { t: "box", x: 130, y: 120, w: 44, h: 26, label: "區塊", s: 9, c: "blue", fill: true },
      { t: "line", pts: [[58, 133], [72, 133]], c: "blue", w: 2 },
      { t: "line", pts: [[116, 133], [130, 133]], c: "blue", w: 2 },
      { t: "text", x: 94, y: 162, s: 8, label: "區塊鏈：大家都能查的公開帳本", muted: true },
      { t: "group", x: 230, y: 84, w: 122, h: 118, label: "怎麼持有", c: "purple" },
      { t: "box", x: 240, y: 102, w: 104, h: 26, label: "交易所", s: 9, c: "purple" },
      { t: "box", x: 240, y: 134, w: 104, h: 26, label: "現貨 ETF", s: 9, c: "purple" },
      { t: "box", x: 240, y: 166, w: 104, h: 26, label: "公司財庫", s: 9, c: "purple" },
      { t: "text", x: 100, y: 196, s: 9, label: "幣價高 → 礦工收入高", b: true },
    ] },
    how: [
      ["在做什麼", "比特幣是一種沒有中央銀行發行的數位貨幣，所有交易記在一本全球公開的帳本（區塊鏈）上。圍繞它形成了挖礦、交易所、ETF、穩定幣等產業。"],
      ["怎麼運作", "礦工用專門的 ASIC 礦機不斷計算數學題，最先算出的人取得記帳權，把一批交易打包成新區塊接到鏈上，並獲得新發行的比特幣當獎勵。一般人則透過交易所、現貨 ETF 或買持幣公司的股票參與。"],
      ["關鍵名詞", "算力（hash rate）：全網挖礦的計算能力。減半：約每四年挖礦獎勵減半一次。穩定幣：和美元一比一掛鉤的代幣。ETF：在股市就能買賣、追蹤比特幣價格的基金。"],
      ["景氣看什麼", "比特幣價格（幾乎決定所有相關股票）、ETF 資金流入流出、美國監管政策、電價與全網算力；部分礦工也把電力與機房轉租給 AI 資料中心。"],
      ["代表公司", "Coinbase、Robinhood 做交易，Strategy 大量持有比特幣，Circle 發行穩定幣，MARA、Riot、CleanSpark 做挖礦。台灣廠商則參與礦機晶片的代工與封測。"],
    ] },

  { id: "us-healthins", mk: "us", cat: "醫療", name: "醫療保險與給付體系", icon: "home",
    desc: "美國人看病多數靠雇主或政府資助的醫療保險；保險公司收保費、付醫院與藥品理賠，獲利取決於「收的保費」和「付出的醫療費」之間的差距。",
    flow: ["雇主與政府付保費", "保險公司", "醫院與醫師", "藥品福利管理", "理賠支付"],
    segs: [{ n: "醫療保險", c: [["UNH", "UnitedHealth", "最大醫療保險與 Optum"], ["ELV", "Elevance Health", "醫療保險"], ["CI", "Cigna", "保險與 Express Scripts"], ["CVS", "CVS Health", "Aetna 保險與藥局"], ["HUM", "Humana", "Medicare 優勢計畫"], ["CNC", "Centene", "Medicaid 保險"]] }],
    fig: { w: 360, h: 230, alt: "醫療保險：雇主與政府付保費給保險公司，保險公司再付理賠給醫院醫師和藥品福利管理；理賠率決定獲利", items: [
      { t: "box", x: 10, y: 22, w: 70, h: 40, label: "雇主", sub: "員工團保", c: "gray" },
      { t: "box", x: 10, y: 78, w: 70, h: 40, label: "政府", sub: "Medicare", c: "gray" },
      { t: "arrow", pts: [[80, 42], [118, 62]], c: "green" },
      { t: "arrow", pts: [[80, 98], [118, 82]], c: "green", label: "保費", lx: 102, ly: 104 },
      { t: "box", x: 120, y: 44, w: 84, h: 56, label: "保險公司", sub: "收保費付理賠", c: "blue", fill: true },
      { t: "arrow", pts: [[204, 58], [244, 40]], c: "red" },
      { t: "arrow", pts: [[204, 86], [244, 104]], c: "red", label: "理賠", lx: 222, ly: 108 },
      { t: "box", x: 246, y: 20, w: 104, h: 38, label: "醫院、醫師", sub: "看診、手術", c: "red" },
      { t: "box", x: 246, y: 86, w: 104, h: 38, label: "藥品福利", sub: "PBM、藥局", c: "red" },
      { t: "icon", x: 150, y: 124, s: 26, k: "person", c: "gray" }, { t: "text", x: 163, y: 160, s: 8, label: "病人", muted: true },
      { t: "arrow", pts: [[178, 140], [296, 140], [296, 126]], c: "gray", dash: true, label: "就醫拿藥", lx: 236, ly: 134 },
      { t: "text", x: 180, y: 182, s: 9.5, label: "理賠率 ＝ 付出的理賠 ÷ 收到的保費", b: true },
      { t: "text", x: 180, y: 198, s: 8, label: "就醫量突然變多，保險公司的獲利就被壓縮", muted: true },
      { t: "legend", x: 16, y: 222, items: [["green", "保費流入"], ["red", "理賠流出"]] },
    ] },
    how: [
      ["在做什麼", "美國沒有台灣這種全民健保，多數人靠公司團保或政府計畫（老人的 Medicare、低收入的 Medicaid）。民間保險公司收保費、替會員付醫療費，賺中間的差額。"],
      ["怎麼運作", "雇主或政府每月付保費給保險公司；會員看病時，醫院和醫師向保險公司請款，藥品則經過藥品福利管理公司（PBM）談價與支付。保險公司事先預估明年醫療費用來訂保費。"],
      ["關鍵名詞", "理賠率（MLR）：理賠占保費的比例，越高代表越不賺。Medicare 優勢計畫：民間公司承接的老人醫保。PBM：替保險公司管理處方藥支出的中間商。"],
      ["景氣看什麼", "醫療使用量是否高於預期、政府給付費率調整、藥價與減重藥等新藥的支出、監管與政策變化；這個產業和電子景氣的相關性低。"],
      ["代表公司", "UnitedHealth、Elevance、Cigna、CVS（Aetna）、Humana、Centene。台灣是單一健保制度，沒有對應的民間醫保產業，可當作理解美國醫療股的背景知識。"],
    ] },

  { id: "us-housing", mk: "us", cat: "房地產", name: "美國房市", icon: "home",
    desc: "美國房市受房貸利率影響最大：利率決定買不買得起，進而影響新屋開工、成屋買賣，並帶動建材、裝修、房貸與搬遷等一長串下游消費。",
    flow: ["房貸利率", "購屋負擔能力", "新屋開工", "成屋買賣", "建材與裝修需求"],
    segs: [{ n: "建商", c: [["DHI", "D.R. Horton", "最大建商之一"], ["LEN", "Lennar", "建商"], ["PHM", "PulteGroup", "建商"], ["NVR", "NVR", "建商"]] },
      { n: "裝修與房貸", c: [["HD", "Home Depot", "建材與居家修繕零售"], ["LOW", "Lowe's", "建材與居家修繕零售"], ["RKT", "Rocket Companies", "房貸"], ["Z", "Zillow", "房產平台"]] }],
    fig: { w: 360, h: 230, alt: "美國房市：房貸利率決定買不買得起，帶動新屋與成屋交易，再帶動建材、裝修、房貸、搬家與家電需求", items: [
      { t: "box", x: 10, y: 22, w: 84, h: 44, label: "房貸利率", sub: "跟著公債走", c: "red" },
      { t: "arrow", pts: [[94, 44], [124, 44]], c: "red" },
      { t: "box", x: 126, y: 22, w: 90, h: 44, label: "買得起嗎", sub: "月付金÷收入", c: "orange" },
      { t: "arrow", pts: [[216, 36], [246, 30]], c: "orange" },
      { t: "arrow", pts: [[216, 54], [246, 72]], c: "orange" },
      { t: "box", x: 248, y: 12, w: 104, h: 36, label: "新屋", sub: "建商蓋房", c: "blue" },
      { t: "box", x: 248, y: 58, w: 104, h: 36, label: "成屋買賣", sub: "仲介、過戶", c: "purple" },
      { t: "arrow", pts: [[300, 94], [300, 110]], c: "green" },
      { t: "group", x: 8, y: 112, w: 344, h: 76, label: "帶動的下游", c: "green" },
      { t: "icon", x: 30, y: 130, s: 24, k: "factory", c: "green" }, { t: "text", x: 42, y: 164, s: 8, label: "建材", muted: true },
      { t: "icon", x: 98, y: 130, s: 24, k: "house", c: "green" }, { t: "text", x: 110, y: 164, s: 8, label: "裝修", muted: true },
      { t: "icon", x: 166, y: 130, s: 24, k: "bank", c: "green" }, { t: "text", x: 178, y: 164, s: 8, label: "房貸", muted: true },
      { t: "icon", x: 234, y: 130, s: 24, k: "truck", c: "green" }, { t: "text", x: 246, y: 164, s: 8, label: "搬家", muted: true },
      { t: "icon", x: 302, y: 130, s: 24, k: "fan", c: "green" }, { t: "text", x: 314, y: 164, s: 8, label: "家電", muted: true },
      { t: "text", x: 180, y: 204, s: 9.5, label: "利率是房市最大的開關", b: true },
      { t: "text", x: 180, y: 220, s: 8, label: "常見指標：新屋開工、成屋銷售、庫存月數", muted: true },
    ] },
    how: [
      ["在做什麼", "美國人買房幾乎都靠 30 年期房貸，房市是美國經濟很重要的引擎：一間房子成交，會帶動建材、裝潢、家具家電、房貸與搬家等一連串消費。"],
      ["怎麼運作", "房貸利率大致跟著 10 年期公債殖利率走。利率高時月付金變重，很多人買不起或不想賣掉手上低利房貸的舊房，成屋交易變少；建商則用補貼利率等方式推新屋，開工量隨需求調整。"],
      ["關鍵名詞", "新屋開工：建商開始動工的數量，是景氣領先指標。成屋銷售：中古屋成交量。庫存月數：以目前速度要幾個月才能賣完待售房屋。鎖定效應：屋主不想放棄低利房貸。"],
      ["景氣看什麼", "房貸利率與聯準會政策、就業與薪資、新屋開工與營建許可、成屋庫存與房價；房市回溫時，建材與居家修繕零售通常跟著受惠。"],
      ["代表公司", "建商有 D.R. Horton、Lennar、PulteGroup、NVR；居家修繕零售有 Home Depot、Lowe's；房貸與平台有 Rocket、Zillow。台灣的五金、手工具、家具與家電出口廠也受美國房市影響。"],
    ] },

  { id: "us-minerals", mk: "us", cat: "原物料", name: "關鍵礦產與金屬", icon: "factory",
    desc: "銅、鋰、鎳、稀土、鎵、鍺等金屬是電動車、電網、AI 資料中心與國防的基礎材料；精煉產能高度集中，因此成為各國補貼與出口管制的焦點。",
    flow: ["開採礦石", "選礦", "精煉提純", "金屬材料", "電池、馬達、電網"],
    segs: [{ n: "銅與鋁", c: [["FCX", "Freeport-McMoRan", "銅礦"], ["SCCO", "Southern Copper", "銅礦"], ["AA", "Alcoa", "鋁"]] },
      { n: "鋰與稀土", c: [["ALB", "Albemarle", "鋰"], ["MP", "MP Materials", "稀土礦與磁材"]] }],
    fig: { w: 360, h: 230, alt: "關鍵礦產：礦石經選礦、精煉成金屬材料，再做成電池、馬達磁鐵、晶片與電線，用在電動車、機器人、電子與電網", items: [
      { t: "box", x: 10, y: 30, w: 60, h: 44, label: "礦山", sub: "挖礦石", c: "gray" },
      { t: "arrow", pts: [[70, 52], [90, 52]], c: "gray" },
      { t: "box", x: 92, y: 30, w: 60, h: 44, label: "選礦", sub: "提高濃度", c: "orange" },
      { t: "arrow", pts: [[152, 52], [172, 52]], c: "orange" },
      { t: "box", x: 174, y: 30, w: 66, h: 44, label: "精煉", sub: "分離、提純", c: "red", fill: true },
      { t: "text", x: 207, y: 22, s: 8, label: "產能最集中", c: "red" },
      { t: "arrow", pts: [[240, 52], [260, 52]], c: "red" },
      { t: "box", x: 262, y: 30, w: 88, h: 44, label: "金屬材料", sub: "氧化物、合金", c: "blue" },
      { t: "arrow", pts: [[306, 74], [306, 100]], c: "blue" },
      { t: "box", x: 14, y: 102, w: 78, h: 40, label: "鋰鎳鈷", sub: "電池", c: "green" },
      { t: "box", x: 100, y: 102, w: 78, h: 40, label: "稀土", sub: "馬達磁鐵", c: "purple" },
      { t: "box", x: 186, y: 102, w: 78, h: 40, label: "鎵、鍺", sub: "晶片、光電", c: "cyan" },
      { t: "box", x: 272, y: 102, w: 78, h: 40, label: "銅", sub: "電線、電網", c: "orange" },
      { t: "icon", x: 41, y: 154, s: 24, k: "car", c: "gray" }, { t: "text", x: 53, y: 188, s: 8, label: "電動車", muted: true },
      { t: "icon", x: 127, y: 154, s: 24, k: "robot", c: "gray" }, { t: "text", x: 139, y: 188, s: 8, label: "機器人", muted: true },
      { t: "icon", x: 213, y: 154, s: 24, k: "laptop", c: "gray" }, { t: "text", x: 225, y: 188, s: 8, label: "電子", muted: true },
      { t: "icon", x: 299, y: 154, s: 24, k: "tower", c: "gray" }, { t: "text", x: 311, y: 188, s: 8, label: "電網", muted: true },
      { t: "text", x: 180, y: 216, s: 8, label: "供應集中 → 各國補貼、出口管制、建立庫存", muted: true },
    ] },
    how: [
      ["在做什麼", "電動車電池要鋰、鎳、鈷，馬達要稀土磁鐵，晶片與光通訊要鎵、鍺，電網和資料中心要大量的銅。這些「關鍵礦產」決定了科技產業能不能穩定生產。"],
      ["怎麼運作", "礦石開採後先選礦提高濃度，再經冶煉、化學分離與提純，做成金屬、氧化物或合金。挖礦的地點分散在各國，但精煉與分離產能高度集中在中國，這是供應鏈最大的風險點。"],
      ["關鍵名詞", "精煉：把礦石變成高純度金屬。稀土：一組 17 種元素，做強力永久磁鐵。出口管制：限制關鍵材料或技術出口。長約與保證價格：政府或大客戶確保供應的方式。"],
      ["景氣看什麼", "金屬價格與庫存、電動車與電網投資、中國的出口管制動向、美國政府的補貼與入股、新礦與精煉廠的建置進度；價格波動通常比一般產業股大。"],
      ["代表公司", "Freeport-McMoRan、Southern Copper 是大型銅礦商，Alcoa 做鋁，Albemarle 是鋰業龍頭，MP Materials 經營美國稀土礦與磁材。台灣幾乎不產礦，電子與電池產業是這些材料的使用者。"],
    ] },

  { id: "us-oilgas", mk: "us", cat: "能源", name: "能源油氣", icon: "bolt",
    desc: "石油與天然氣從上游開採、中游管線運輸，到下游煉油與發電；美國頁岩油氣讓它成為最大產油國之一，天然氣也是 AI 資料中心的重要電力來源。",
    flow: ["探勘開採", "管線運輸", "煉油", "汽柴油與塑化", "天然氣發電與出口"],
    segs: [{ n: "整合與上游", c: [["XOM", "ExxonMobil", "整合型石油公司"], ["CVX", "Chevron", "整合型石油公司"], ["COP", "ConocoPhillips", "上游開採"], ["EOG", "EOG Resources", "頁岩油"]] },
      { n: "天然氣與中游", c: [["EQT", "EQT", "天然氣生產"], ["KMI", "Kinder Morgan", "天然氣管線"], ["LNG", "Cheniere Energy", "液化天然氣出口"], ["SLB", "SLB", "油田服務"]] }],
    fig: { w: 360, h: 230, alt: "油氣：油井產出的石油經管線送到煉油廠做成汽柴油與塑化原料；天然氣送去發電供應資料中心，或液化出口", items: [
      { t: "icon", x: 14, y: 22, s: 32, k: "oil", c: "orange" }, { t: "text", x: 30, y: 64, s: 8, label: "油井", muted: true },
      { t: "arrow", pts: [[48, 42], [76, 42]], c: "orange" },
      { t: "box", x: 78, y: 22, w: 60, h: 40, label: "管線", sub: "中游運輸", c: "yellow" },
      { t: "arrow", pts: [[138, 42], [164, 42]], c: "orange" },
      { t: "box", x: 166, y: 22, w: 66, h: 40, label: "煉油廠", sub: "下游", c: "red" },
      { t: "arrow", pts: [[232, 42], [262, 42]], c: "orange" },
      { t: "icon", x: 266, y: 28, s: 24, k: "car", c: "orange" }, { t: "text", x: 278, y: 62, s: 8, label: "汽柴油", muted: true },
      { t: "icon", x: 318, y: 28, s: 24, k: "flask", c: "orange" }, { t: "text", x: 330, y: 62, s: 8, label: "塑化", muted: true },
      { t: "arrow", pts: [[30, 80], [30, 112], [76, 112]], c: "cyan" },
      { t: "box", x: 78, y: 92, w: 60, h: 40, label: "天然氣", sub: "頁岩氣", c: "cyan" },
      { t: "arrow", pts: [[138, 112], [164, 112]], c: "cyan" },
      { t: "box", x: 166, y: 92, w: 66, h: 40, label: "發電廠", sub: "燃氣機組", c: "cyan" },
      { t: "arrow", pts: [[232, 112], [262, 112]], c: "cyan" },
      { t: "icon", x: 266, y: 100, s: 24, k: "cloud", c: "cyan" }, { t: "text", x: 278, y: 134, s: 8, label: "資料中心", muted: true },
      { t: "arrow", pts: [[108, 132], [108, 152]], c: "cyan" },
      { t: "box", x: 70, y: 154, w: 76, h: 34, label: "LNG 出口", sub: "船運到亞洲", c: "purple" },
      { t: "icon", x: 158, y: 160, s: 24, k: "ship", c: "purple" },
      { t: "text", x: 290, y: 160, s: 9, label: "看什麼", b: true },
      { t: "text", x: 290, y: 175, s: 8, label: "油價、OPEC+", muted: true },
      { t: "text", x: 290, y: 188, s: 8, label: "鑽井數、庫存", muted: true },
      { t: "legend", x: 16, y: 222, items: [["orange", "石油"], ["cyan", "天然氣"]] },
    ] },
    how: [
      ["在做什麼", "把地底的石油和天然氣開採出來，運送、加工成汽油、柴油、航空燃油和塑化原料，或拿天然氣去發電、液化出口。這是全球最大的能源來源之一。"],
      ["怎麼運作", "上游公司鑽井開採（美國主要是頁岩，用水平鑽井與壓裂），中游用管線與儲槽運送，下游煉油廠把原油分餾成各種油品。天然氣則透過管線送到發電廠，或冷卻成液化天然氣（LNG）用船出口。"],
      ["關鍵名詞", "上中下游：開採、運輸、加工。頁岩油氣：從頁岩層開採的油氣。OPEC+：主要產油國聯盟，會調整產量影響油價。LNG：液化天然氣，方便長途海運。"],
      ["景氣看什麼", "國際油價與天然氣價、OPEC+ 產量政策、美國鑽井數與庫存、煉油價差；AI 資料中心用電增加，讓天然氣發電需求受到關注。"],
      ["代表公司", "ExxonMobil、Chevron 是整合型大廠，ConocoPhillips、EOG 偏上游，EQT 產天然氣，Kinder Morgan 經營管線，Cheniere 出口 LNG，SLB 提供油田服務。台灣的台塑化、中油與 LNG 進口都和國際油氣價格相關。"],
    ] },

  { id: "us-machinery", mk: "us", cat: "工業", name: "重工機械", icon: "factory",
    desc: "挖土機、礦用卡車、農機、引擎與發電機組等大型機械，服務基建、礦業、農業與能源；景氣循環明顯，但龐大的售後零件與服務提供穩定收入。",
    flow: ["基建與礦業需求", "機械廠製造", "經銷商銷售", "設備使用", "售後零件與服務"],
    segs: [{ n: "機械製造", c: [["CAT", "Caterpillar", "營建與礦業機械、發電機組"], ["DE", "Deere", "農業機械"], ["CMI", "Cummins", "引擎與發電機"], ["PCAR", "PACCAR", "重型卡車"]] },
      { n: "能源設備與租賃", c: [["GEV", "GE Vernova", "燃氣渦輪與電網設備"], ["URI", "United Rentals", "設備租賃"]] }],
    fig: { w: 360, h: 230, alt: "重工機械：基建、農業、礦業與發電需求帶來訂單，機械廠製造後經經銷商銷售，再靠零件與服務長期收費", items: [
      { t: "group", x: 8, y: 8, w: 112, h: 136, label: "需求來源", c: "gray" },
      { t: "icon", x: 20, y: 28, s: 24, k: "tower", c: "gray" }, { t: "text", x: 32, y: 62, s: 8, label: "基建", muted: true },
      { t: "icon", x: 74, y: 28, s: 24, k: "sun", c: "gray" }, { t: "text", x: 86, y: 62, s: 8, label: "農業", muted: true },
      { t: "icon", x: 20, y: 84, s: 24, k: "truck", c: "gray" }, { t: "text", x: 32, y: 118, s: 8, label: "礦業", muted: true },
      { t: "icon", x: 74, y: 84, s: 24, k: "bolt", c: "gray" }, { t: "text", x: 86, y: 118, s: 8, label: "發電", muted: true },
      { t: "arrow", pts: [[120, 76], [144, 76]], c: "blue" },
      { t: "box", x: 146, y: 40, w: 90, h: 72, label: "機械廠", sub: "挖土機、引擎", c: "orange", fill: true },
      { t: "arrow", pts: [[236, 64], [262, 64]], c: "blue" },
      { t: "box", x: 264, y: 44, w: 86, h: 40, label: "經銷商", sub: "銷售與維修", c: "blue" },
      { t: "arrow", pts: [[307, 84], [307, 110]], c: "green" },
      { t: "box", x: 264, y: 112, w: 86, h: 40, label: "零件與服務", sub: "機器用越久越需要", c: "green" },
      { t: "text", x: 180, y: 180, s: 9.5, label: "景氣循環：商品價格、基建預算、利率", b: true },
      { t: "text", x: 180, y: 198, s: 8, label: "AI 資料中心帶動發電機組與燃氣渦輪需求", muted: true },
      { t: "legend", x: 16, y: 222, items: [["blue", "新機銷售"], ["green", "售後收入"]] },
    ] },
    how: [
      ["在做什麼", "製造蓋路挖地的營建機械、礦場用的大型卡車、農夫用的曳引機與收割機，以及卡車引擎、柴油發電機組和燃氣渦輪等大型設備。"],
      ["怎麼運作", "政府基建、礦業公司、農民與電力業者下單，機械廠在工廠組裝後透過各地經銷商銷售與維修。機器動輒用十幾年，期間需要不斷更換零件與保養，售後收入相對穩定。"],
      ["關鍵名詞", "經銷商網路：負責銷售、租賃與維修的在地夥伴。售後市場：零件與服務。積壓訂單（backlog）：已接但還沒交貨的訂單。發電機組：資料中心的備用電源。"],
      ["景氣看什麼", "基建法案與政府預算、銅鐵等商品價格（影響礦業投資）、農產品價格與農民收入、利率、經銷商庫存，以及資料中心帶來的發電設備訂單。"],
      ["代表公司", "Caterpillar（營建礦業機械與發電機組）、Deere（農機）、Cummins（引擎）、PACCAR（卡車）、GE Vernova（燃氣渦輪），以及設備租賃商 United Rentals。台灣有供應零件、液壓件與鑄件的廠商。"],
    ] },

  { id: "jp-nand", mk: "jp", cat: "記憶體", name: "日本 NAND 記憶體", icon: "memory",
    desc: "NAND 快閃記憶體斷電後資料不會消失，做成 SSD 和手機儲存；日本鎧俠和美國 SanDisk 共同營運大型晶圓廠，並以 3D 堆疊技術提高容量。",
    flow: ["晶圓", "3D 堆疊儲存單元", "封裝與控制器", "SSD 與記憶卡", "資料中心、手機"],
    segs: [{ n: "NAND 製造", c: [["285A.T", "鎧俠（Kioxia）", "NAND 快閃記憶體"], ["SNDK", "SanDisk", "美國合資夥伴"]] },
      { n: "設備與材料", c: [["8035.T", "東京威力科創", "蝕刻與沉積設備"], ["4186.T", "東京應化", "光阻劑"], ["3436.T", "SUMCO", "矽晶圓"]] }],
    fig: { w: 360, h: 230, alt: "NAND：在晶圓上把儲存單元往上堆疊上百層，封裝後加上控制器做成 SSD，用在資料中心、筆電、手機與汽車", items: [
      { t: "wafer", x: 40, y: 60, r: 28, label: "晶圓", c: "blue" },
      { t: "arrow", pts: [[72, 60], [98, 60]], c: "gray" },
      { t: "text", x: 130, y: 20, s: 8, label: "上百層儲存單元", muted: true },
      { t: "stack", x: 100, y: 28, w: 60, h: 64, n: 8, label: "3D 堆疊", c: "purple" },
      { t: "arrow", pts: [[162, 60], [186, 60]], c: "gray" },
      { t: "box", x: 188, y: 36, w: 62, h: 48, label: "封裝", sub: "加控制器", c: "orange" },
      { t: "arrow", pts: [[250, 60], [270, 60]], c: "gray" },
      { t: "box", x: 272, y: 36, w: 78, h: 48, label: "SSD", sub: "固態硬碟", c: "cyan", fill: true },
      { t: "text", x: 180, y: 124, s: 9, label: "用在哪", b: true },
      { t: "icon", x: 48, y: 132, s: 24, k: "cloud", c: "cyan" }, { t: "text", x: 60, y: 166, s: 8, label: "資料中心", muted: true },
      { t: "icon", x: 128, y: 132, s: 24, k: "laptop", c: "cyan" }, { t: "text", x: 140, y: 166, s: 8, label: "筆電", muted: true },
      { t: "icon", x: 208, y: 132, s: 24, k: "phone", c: "cyan" }, { t: "text", x: 220, y: 166, s: 8, label: "手機", muted: true },
      { t: "icon", x: 288, y: 132, s: 24, k: "car", c: "cyan" }, { t: "text", x: 300, y: 166, s: 8, label: "車用", muted: true },
      { t: "text", x: 180, y: 194, s: 9.5, label: "AI 推論要存大量資料 → 大容量 SSD", b: true },
      { t: "text", x: 180, y: 210, s: 8, label: "價格隨供需大幅波動，景氣循環明顯", muted: true },
    ] },
    how: [
      ["在做什麼", "NAND 快閃記憶體是「斷電也記得住」的儲存晶片，做成資料中心的 SSD、筆電硬碟、手機儲存空間和記憶卡。它和 DRAM（工作記憶體）是記憶體的兩大類。"],
      ["怎麼運作", "在晶圓上反覆沉積薄膜，把儲存單元像蓋大樓一樣往上疊到兩三百層，再用深孔蝕刻打通；做好的晶片封裝後搭配控制器晶片，管理讀寫與壽命，組成 SSD。"],
      ["關鍵名詞", "3D NAND：垂直堆疊的快閃記憶體，層數越多容量越大。控制器：SSD 的大腦。QLC／TLC：每個單元存 4 或 3 位元。企業級 SSD：資料中心用、容量與耐用度更高。"],
      ["景氣看什麼", "NAND 合約價、廠商減產或擴產、資料中心 SSD 需求（AI 推論與儲存）、手機與 PC 出貨；記憶體價格常大起大落，是典型的景氣循環產業。"],
      ["和台灣的關係", "台灣群聯、慧榮等公司設計 NAND 控制器，威剛、宇瞻等做記憶體模組，力成等封測廠承接封裝測試；鎧俠的晶圓廠則在日本四日市與北上。"],
    ] },

  { id: "jp-copperfoil", mk: "jp", cat: "PCB", name: "日本銅箔", icon: "layers",
    desc: "銅箔是銅箔基板與印刷電路板的導電層；AI 伺服器與高速交換器需要表面極平滑的高階銅箔來降低訊號損耗，日本廠在高階與載板用極薄銅箔具優勢。",
    flow: ["銅原料", "電解析出", "表面處理", "銅箔基板 CCL", "PCB 與載板"],
    segs: [{ n: "銅箔", c: [["5706.T", "三井金屬", "載板用極薄銅箔"], ["5801.T", "古河電工", "電解銅箔"], ["5016.T", "JX 金屬", "壓延銅箔與半導體材料"]] }],
    fig: { w: 360, h: 230, alt: "銅箔：銅在電解槽裡析出成薄銅箔，貼上樹脂做成 CCL 再做成 PCB；表面越平滑，高速訊號損耗越小", items: [
      { t: "box", x: 10, y: 30, w: 54, h: 40, label: "銅原料", s: 9, c: "orange" },
      { t: "arrow", pts: [[64, 50], [84, 50]], c: "orange" },
      { t: "box", x: 86, y: 24, w: 76, h: 52, label: "電解槽", sub: "滾筒析出銅", c: "red" },
      { t: "arrow", pts: [[162, 50], [184, 50]], c: "orange" },
      { t: "box", x: 186, y: 34, w: 60, h: 32, label: "銅箔", sub: "很薄", c: "orange", fill: true },
      { t: "arrow", pts: [[246, 50], [266, 50]], c: "orange" },
      { t: "stack", x: 268, y: 30, w: 82, h: 40, n: 4, label: "CCL 基板", c: "yellow" },
      { t: "arrow", pts: [[309, 84], [309, 108]], c: "green" },
      { t: "box", x: 268, y: 110, w: 82, h: 38, label: "PCB", sub: "伺服器主板", c: "green" },
      { t: "group", x: 10, y: 96, w: 236, h: 82, label: "為什麼要「低粗糙度」", c: "blue" },
      { t: "arrow", pts: [[24, 122], [92, 122]], c: "blue", dash: true },
      { t: "line", pts: [[24, 140], [34, 132], [44, 140], [54, 132], [64, 140], [74, 132], [84, 140], [92, 134]], c: "orange", w: 2 },
      { t: "text", x: 58, y: 164, s: 8, label: "粗：訊號損耗大", muted: true },
      { t: "arrow", pts: [[140, 122], [220, 122]], c: "blue" },
      { t: "line", pts: [[140, 136], [220, 136]], c: "orange", w: 3 },
      { t: "text", x: 180, y: 164, s: 8, label: "平滑：適合高速", muted: true },
      { t: "text", x: 180, y: 198, s: 9.5, label: "AI 伺服器、高速交換器需要高階銅箔", b: true },
      { t: "legend", x: 16, y: 222, items: [["blue", "高速訊號"], ["orange", "銅箔表面"]] },
    ] },
    how: [
      ["在做什麼", "銅箔是一層比頭髮還薄的銅片，貼在玻纖布與樹脂上做成銅箔基板（CCL），再蝕刻成印刷電路板上的線路。訊號和電流都靠它傳遞。"],
      ["怎麼運作", "把銅溶成電解液，通電後銅會在旋轉的鈦滾筒上析出成連續的薄片，剝下來後做表面處理（粗化、防鏽）。高階產品要讓表面越平滑越好，又要黏得住樹脂，製程控制很難。"],
      ["關鍵名詞", "HVLP：超低輪廓銅箔，表面極平滑，用於高速板。集膚效應：高頻訊號只走在導體表面，所以表面粗糙會增加損耗。極薄銅箔：附載體的超薄銅箔，用於 IC 載板。"],
      ["景氣看什麼", "AI 伺服器與 800G／1.6T 交換器出貨（帶動高階 CCL）、高階銅箔的產能與加工費、銅價、IC 載板需求；一般消費電子用銅箔則競爭激烈。"],
      ["和台灣的關係", "台灣的台光電、聯茂、台燿等 CCL 廠是高階銅箔的主要買家，金居等台廠也生產高階銅箔；日本廠在載板用極薄銅箔等領域較具優勢。"],
    ] },

  { id: "kr-components", mk: "kr", cat: "電子零組件", name: "韓國電子元件", icon: "layers",
    desc: "韓國的被動元件、IC 載板與相機模組廠，以三星電機和 LG Innotek 為代表，客戶包括手機品牌、AI 伺服器與汽車，與日本、台灣廠商在同一市場競爭。",
    flow: ["陶瓷與樹脂材料", "MLCC 與載板", "相機模組", "手機、伺服器、汽車"],
    segs: [{ n: "元件與載板", c: [["009150.KS", "三星電機", "MLCC、FC-BGA 載板、相機模組"], ["011070.KS", "LG Innotek", "相機模組、載板"], ["007660.KS", "ISU Petasys", "AI 伺服器多層板"]] }],
    fig: { w: 360, h: 230, alt: "韓國電子元件：MLCC、封裝載板與相機模組三大產品，用在 AI 伺服器、手機、汽車與電腦", items: [
      { t: "box", x: 10, y: 20, w: 100, h: 40, label: "MLCC", sub: "陶瓷疊層電容", c: "blue" },
      { t: "stack", x: 30, y: 70, w: 60, h: 36, n: 6, c: "blue" },
      { t: "box", x: 130, y: 20, w: 100, h: 40, label: "封裝載板", sub: "FC-BGA", c: "yellow" },
      { t: "stack", x: 150, y: 70, w: 60, h: 36, n: 4, c: "yellow" },
      { t: "box", x: 250, y: 20, w: 100, h: 40, label: "相機模組", sub: "鏡頭＋感測器", c: "purple" },
      { t: "icon", x: 286, y: 72, s: 30, k: "camera", c: "purple" },
      { t: "line", pts: [[20, 124], [340, 124]], c: "gray", dash: true },
      { t: "text", x: 180, y: 140, s: 9, label: "用在哪", b: true },
      { t: "icon", x: 40, y: 150, s: 24, k: "cloud", c: "cyan" }, { t: "text", x: 52, y: 184, s: 8, label: "AI 伺服器", muted: true },
      { t: "icon", x: 120, y: 150, s: 24, k: "phone", c: "cyan" }, { t: "text", x: 132, y: 184, s: 8, label: "手機", muted: true },
      { t: "icon", x: 200, y: 150, s: 24, k: "car", c: "cyan" }, { t: "text", x: 212, y: 184, s: 8, label: "汽車", muted: true },
      { t: "icon", x: 280, y: 150, s: 24, k: "laptop", c: "cyan" }, { t: "text", x: 292, y: 184, s: 8, label: "電腦", muted: true },
      { t: "text", x: 180, y: 212, s: 8, label: "和日本、台灣廠商在同一個市場競爭", muted: true },
    ] },
    how: [
      ["在做什麼", "韓國電子元件廠生產三類關鍵零件：調節電流的 MLCC 積層陶瓷電容、承載晶片的 IC 封裝載板，以及手機與汽車用的相機模組，主要客戶是全球手機品牌、伺服器與車廠。"],
      ["怎麼運作", "MLCC 把陶瓷薄片和電極印刷後疊上數百層再燒結；FC-BGA 載板用多層增層材料做出細線路，連接晶片和主機板；相機模組把鏡頭、感測器與對焦機構組裝在一起。"],
      ["關鍵名詞", "MLCC：最常見的被動元件，一支手機用上千顆。FC-BGA：高階處理器用的封裝載板。多層板：AI 伺服器與交換器用、層數很高的 PCB。車規：汽車用、要求更嚴格的品質等級。"],
      ["景氣看什麼", "手機新機出貨、AI 伺服器與 AI 晶片的載板需求、車用電子比重、MLCC 庫存與報價，以及韓元匯率。"],
      ["和台灣的關係", "MLCC 對手是台灣國巨、華新科與日本村田；載板對手是欣興、南電、景碩；相機鏡頭則有大立光、玉晶光。看韓國廠的財報與展望，可以推估同業景氣。"],
    ] },
);
