/* 精細版（新題材）：加密貨幣、美國醫療保險、美國房市、關鍵礦產、能源油氣、重工機械、日本 NAND、日本銅箔、韓國電子元件。圖上的編號圓點對應 chain 第 n 段。 */
INDUSTRY_PACK.push(
  { id: "us-crypto", mk: "us", cat: "金融", name: "加密貨幣與比特幣生態", icon: "chip",
    desc: "比特幣靠全球礦工用專用晶片與大量電力維護公開帳本；投資人透過交易所、現貨 ETF 或持幣公司參與，相關股票隨幣價大幅波動。",
    flow: ["電力與礦機", "挖礦記帳", "新幣獎勵", "交易所買賣", "ETF 與公司持有"],
    segs: [{ n: "交易與持有", c: [["COIN", "Coinbase", "加密貨幣交易所"], ["HOOD", "Robinhood", "券商與加密交易"], ["MSTR", "Strategy", "大量持有比特幣"], ["CRCL", "Circle", "穩定幣 USDC"]] },
      { n: "挖礦", c: [["MARA", "MARA Holdings", "比特幣挖礦"], ["RIOT", "Riot Platforms", "比特幣挖礦"], ["CLSK", "CleanSpark", "比特幣挖礦"]] }],
    fig: { w: 400, h: 280, alt: "比特幣：電力驅動 ASIC 礦機計算雜湊搶記帳，成功者把交易打包成新區塊並拿到新幣；投資人透過交易所、穩定幣、現貨 ETF 與持幣公司參與", items: [
      { t: "group", x: 8, y: 16, w: 178, h: 132, label: "挖礦機房", c: "orange" },
      { t: "icon", x: 16, y: 40, s: 22, k: "bolt", c: "yellow" }, { t: "text", x: 27, y: 76, s: 8, label: "電力", muted: true },
      { t: "arrow", pts: [[40, 51], [54, 51]], c: "yellow" },
      { t: "rack", x: 56, y: 30, w: 42, h: 66, n: 6, c: "orange" },
      { t: "fan", x: 116, y: 44, r: 9, c: "gray" }, { t: "fan", x: 116, y: 72, r: 9, c: "gray" },
      { t: "text", x: 116, y: 94, s: 7.5, label: "排熱", muted: true },
      { t: "path", d: "M77 96V104", c: "orange", w: 1.2 },
      { t: "chip", x: 60, y: 108, w: 34, h: 22, label: "ASIC", c: "purple" },
      { t: "badge", x: 30, y: 116, n: 1, c: "purple" },
      { t: "text", x: 138, y: 118, s: 8, label: "SHA-256", muted: true }, { t: "text", x: 138, y: 130, s: 8, label: "猜答案搶記帳", muted: true },
      { t: "icon", x: 148, y: 34, s: 24, k: "coin", c: "yellow" },
      { t: "text", x: 160, y: 70, s: 7.5, label: "新幣獎勵", muted: true }, { t: "text", x: 160, y: 82, s: 7.5, label: "約四年減半", muted: true },
      { t: "badge", x: 178, y: 26, n: 2, c: "orange" },
      // 區塊鏈
      { t: "rect", x: 20, y: 166, w: 50, h: 34, c: "blue", fill: 0.08 }, { t: "rect", x: 20, y: 166, w: 50, h: 9, c: "blue", fill: 0.45 },
      { t: "path", d: "M26 182h38M26 188h30M26 194h34", c: "blue", w: 0.8 },
      { t: "rect", x: 84, y: 166, w: 50, h: 34, c: "blue", fill: 0.08 }, { t: "rect", x: 84, y: 166, w: 50, h: 9, c: "blue", fill: 0.45 },
      { t: "path", d: "M90 182h38M90 188h30M90 194h34", c: "blue", w: 0.8 },
      { t: "rect", x: 148, y: 166, w: 50, h: 34, c: "blue", fill: 0.22 }, { t: "rect", x: 148, y: 166, w: 50, h: 9, c: "blue", fill: 0.6 },
      { t: "path", d: "M154 182h38M154 188h30M154 194h34", c: "blue", w: 0.8 },
      { t: "path", d: "M70 171h14M134 171h14", c: "blue", w: 2.2 },
      { t: "arrow", pts: [[173, 148], [173, 164]], c: "orange" }, { t: "text", x: 180, y: 160, s: 7.5, a: "start", label: "打包交易", muted: true },
      { t: "text", x: 173, y: 213, s: 7.5, label: "新區塊", muted: true },
      { t: "text", x: 84, y: 220, s: 8.5, b: true, label: "公開帳本（區塊鏈）" },
      // 交易與持有
      { t: "group", x: 232, y: 16, w: 160, h: 206, label: "交易與持有", c: "purple" },
      { t: "box", x: 242, y: 34, w: 62, h: 40, label: "交易所", sub: "撮合買賣", c: "blue" },
      { t: "badge", x: 242, y: 34, n: 3, c: "blue" },
      { t: "text", x: 324, y: 46, s: 7.5, label: "賣", c: "red" }, { t: "text", x: 324, y: 69, s: 7.5, label: "買", c: "green" },
      { t: "rect", x: 340, y: 36, w: 40, h: 5, c: "red", fill: 0.5, stroke: false }, { t: "rect", x: 348, y: 43, w: 32, h: 5, c: "red", fill: 0.5, stroke: false },
      { t: "rect", x: 334, y: 59, w: 46, h: 5, c: "green", fill: 0.5, stroke: false }, { t: "rect", x: 344, y: 66, w: 36, h: 5, c: "green", fill: 0.5, stroke: false },
      { t: "path", d: "M332 53h50", c: "gray", w: 0.8, dash: true },
      { t: "text", x: 357, y: 84, s: 7.5, label: "掛單簿", muted: true },
      { t: "circle", x: 256, y: 114, r: 12, c: "green", fill: 0.2 }, { t: "text", x: 256, y: 118, s: 10, b: true, label: "$" },
      { t: "arrow", pts: [[268, 114], [285, 114]], c: "cyan" },
      { t: "circle", x: 300, y: 114, r: 14, c: "cyan", fill: 0.35 }, { t: "text", x: 300, y: 117, s: 7.5, b: true, label: "USDC" },
      { t: "line", pts: [[314, 114], [334, 114]], c: "gray", dash: true, w: 1.2 },
      { t: "box", x: 336, y: 102, w: 48, h: 24, label: "美債準備", s: 8, c: "gray" },
      { t: "text", x: 312, y: 144, s: 8, label: "穩定幣 1:1 掛鉤美元", muted: true },
      { t: "badge", x: 244, y: 100, n: 4, c: "cyan" },
      { t: "box", x: 242, y: 160, w: 66, h: 44, label: "現貨 ETF", sub: "股市就能買", c: "green" },
      { t: "badge", x: 242, y: 160, n: 5, c: "green" },
      { t: "box", x: 318, y: 160, w: 66, h: 44, label: "持幣公司", sub: "發債買幣", c: "pink" },
      { t: "badge", x: 318, y: 160, n: 6, c: "pink" },
      { t: "arrow", pts: [[198, 183], [240, 183]], c: "blue", dash: true },
      { t: "text", x: 200, y: 246, s: 9, b: true, label: "幣價決定礦工與交易所獲利" },
      { t: "legend", x: 14, y: 270, items: [["yellow", "電力與新幣"], ["blue", "帳本與交易"], ["pink", "資金端"]] },
    ] },
    how: [
      ["在做什麼", "比特幣是一種沒有中央銀行發行的數位貨幣，所有交易記在一本全球公開的帳本（區塊鏈）上。圍繞它形成了挖礦、交易所、穩定幣、ETF 與持幣公司等產業。"],
      ["怎麼運作", "礦工用專門的 ASIC 礦機不停計算雜湊，最先算出答案的人取得記帳權，把一批交易打包成新區塊接到鏈上，並拿到新發行的比特幣當獎勵。一般人則透過交易所、現貨 ETF 或買持幣公司的股票參與。"],
      ["關鍵名詞", "算力（hash rate）：全網挖礦的計算能力。減半：約每四年挖礦獎勵減半一次。穩定幣：和美元一比一掛鉤的代幣，背後以現金與短期美債當準備。ETF：在股市就能買賣、追蹤比特幣價格的基金。"],
      ["景氣看什麼", "比特幣價格（幾乎決定所有相關股票）、ETF 資金流入流出、美國監管政策、電價與全網算力；部分礦工也把電力與機房轉租給 AI 資料中心。"],
      ["代表公司", "Coinbase、Robinhood 做交易，Circle 發行穩定幣 USDC，Strategy 大量持有比特幣，MARA、Riot、CleanSpark 做挖礦。台灣廠商則參與礦機晶片的代工與封測。"],
    ],
    trends: [
      "現貨 ETF 讓傳統投資人用證券帳戶就能持有比特幣，ETF 資金流向成為觀察幣價的新指標",
      "穩定幣逐步納入法規監管，發行商以短期美債作為準備資產，和傳統金融的連結越來越深",
      "挖礦獎勵每次減半都壓縮礦工收入，礦工改用更省電的礦機，並把電力與機房轉作 AI 運算",
      "越來越多上市公司把比特幣放進資產負債表，公司股價和幣價的連動更明顯",
    ],
    chain: [
      { tier: "上游", title: "算力與電力", items: [
        { name: "礦機晶片（ASIC）", desc: "專門計算 SHA-256 雜湊的晶片，決定每度電能挖多少", c: [["2330", "台積電", "礦機晶片代工"]] },
        { name: "挖礦與機房", desc: "取得便宜電力、架設大量礦機，靠新幣獎勵與手續費賺錢", c: [["MARA", "MARA Holdings", "比特幣挖礦"], ["RIOT", "Riot Platforms", "比特幣挖礦"], ["CLSK", "CleanSpark", "比特幣挖礦"]] },
      ] },
      { tier: "中游", title: "交易與金融基礎設施", items: [
        { name: "交易所與券商", desc: "撮合加密貨幣買賣，收取交易手續費與託管費", c: [["COIN", "Coinbase", "加密貨幣交易所與託管"], ["HOOD", "Robinhood", "券商與加密交易"]] },
        { name: "穩定幣", desc: "和美元一比一掛鉤的代幣，是加密市場裡的現金", c: [["CRCL", "Circle", "發行 USDC"], ["COIN", "Coinbase", "USDC 合作與分潤"]] },
      ] },
      { tier: "下游", title: "投資與持有", items: [
        { name: "比特幣現貨 ETF", desc: "在股市買賣、背後真的持有比特幣的基金", c: [["BLK", "貝萊德", "發行比特幣現貨 ETF"], ["COIN", "Coinbase", "多檔 ETF 的託管機構"]] },
        { name: "持幣公司", desc: "把比特幣當公司主要資產，股價跟著幣價放大波動", c: [["MSTR", "Strategy", "大量持有比特幣"]] },
      ] },
    ] },

  { id: "us-healthins", mk: "us", cat: "醫療", name: "醫療保險與給付體系", icon: "home",
    desc: "美國人看病多數靠雇主或政府資助的醫療保險；保險公司收保費、付醫院與藥品理賠，獲利取決於「收的保費」和「付出的醫療費」之間的差距。",
    flow: ["雇主與政府付保費", "保險公司", "醫院與醫師", "藥品福利管理", "理賠支付"],
    segs: [{ n: "醫療保險", c: [["UNH", "UnitedHealth", "最大醫療保險與 Optum"], ["ELV", "Elevance Health", "醫療保險"], ["CI", "Cigna", "保險與 Express Scripts"], ["CVS", "CVS Health", "Aetna 保險與藥局"], ["HUM", "Humana", "Medicare 優勢計畫"], ["CNC", "Centene", "Medicaid 保險"]] }],
    fig: { w: 400, h: 280, alt: "美國醫療保險：雇主與政府付保費給保險公司，保費大部分變成理賠付給醫院與藥局，藥品支出經過 PBM 談價；下方是一筆理賠的流程", items: [
      { t: "group", x: 8, y: 14, w: 100, h: 178, label: "誰付保費", c: "green" },
      { t: "icon", x: 16, y: 34, s: 22, k: "factory", c: "green" },
      { t: "text", x: 44, y: 46, s: 8.5, a: "start", label: "雇主團保" }, { t: "text", x: 44, y: 58, s: 7.5, a: "start", label: "上班族", muted: true },
      { t: "badge", x: 98, y: 40, n: 1, c: "green" },
      { t: "icon", x: 16, y: 84, s: 22, k: "bank", c: "green" },
      { t: "text", x: 44, y: 96, s: 8.5, a: "start", label: "政府計畫" }, { t: "text", x: 44, y: 108, s: 7.5, a: "start", label: "Medicare", muted: true },
      { t: "badge", x: 98, y: 90, n: 2, c: "green" },
      { t: "icon", x: 16, y: 134, s: 22, k: "person", c: "gray" },
      { t: "text", x: 44, y: 146, s: 8.5, a: "start", label: "會員" }, { t: "text", x: 44, y: 158, s: 7.5, a: "start", label: "自付額", muted: true },
      { t: "arrow", pts: [[108, 48], [132, 66]], c: "green" }, { t: "arrow", pts: [[108, 98], [132, 100]], c: "green" }, { t: "arrow", pts: [[108, 148], [132, 132]], c: "green" },
      // 保險公司
      { t: "rect", x: 134, y: 30, w: 104, h: 150, c: "blue", fill: 0.06, r: 6, sw: 1.4 },
      { t: "text", x: 186, y: 46, s: 9.5, b: true, label: "保險公司" },
      { t: "badge", x: 134, y: 30, n: 3, c: "blue" },
      { t: "rect", x: 150, y: 60, w: 32, h: 96, c: "gray", fill: 0.05 },
      { t: "rect", x: 150, y: 60, w: 32, h: 16, c: "gray", fill: 0.45 },
      { t: "rect", x: 150, y: 76, w: 32, h: 80, c: "green", fill: 0.4 },
      { t: "text", x: 188, y: 71, s: 7.5, a: "start", label: "費用＋利潤", muted: true },
      { t: "text", x: 188, y: 104, s: 8, a: "start", label: "理賠支出" }, { t: "text", x: 188, y: 116, s: 7.5, a: "start", label: "理賠率 MLR", muted: true },
      { t: "text", x: 166, y: 170, s: 7.5, label: "保費池", muted: true },
      { t: "icon", x: 200, y: 132, s: 18, k: "chart", c: "blue" }, { t: "text", x: 209, y: 164, s: 7.5, label: "精算訂價", muted: true },
      // 醫療服務
      { t: "group", x: 262, y: 14, w: 130, h: 178, label: "醫療服務", c: "red" },
      { t: "icon", x: 270, y: 32, s: 26, k: "hospital", c: "red" },
      { t: "text", x: 302, y: 46, s: 8.5, a: "start", label: "醫院醫師" }, { t: "text", x: 302, y: 58, s: 7.5, a: "start", label: "看診開刀", muted: true },
      { t: "badge", x: 378, y: 34, n: 5, c: "red" },
      { t: "box", x: 272, y: 84, w: 56, h: 34, label: "PBM", sub: "藥價談判", c: "purple" },
      { t: "badge", x: 272, y: 84, n: 4, c: "purple" },
      { t: "icon", x: 344, y: 84, s: 20, k: "pill", c: "pink" }, { t: "text", x: 354, y: 116, s: 8, label: "藥局", muted: true },
      { t: "icon", x: 344, y: 136, s: 20, k: "flask", c: "pink" }, { t: "text", x: 354, y: 168, s: 8, label: "藥廠", muted: true },
      { t: "badge", x: 380, y: 100, n: 6, c: "pink" },
      { t: "arrow", pts: [[328, 96], [342, 94]], c: "green" },
      { t: "arrow", pts: [[344, 148], [300, 148], [300, 120]], c: "pink", dash: true },
      { t: "arrow", pts: [[238, 52], [268, 46]], c: "green" }, { t: "arrow", pts: [[268, 60], [240, 66]], c: "blue", dash: true },
      { t: "arrow", pts: [[238, 100], [270, 100]], c: "green" },
      // 一筆理賠的流程
      { t: "box", x: 10, y: 206, w: 66, h: 28, label: "繳保費", s: 9, c: "green" }, { t: "arrow", pts: [[76, 220], [86, 220]], c: "gray" },
      { t: "box", x: 88, y: 206, w: 66, h: 28, label: "看病就醫", s: 9, c: "gray" }, { t: "arrow", pts: [[154, 220], [164, 220]], c: "gray" },
      { t: "box", x: 166, y: 206, w: 66, h: 28, label: "醫院請款", s: 9, c: "blue" }, { t: "arrow", pts: [[232, 220], [242, 220]], c: "gray" },
      { t: "box", x: 244, y: 206, w: 66, h: 28, label: "理賠審核", s: 9, c: "blue" }, { t: "arrow", pts: [[310, 220], [320, 220]], c: "gray" },
      { t: "box", x: 322, y: 206, w: 66, h: 28, label: "付款結案", s: 9, c: "green" },
      { t: "text", x: 200, y: 250, s: 8.5, label: "理賠率越高，保險公司越不賺", muted: true },
      { t: "legend", x: 14, y: 272, items: [["green", "錢：保費與理賠"], ["blue", "請款與申報", true], ["pink", "藥廠回扣", true]] },
    ] },
    how: [
      ["在做什麼", "美國沒有台灣這種全民健保，多數人靠公司團保或政府計畫（老人的 Medicare、低收入的 Medicaid）。民間保險公司收保費、替會員付醫療費，賺中間的差額。"],
      ["怎麼運作", "雇主或政府每月付保費給保險公司；會員看病時，醫院和醫師向保險公司請款，保險公司審核後付款。藥品則經過藥品福利管理公司（PBM）向藥廠談價與支付。保險公司事先預估明年醫療費用來訂保費。"],
      ["關鍵名詞", "理賠率（MLR）：理賠占保費的比例，越高代表越不賺。Medicare 優勢計畫：民間公司承接的老人醫保。PBM：替保險公司管理處方藥支出的中間商。"],
      ["景氣看什麼", "醫療使用量是否高於預期、政府給付費率調整、藥價與減重藥等新藥的支出、監管與政策變化；這個產業和電子景氣的相關性低。"],
      ["代表公司", "UnitedHealth、Elevance、Cigna、CVS（Aetna）、Humana、Centene。台灣是單一健保制度，沒有對應的民間醫保產業，可當作理解美國醫療股的背景知識。"],
    ],
    trends: [
      "保險、PBM、診所與藥局整合在同一集團內（垂直整合），但也因此面臨更多監管與反壟斷檢視",
      "政府計畫的給付費率與審核規則變動，直接左右 Medicare 優勢計畫業者的獲利",
      "減重藥等高價新藥普及，處方藥支出上升，PBM 的談價與藥價透明度成為焦點",
      "用 AI 與數據分析做理賠審核、風險評估與慢性病管理，以壓低醫療成本",
    ],
    chain: [
      { tier: "上游", title: "保費來源", items: [
        { name: "雇主團體保險", desc: "公司替員工投保，是商業醫療保險的最大客群", c: [["UNH", "UnitedHealth", "商業團保"], ["ELV", "Elevance Health", "商業團保"], ["CI", "Cigna", "商業團保"]] },
        { name: "政府醫保計畫", desc: "政府出錢、民間保險公司代為承接的老人與低收入醫保", c: [["HUM", "Humana", "Medicare 優勢計畫"], ["CNC", "Centene", "Medicaid 代管"], ["ELV", "Elevance Health", "Medicaid 與 Medicare"]] },
      ] },
      { tier: "中游", title: "保險與藥品管理", items: [
        { name: "承保與理賠", desc: "精算訂保費、審核與支付醫療理賠", c: [["UNH", "UnitedHealth", "最大醫療保險"], ["ELV", "Elevance Health", "醫療保險"], ["CVS", "CVS Health", "旗下 Aetna"], ["CI", "Cigna", "醫療保險"], ["HUM", "Humana", "醫療保險"]] },
        { name: "藥品福利管理（PBM）", desc: "替保險公司向藥廠談價、管理處方藥支出", c: [["CI", "Cigna", "Express Scripts"], ["CVS", "CVS Health", "CVS Caremark"], ["UNH", "UnitedHealth", "Optum Rx"]] },
      ] },
      { tier: "下游", title: "醫療服務與藥品", items: [
        { name: "醫院與醫師", desc: "提供看診、手術與住院，向保險公司請款", c: [["HCA", "HCA Healthcare", "醫院連鎖"], ["UNH", "UnitedHealth", "Optum Health 診所網路"]] },
        { name: "藥局與藥廠", desc: "開藥、配藥與新藥研發，是醫療支出成長最快的一塊", c: [["CVS", "CVS Health", "連鎖藥局"], ["LLY", "禮來", "減重藥等新藥"]] },
      ] },
    ] },

  { id: "us-housing", mk: "us", cat: "房地產", name: "美國房市", icon: "home",
    desc: "美國房市受房貸利率影響最大：利率決定買不買得起，進而影響新屋開工、成屋買賣，並帶動建材、裝修、房貸與搬遷等一長串下游消費。",
    flow: ["房貸利率", "購屋負擔能力", "新屋開工", "成屋買賣", "建材與裝修需求"],
    segs: [{ n: "建商", c: [["DHI", "D.R. Horton", "最大建商之一"], ["LEN", "Lennar", "建商"], ["PHM", "PulteGroup", "建商"], ["NVR", "NVR", "建商"]] },
      { n: "裝修與房貸", c: [["HD", "Home Depot", "建材與居家修繕零售"], ["LOW", "Lowe's", "建材與居家修繕零售"], ["RKT", "Rocket Companies", "房貸"], ["Z", "Zillow", "房產平台"]] }],
    fig: { w: 400, h: 280, alt: "美國房市：房貸利率決定買不買得起；建商用建材蓋新屋，成屋由仲介與平台撮合；買房後帶動修繕與家電家具消費", items: [
      { t: "group", x: 8, y: 14, w: 118, h: 122, label: "資金端", c: "blue" },
      { t: "path", d: "M18 76A26 26 0 0 1 31 53.5", c: "green", w: 4 },
      { t: "path", d: "M31 53.5A26 26 0 0 1 57 53.5", c: "yellow", w: 4 },
      { t: "path", d: "M57 53.5A26 26 0 0 1 70 76", c: "red", w: 4 },
      { t: "path", d: "M44 76L59 57", c: "red", w: 2 }, { t: "circle", x: 44, y: 76, r: 3, c: "gray", fill: 1 },
      { t: "text", x: 44, y: 92, s: 8, b: true, label: "房貸利率" },
      { t: "badge", x: 18, y: 36, n: 1, c: "blue" },
      { t: "icon", x: 86, y: 44, s: 24, k: "bank", c: "blue" }, { t: "text", x: 98, y: 82, s: 7.5, label: "銀行放款", muted: true },
      { t: "text", x: 66, y: 112, s: 8, label: "利率↑ 月付↑", muted: true }, { t: "text", x: 66, y: 125, s: 7.5, label: "跟著 10 年債走", muted: true },
      { t: "arrow", pts: [[126, 104], [146, 112]], c: "blue" },
      // 房子剖面
      { t: "path", d: "M144 90L212 40L280 90Z", c: "orange", fill: 0.2 },
      { t: "path", d: "M162 78h100M178 66h68M196 54h32", c: "orange", w: 0.8 },
      { t: "badge", x: 212, y: 30, n: 3, c: "orange" },
      { t: "rect", x: 150, y: 90, w: 124, h: 100, c: "gray", fill: 0.06 },
      { t: "rect", x: 152, y: 92, w: 8, h: 96, c: "pink", fill: 0.35, stroke: false }, { t: "rect", x: 264, y: 92, w: 8, h: 96, c: "pink", fill: 0.35, stroke: false },
      { t: "path", d: "M184 90v50M240 90v50", c: "gray", w: 0.8, dash: true },
      { t: "path", d: "M150 140h124", c: "gray", w: 1.4 },
      { t: "rect", x: 196, y: 102, w: 18, h: 18, c: "cyan", fill: 0.25 }, { t: "rect", x: 222, y: 102, w: 18, h: 18, c: "cyan", fill: 0.25 },
      { t: "path", d: "M205 102v18M196 111h18M231 102v18M222 111h18", c: "cyan", w: 0.8 },
      { t: "badge", x: 172, y: 112, n: 2, c: "pink" }, { t: "text", x: 172, y: 130, s: 7.5, label: "隔熱", muted: true },
      { t: "rect", x: 196, y: 156, w: 18, h: 34, c: "orange", fill: 0.3 },
      { t: "rect", x: 238, y: 158, w: 18, h: 32, c: "cyan", fill: 0.2 }, { t: "path", d: "M238 170h18", c: "cyan", w: 0.8 },
      { t: "badge", x: 247, y: 149, n: 6, c: "cyan" },
      { t: "rect", x: 144, y: 190, w: 136, h: 8, c: "gray", fill: 0.5 },
      { t: "path", d: "M284 190L292 120M298 190L306 120M286 176h13M288 160h13M290 144h13M292 130h13", c: "yellow", w: 1.3 },
      { t: "badge", x: 302, y: 110, n: 5, c: "yellow" },
      // 買賣
      { t: "group", x: 318, y: 14, w: 74, h: 182, label: "買賣", c: "green" },
      { t: "box", x: 326, y: 32, w: 58, h: 32, label: "新屋", sub: "建商推案", c: "orange" },
      { t: "box", x: 326, y: 74, w: 58, h: 32, label: "成屋", sub: "中古屋", c: "green" },
      { t: "badge", x: 326, y: 74, n: 4, c: "green" },
      { t: "icon", x: 343, y: 116, s: 24, k: "person", c: "gray", label: "買方" },
      { t: "text", x: 355, y: 170, s: 8, label: "庫存月數", muted: true }, { t: "text", x: 355, y: 182, s: 7.5, label: "看供需", muted: true },
      { t: "arrow", pts: [[262, 76], [322, 48]], c: "orange" },
      // 時間軸
      { t: "box", x: 10, y: 212, w: 66, h: 28, label: "營建許可", s: 9, c: "orange" }, { t: "arrow", pts: [[76, 226], [86, 226]], c: "gray" },
      { t: "box", x: 88, y: 212, w: 66, h: 28, label: "新屋開工", s: 9, c: "orange" }, { t: "arrow", pts: [[154, 226], [164, 226]], c: "gray" },
      { t: "box", x: 166, y: 212, w: 66, h: 28, label: "完工交屋", s: 9, c: "green" }, { t: "arrow", pts: [[232, 226], [242, 226]], c: "gray" },
      { t: "box", x: 244, y: 212, w: 66, h: 28, label: "搬家裝修", s: 9, c: "yellow" }, { t: "arrow", pts: [[310, 226], [320, 226]], c: "gray" },
      { t: "box", x: 322, y: 212, w: 66, h: 28, label: "家電家具", s: 9, c: "cyan" },
      { t: "legend", x: 14, y: 268, items: [["blue", "資金與利率"], ["orange", "建造"], ["yellow", "修繕"], ["cyan", "家電"]] },
    ] },
    how: [
      ["在做什麼", "美國人買房幾乎都靠 30 年期房貸，房市是美國經濟很重要的引擎：一間房子成交，會帶動建材、裝潢、家具家電、房貸與搬家等一連串消費。"],
      ["怎麼運作", "房貸利率大致跟著 10 年期公債殖利率走。利率高時月付金變重，很多人買不起或不想賣掉手上低利房貸的舊房，成屋交易變少；建商則用補貼利率等方式推新屋，開工量隨需求調整。"],
      ["關鍵名詞", "新屋開工：建商開始動工的數量，是景氣領先指標。成屋銷售：中古屋成交量。庫存月數：以目前速度要幾個月才能賣完待售房屋。鎖定效應：屋主不想放棄低利房貸。"],
      ["景氣看什麼", "房貸利率與聯準會政策、就業與薪資、新屋開工與營建許可、成屋庫存與房價；房市回溫時，建材與居家修繕零售通常跟著受惠。"],
      ["代表公司", "建商有 D.R. Horton、Lennar、PulteGroup、NVR；居家修繕零售有 Home Depot、Lowe's；房貸與平台有 Rocket、Zillow。台灣的五金、手工具、家具與家電出口廠也受美國房市影響。"],
    ],
    trends: [
      "屋主捨不得放棄過去的低利房貸，成屋供給偏少，新屋在整體成交中的比重提高",
      "建商用補貼房貸利率、蓋較小坪數的房子來維持買方的負擔能力",
      "屋齡老化讓修繕與翻新需求相對穩定，專業包商客群成為修繕零售的成長重點",
      "買房、貸款、仲介流程持續數位化，房產平台與房貸業者走向一站式服務",
    ],
    chain: [
      { tier: "上游", title: "資金與建材", items: [
        { name: "房貸與放款", desc: "提供購屋貸款，利率高低決定有多少人買得起", c: [["RKT", "Rocket Companies", "房貸"]] },
        { name: "建材與構件", desc: "木料、屋架、隔熱與屋頂材料", c: [["BLDR", "Builders FirstSource", "木料與預製構件"], ["OC", "Owens Corning", "隔熱與屋頂材料"]] },
      ] },
      { tier: "中游", title: "蓋房與買賣", items: [
        { name: "建商", desc: "買地、蓋新屋並銷售，常提供房貸利率補貼", c: [["DHI", "D.R. Horton", "建商"], ["LEN", "Lennar", "建商"], ["PHM", "PulteGroup", "建商"], ["NVR", "NVR", "建商"]] },
        { name: "成屋買賣平台", desc: "刊登房源、仲介撮合中古屋交易", c: [["Z", "Zillow", "房產平台"], ["COMP", "Compass", "房屋仲介"]] },
      ] },
      { tier: "下游", title: "入住後的消費", items: [
        { name: "居家修繕零售", desc: "賣建材、工具與裝修用品給屋主和包商", c: [["HD", "Home Depot", "居家修繕零售"], ["LOW", "Lowe's", "居家修繕零售"]] },
        { name: "家電與家具", desc: "搬新家帶動冰箱、洗衣機等大型家電汰換", c: [["WHR", "Whirlpool", "大型家電"]] },
      ] },
    ] },

  { id: "us-minerals", mk: "us", cat: "原物料", name: "關鍵礦產與金屬", icon: "factory",
    desc: "銅、鋰、鎳、稀土、鎵、鍺等金屬是電動車、電網、AI 資料中心與國防的基礎材料；精煉產能高度集中，因此成為各國補貼與出口管制的焦點。",
    flow: ["開採礦石", "選礦", "精煉提純", "金屬材料", "電池、馬達、電網"],
    segs: [{ n: "銅與鋁", c: [["FCX", "Freeport-McMoRan", "銅礦"], ["SCCO", "Southern Copper", "銅礦"], ["AA", "Alcoa", "鋁"]] },
      { n: "鋰與稀土", c: [["ALB", "Albemarle", "鋰"], ["MP", "MP Materials", "稀土礦與磁材"]] }],
    fig: { w: 400, h: 280, alt: "關鍵礦產：銅礦經破碎、浮選、冶煉、電解精煉成銅陰極；鹽湖鹵水日曬濃縮成鋰鹽；稀土礦經上百段萃取分離做成永久磁鐵，最後用在電動車、電網與資料中心", items: [
      { t: "path", d: "M8 40H22L28 50H36L42 60H50L56 70H66L72 60H80L86 50H94L100 40H112V96H8Z", c: "gray", fill: 0.18 },
      { t: "circle", x: 36, y: 80, r: 2.5, c: "orange", fill: 0.8 }, { t: "circle", x: 62, y: 86, r: 2.5, c: "orange", fill: 0.8 }, { t: "circle", x: 84, y: 76, r: 2.5, c: "orange", fill: 0.8 },
      { t: "icon", x: 52, y: 48, s: 16, k: "truck", c: "yellow" },
      { t: "badge", x: 14, y: 28, n: 1, c: "orange" }, { t: "text", x: 62, y: 31, s: 8, label: "露天銅礦", muted: true },
      { t: "arrow", pts: [[112, 56], [126, 56]], c: "orange" },
      { t: "icon", x: 128, y: 44, s: 22, k: "gear", c: "gray", label: "破碎" },
      { t: "arrow", pts: [[150, 56], [162, 56]], c: "orange" },
      { t: "cyl", x: 164, y: 34, w: 32, h: 46, c: "cyan", label: "浮選" },
      { t: "circle", x: 174, y: 60, r: 2, c: "cyan", fill: 0.6 }, { t: "circle", x: 185, y: 52, r: 2.5, c: "cyan", fill: 0.6 }, { t: "circle", x: 180, y: 68, r: 1.8, c: "cyan", fill: 0.6 },
      { t: "arrow", pts: [[196, 56], [208, 56]], c: "orange" },
      { t: "rect", x: 210, y: 36, w: 34, h: 44, c: "red", fill: 0.15 }, { t: "icon", x: 217, y: 46, s: 20, k: "fire", c: "red" },
      { t: "text", x: 227, y: 91, s: 8, label: "冶煉", muted: true },
      { t: "arrow", pts: [[244, 56], [256, 56]], c: "orange" },
      { t: "rect", x: 258, y: 40, w: 62, h: 40, c: "cyan", fill: 0.12 },
      { t: "path", d: "M274 36v38M288 36v38M302 36v38", c: "gray", w: 2.5 },
      { t: "path", d: "M267 34v40M281 34v40M295 34v40M309 34v40", c: "orange", w: 3 },
      { t: "text", x: 289, y: 91, s: 8, label: "電解精煉", muted: true },
      { t: "badge", x: 252, y: 28, n: 4, c: "orange" },
      { t: "arrow", pts: [[320, 56], [332, 56]], c: "orange" },
      { t: "stack", x: 336, y: 40, w: 52, h: 34, n: 5, c: "orange", label: "銅陰極" },
      // 鋰
      { t: "icon", x: 52, y: 104, s: 18, k: "sun", c: "yellow" },
      { t: "rect", x: 12, y: 128, w: 30, h: 18, c: "cyan", fill: 0.2 }, { t: "rect", x: 46, y: 128, w: 30, h: 18, c: "cyan", fill: 0.4 }, { t: "rect", x: 80, y: 128, w: 30, h: 18, c: "green", fill: 0.45 },
      { t: "text", x: 61, y: 160, s: 8, label: "鹽湖鹵水日曬濃縮", muted: true },
      { t: "badge", x: 14, y: 116, n: 2, c: "cyan" },
      { t: "arrow", pts: [[110, 137], [124, 137]], c: "cyan" },
      { t: "cyl", x: 126, y: 118, w: 30, h: 38, c: "cyan", label: "鋰鹽" },
      // 稀土
      { t: "box", x: 182, y: 120, w: 48, h: 30, label: "稀土礦", s: 9, c: "purple" },
      { t: "badge", x: 182, y: 118, n: 3, c: "purple" },
      { t: "arrow", pts: [[230, 135], [242, 135]], c: "purple" },
      { t: "rect", x: 244, y: 124, w: 10, h: 22, c: "purple", fill: 0.15 }, { t: "rect", x: 256, y: 124, w: 10, h: 22, c: "purple", fill: 0.3 }, { t: "rect", x: 268, y: 124, w: 10, h: 22, c: "purple", fill: 0.15 },
      { t: "rect", x: 280, y: 124, w: 10, h: 22, c: "purple", fill: 0.3 }, { t: "rect", x: 292, y: 124, w: 10, h: 22, c: "purple", fill: 0.15 }, { t: "rect", x: 304, y: 124, w: 10, h: 22, c: "purple", fill: 0.3 },
      { t: "text", x: 279, y: 160, s: 8, label: "上百段萃取分離", muted: true },
      { t: "badge", x: 318, y: 114, n: 5, c: "purple" },
      { t: "arrow", pts: [[316, 135], [330, 135]], c: "purple" },
      { t: "rect", x: 332, y: 122, w: 26, h: 26, c: "red", fill: 0.35 }, { t: "text", x: 345, y: 139, s: 10, b: true, label: "N" },
      { t: "rect", x: 358, y: 122, w: 26, h: 26, c: "blue", fill: 0.35 }, { t: "text", x: 371, y: 139, s: 10, b: true, label: "S" },
      { t: "text", x: 358, y: 160, s: 8, label: "永久磁鐵", muted: true },
      // 應用
      { t: "group", x: 8, y: 180, w: 384, h: 68, label: "用在哪裡", c: "gray" },
      { t: "icon", x: 34, y: 198, s: 26, k: "car", c: "green", label: "電動車" }, { t: "badge", x: 24, y: 204, n: 6, c: "green" },
      { t: "icon", x: 112, y: 196, s: 28, k: "tower", c: "yellow", label: "電網" }, { t: "badge", x: 104, y: 204, n: 7, c: "yellow" },
      { t: "rack", x: 182, y: 196, w: 30, h: 32, n: 4, c: "blue", label: "資料中心" }, { t: "badge", x: 222, y: 204, n: 7, c: "yellow" },
      { t: "icon", x: 258, y: 200, s: 26, k: "globe", c: "red" },
      { t: "text", x: 336, y: 214, s: 8, b: true, label: "精煉產能集中" }, { t: "text", x: 336, y: 228, s: 7.5, label: "出口管制風險", muted: true },
      { t: "legend", x: 14, y: 270, items: [["orange", "銅"], ["cyan", "鋰"], ["purple", "稀土"]] },
    ] },
    how: [
      ["在做什麼", "電動車電池要鋰、鎳、鈷，馬達要稀土磁鐵，晶片與光通訊要鎵、鍺，電網和資料中心要大量的銅。這些「關鍵礦產」決定了科技產業能不能穩定生產。"],
      ["怎麼運作", "銅礦開採後先破碎、浮選提高濃度，再冶煉與電解精煉成高純度銅；鋰多半來自鹽湖鹵水日曬濃縮或硬岩礦；稀土要經過上百段化學萃取才能分離出單一元素。精煉與分離產能高度集中在中國，是供應鏈最大的風險點。"],
      ["關鍵名詞", "精煉：把礦石變成高純度金屬。稀土：一組 17 種元素，做強力永久磁鐵。出口管制：限制關鍵材料或技術出口。長約與保證價格：政府或大客戶確保供應的方式。"],
      ["景氣看什麼", "金屬價格與庫存、電動車與電網投資、中國的出口管制動向、美國政府的補貼與入股、新礦與精煉廠的建置進度；價格波動通常比一般產業股大。"],
      ["代表公司", "Freeport-McMoRan、Southern Copper 是大型銅礦商，Alcoa 做鋁，Albemarle 是鋰業龍頭，MP Materials 經營美國稀土礦與磁材。台灣幾乎不產礦，電子與電池產業是這些材料的使用者。"],
    ],
    trends: [
      "各國把精煉與分離產能搬回本土或友好國家，政府以補貼、入股與保證收購價支持",
      "電網升級與 AI 資料中心大量用銅，銅的需求從傳統營建延伸到電力與科技",
      "稀土供應鏈往下游延伸，從採礦一路做到分離、金屬與永久磁鐵",
      "鋰提取技術朝直接提鋰發展，縮短鹽湖日曬時間並減少用水",
    ],
    chain: [
      { tier: "上游", title: "開採", items: [
        { name: "銅礦開採", desc: "大型露天與地下銅礦，產出銅精礦", c: [["FCX", "Freeport-McMoRan", "銅礦"], ["SCCO", "Southern Copper", "銅礦"]] },
        { name: "鋰資源", desc: "鹽湖鹵水與硬岩鋰礦，做成碳酸鋰或氫氧化鋰", c: [["ALB", "Albemarle", "鋰"], ["SQM", "SQM", "智利鹽湖鋰"]] },
        { name: "稀土礦", desc: "開採含稀土的礦石，做成混合稀土精礦", c: [["MP", "MP Materials", "美國稀土礦"]] },
      ] },
      { tier: "中游", title: "冶煉與精煉", items: [
        { name: "冶煉與電解精煉", desc: "把精礦冶煉、電解成高純度銅或鋁", c: [["FCX", "Freeport-McMoRan", "銅冶煉與精煉"], ["SCCO", "Southern Copper", "銅冶煉與精煉"], ["AA", "Alcoa", "氧化鋁與鋁冶煉"]] },
        { name: "稀土分離與磁材", desc: "化學萃取分離出單一稀土，再做成永久磁鐵", c: [["MP", "MP Materials", "稀土分離與磁材"]] },
      ] },
      { tier: "下游", title: "應用", items: [
        { name: "電動車與電池", desc: "電池用鋰、馬達用稀土磁鐵、車上大量銅線", c: [["TSLA", "特斯拉", "電動車"]] },
        { name: "電網與資料中心", desc: "變壓器、電纜與配電設備大量用銅", c: [["ETN", "伊頓", "配電設備"], ["GEV", "GE Vernova", "電網設備"]] },
      ] },
    ] },

  { id: "us-oilgas", mk: "us", cat: "能源", name: "能源油氣", icon: "bolt",
    desc: "石油與天然氣從上游開採、中游管線運輸，到下游煉油與發電；美國頁岩油氣讓它成為最大產油國之一，天然氣也是 AI 資料中心的重要電力來源。",
    flow: ["探勘開採", "管線運輸", "煉油", "汽柴油與塑化", "天然氣發電與出口"],
    segs: [{ n: "整合與上游", c: [["XOM", "ExxonMobil", "整合型石油公司"], ["CVX", "Chevron", "整合型石油公司"], ["COP", "ConocoPhillips", "上游開採"], ["EOG", "EOG Resources", "頁岩油"]] },
      { n: "天然氣與中游", c: [["EQT", "EQT", "天然氣生產"], ["KMI", "Kinder Morgan", "天然氣管線"], ["LNG", "Cheniere Energy", "液化天然氣出口"], ["SLB", "SLB", "油田服務"]] }],
    fig: { w: 400, h: 280, alt: "油氣：鑽井平台垂直往下再水平鑽進頁岩層並壓裂；原油經管線送到煉油廠分餾成汽油柴油，天然氣經管線送去液化出口或燃氣電廠供電給資料中心", items: [
      { t: "rect", x: 8, y: 100, w: 196, h: 22, c: "gray", fill: 0.08, stroke: false },
      { t: "rect", x: 8, y: 122, w: 196, h: 26, c: "yellow", fill: 0.1, stroke: false },
      { t: "rect", x: 8, y: 148, w: 196, h: 30, c: "orange", fill: 0.22, stroke: false },
      { t: "rect", x: 8, y: 178, w: 196, h: 10, c: "gray", fill: 0.12, stroke: false },
      { t: "path", d: "M8 96H392", c: "gray", w: 1 },
      { t: "text", x: 48, y: 40, s: 8, label: "鑽井平台", muted: true },
      { t: "icon", x: 26, y: 50, s: 44, k: "tower", c: "gray" },
      { t: "badge", x: 16, y: 56, n: 1, c: "gray" },
      { t: "rect", x: 44, y: 90, w: 8, h: 6, c: "gray", fill: 0.6 },
      { t: "path", d: "M48 96V150Q48 162 60 162H196", c: "gray", w: 2.4 },
      { t: "path", d: "M80 162l-4-9M80 162l4 9M110 162l-4-9M110 162l4 9M140 162l-4-9M140 162l4 9M170 162l-4-9M170 162l4 9", c: "orange", w: 1.2 },
      { t: "circle", x: 95, y: 171, r: 2, c: "orange", fill: 0.9 }, { t: "circle", x: 155, y: 154, r: 2, c: "orange", fill: 0.9 }, { t: "circle", x: 125, y: 172, r: 2, c: "cyan", fill: 0.9 },
      { t: "text", x: 124, y: 139, s: 8, label: "水平鑽井＋壓裂", muted: true },
      { t: "badge", x: 34, y: 134, n: 2, c: "orange" },
      { t: "text", x: 16, y: 199, s: 8, a: "start", label: "頁岩層（油氣在岩縫裡）", muted: true },
      // 管線
      { t: "path", d: "M52 92H212", c: "orange", w: 3 },
      { t: "path", d: "M52 104H316V86", c: "cyan", w: 2.4 },
      { t: "circle", x: 120, y: 92, r: 6, c: "cyan", fill: 0.4 },
      { t: "badge", x: 120, y: 78, n: 3, c: "cyan" }, { t: "text", x: 96, y: 72, s: 8, label: "管線", muted: true },
      { t: "cyl", x: 150, y: 66, w: 24, h: 24, c: "orange" },
      // 煉油
      { t: "rect", x: 212, y: 22, w: 22, h: 74, c: "red", fill: 0.15, r: 8 },
      { t: "path", d: "M214 36h18M214 48h18M214 60h18M214 72h18M214 84h18", c: "red", w: 0.8 },
      { t: "badge", x: 204, y: 22, n: 5, c: "red" },
      { t: "arrow", pts: [[234, 36], [250, 36]], c: "yellow" }, { t: "text", x: 254, y: 39, s: 8, a: "start", label: "汽油" },
      { t: "arrow", pts: [[234, 54], [250, 54]], c: "yellow" }, { t: "text", x: 254, y: 57, s: 8, a: "start", label: "柴油" },
      { t: "arrow", pts: [[234, 72], [250, 72]], c: "yellow" }, { t: "text", x: 254, y: 75, s: 8, a: "start", label: "塑化原料" },
      // LNG
      { t: "circle", x: 316, y: 70, r: 16, c: "cyan", fill: 0.2 }, { t: "text", x: 316, y: 73, s: 8, label: "液化" },
      { t: "badge", x: 302, y: 50, n: 4, c: "cyan" },
      { t: "arrow", pts: [[332, 70], [348, 70]], c: "cyan" },
      { t: "icon", x: 350, y: 52, s: 34, k: "ship", c: "blue" },
      { t: "text", x: 368, y: 44, s: 8, label: "LNG 出口", muted: true },
      // 發電
      { t: "path", d: "M244 104V126", c: "cyan", w: 2.4 },
      { t: "icon", x: 230, y: 128, s: 30, k: "factory", c: "cyan" }, { t: "text", x: 245, y: 172, s: 8, label: "燃氣電廠", muted: true },
      { t: "badge", x: 224, y: 124, n: 7, c: "cyan" },
      { t: "arrow", pts: [[262, 143], [292, 143]], c: "yellow" }, { t: "icon", x: 268, y: 124, s: 14, k: "bolt", c: "yellow" },
      { t: "rack", x: 296, y: 118, w: 36, h: 50, n: 5, c: "blue" }, { t: "text", x: 314, y: 180, s: 8, label: "AI 資料中心", muted: true },
      // 整合型
      { t: "path", d: "M10 206V214H390V206", c: "purple", w: 1.2 },
      { t: "badge", x: 200, y: 214, n: 6, c: "purple" },
      { t: "text", x: 200, y: 234, s: 8.5, b: true, label: "整合型大廠：上中下游一手包" },
      { t: "text", x: 200, y: 248, s: 8, label: "油價看 OPEC+ 與美國產量", muted: true },
      { t: "legend", x: 14, y: 270, items: [["orange", "原油"], ["cyan", "天然氣"], ["yellow", "油品與電力"]] },
    ] },
    how: [
      ["在做什麼", "把地底的石油和天然氣開採出來，運送、加工成汽油、柴油、航空燃油和塑化原料，或拿天然氣去發電、液化出口。這是全球最大的能源來源之一。"],
      ["怎麼運作", "上游公司鑽井開採（美國主要是頁岩，先垂直鑽下去再水平鑽進岩層，用高壓水壓裂讓油氣流出），中游用管線與儲槽運送，下游煉油廠把原油分餾成各種油品。天然氣則透過管線送到發電廠，或冷卻成液化天然氣（LNG）用船出口。"],
      ["關鍵名詞", "上中下游：開採、運輸、加工。頁岩油氣：從頁岩層開採的油氣。OPEC+：主要產油國聯盟，會調整產量影響油價。LNG：液化天然氣，方便長途海運。煉油價差：油品售價減原油成本。"],
      ["景氣看什麼", "國際油價與天然氣價、OPEC+ 產量政策、美國鑽井數與庫存、煉油價差；AI 資料中心用電增加，讓天然氣發電需求受到關注。"],
      ["代表公司", "ExxonMobil、Chevron 是整合型大廠，ConocoPhillips、EOG 偏上游，EQT 產天然氣，Kinder Morgan 經營管線，Cheniere 出口 LNG，SLB 提供油田服務。台灣的台塑化、中油與 LNG 進口都和國際油氣價格相關。"],
    ],
    trends: [
      "頁岩業者整併成大型公司，重視現金回饋與資本紀律，不再一味追求增產",
      "美國 LNG 出口設施持續擴建，天然氣從內需商品變成全球貿易商品",
      "AI 資料中心用電需求帶動燃氣發電，天然氣被視為銜接再生能源的穩定電力",
      "油田服務導入自動化鑽井與數據分析，以更少的井數維持產量",
    ],
    chain: [
      { tier: "上游", title: "探勘與開採", items: [
        { name: "油田服務", desc: "鑽井、壓裂、完井與設備，替油公司把井打出來", c: [["SLB", "SLB", "油田服務"], ["HAL", "Halliburton", "壓裂與完井"], ["BKR", "Baker Hughes", "油田設備與服務"]] },
        { name: "油氣開採", desc: "擁有礦區、鑽井生產原油與天然氣", c: [["COP", "ConocoPhillips", "上游開採"], ["EOG", "EOG Resources", "頁岩油"], ["EQT", "EQT", "天然氣生產"]] },
      ] },
      { tier: "中游", title: "運輸與出口", items: [
        { name: "管線與儲運", desc: "用管線、儲槽把油氣送到煉油廠、電廠與港口", c: [["KMI", "Kinder Morgan", "天然氣管線"], ["WMB", "Williams", "天然氣管線"], ["ET", "Energy Transfer", "油氣管線"]] },
        { name: "LNG 液化出口", desc: "把天然氣冷卻成液體，用船出口到海外", c: [["LNG", "Cheniere Energy", "液化天然氣出口"]] },
      ] },
      { tier: "下游", title: "加工與使用", items: [
        { name: "煉油", desc: "把原油分餾成汽油、柴油、航油與塑化原料", c: [["VLO", "Valero", "煉油"], ["MPC", "Marathon Petroleum", "煉油"], ["PSX", "Phillips 66", "煉油"]] },
        { name: "整合型石油公司", desc: "從開採、運輸到煉油化工一手包辦", c: [["XOM", "ExxonMobil", "整合型石油公司"], ["CVX", "Chevron", "整合型石油公司"]] },
        { name: "天然氣發電", desc: "燃氣電廠發電，供應電網與資料中心", c: [["VST", "Vistra", "燃氣發電"]] },
      ] },
    ] },

  { id: "us-machinery", mk: "us", cat: "工業", name: "重工機械", icon: "factory",
    desc: "挖土機、礦用卡車、農機、引擎與發電機組等大型機械，服務基建、礦業、農業與能源；景氣循環明顯，但龐大的售後零件與服務提供穩定收入。",
    flow: ["基建與礦業需求", "機械廠製造", "經銷商銷售", "設備使用", "售後零件與服務"],
    segs: [{ n: "機械製造", c: [["CAT", "Caterpillar", "營建與礦業機械、發電機組"], ["DE", "Deere", "農業機械"], ["CMI", "Cummins", "引擎與發電機"], ["PCAR", "PACCAR", "重型卡車"]] },
      { n: "能源設備與租賃", c: [["GEV", "GE Vernova", "燃氣渦輪與電網設備"], ["URI", "United Rentals", "設備租賃"]] }],
    fig: { w: 400, h: 280, alt: "重工機械：挖土機剖面（引擎帶動液壓泵，液壓缸推動動臂與鏟斗）、農機、重型卡車、發電機組供電給資料中心；下方是經銷、租賃、使用到售後零件的循環", items: [
      { t: "rect", x: 18, y: 146, w: 124, h: 24, r: 12, c: "gray", fill: 0.2 },
      { t: "circle", x: 32, y: 158, r: 7, c: "gray", fill: 0.3 }, { t: "circle", x: 56, y: 158, r: 7, c: "gray", fill: 0.3 }, { t: "circle", x: 80, y: 158, r: 7, c: "gray", fill: 0.3 },
      { t: "circle", x: 104, y: 158, r: 7, c: "gray", fill: 0.3 }, { t: "circle", x: 128, y: 158, r: 7, c: "gray", fill: 0.3 },
      { t: "rect", x: 26, y: 104, w: 104, h: 40, r: 4, c: "yellow", fill: 0.22 },
      { t: "rect", x: 32, y: 112, w: 42, h: 26, c: "red", fill: 0.2 }, { t: "text", x: 53, y: 129, s: 8, label: "引擎" },
      { t: "badge", x: 24, y: 98, n: 1, c: "red" },
      { t: "circle", x: 84, y: 125, r: 6, c: "purple", fill: 0.35 },
      { t: "path", d: "M90 125H138", c: "purple", w: 1.2, dash: true },
      { t: "rect", x: 96, y: 62, w: 34, h: 42, c: "yellow", fill: 0.15 }, { t: "rect", x: 102, y: 68, w: 22, h: 18, c: "cyan", fill: 0.25 },
      { t: "path", d: "M130 108L164 46L192 94", c: "orange", w: 6 },
      { t: "path", d: "M186 94l16 2l-2 16l-16-6z", c: "orange", fill: 0.4 },
      { t: "path", d: "M138 125L152 92", c: "purple", w: 5 }, { t: "path", d: "M152 92L157 80", c: "gray", w: 2 },
      { t: "badge", x: 166, y: 112, n: 2, c: "purple" }, { t: "text", x: 168, y: 130, s: 7.5, label: "液壓缸", muted: true },
      { t: "badge", x: 96, y: 52, n: 3, c: "orange" },
      { t: "text", x: 80, y: 186, s: 8, label: "挖土機剖面", muted: true },
      // 農機
      { t: "rect", x: 220, y: 30, w: 24, h: 22, c: "green", fill: 0.1 }, { t: "rect", x: 244, y: 50, w: 44, h: 20, c: "green", fill: 0.3 },
      { t: "circle", x: 234, y: 72, r: 18, c: "green", fill: 0.2 }, { t: "circle", x: 234, y: 72, r: 5, c: "green", fill: 0.6 },
      { t: "circle", x: 280, y: 80, r: 10, c: "green", fill: 0.2 },
      { t: "text", x: 256, y: 104, s: 8, label: "農機", muted: true },
      { t: "badge", x: 212, y: 24, n: 4, c: "green" },
      // 卡車
      { t: "icon", x: 314, y: 40, s: 40, k: "truck", c: "blue" }, { t: "text", x: 334, y: 96, s: 8, label: "重型卡車", muted: true },
      { t: "badge", x: 380, y: 40, n: 5, c: "blue" },
      // 發電機組
      { t: "rect", x: 210, y: 124, w: 90, h: 44, c: "cyan", fill: 0.08 },
      { t: "rect", x: 216, y: 132, w: 30, h: 28, c: "red", fill: 0.2 }, { t: "path", d: "M246 146h8", c: "gray", w: 2 },
      { t: "coil", x: 256, y: 136, w: 28, h: 20, n: 4, c: "cyan" },
      { t: "badge", x: 210, y: 120, n: 6, c: "cyan" },
      { t: "arrow", pts: [[300, 146], [322, 146]], c: "yellow" },
      { t: "rack", x: 326, y: 118, w: 34, h: 54, n: 5, c: "blue" },
      { t: "text", x: 255, y: 182, s: 8, label: "發電機組", muted: true }, { t: "text", x: 343, y: 186, s: 8, label: "資料中心備援", muted: true },
      // 銷售與售後
      { t: "box", x: 14, y: 208, w: 74, h: 30, label: "經銷商", s: 9, c: "green" }, { t: "badge", x: 14, y: 206, n: 7, c: "green" },
      { t: "arrow", pts: [[88, 223], [108, 223]], c: "gray" },
      { t: "box", x: 110, y: 208, w: 74, h: 30, label: "租賃車隊", s: 9, c: "green" }, { t: "badge", x: 110, y: 206, n: 7, c: "green" },
      { t: "arrow", pts: [[184, 223], [204, 223]], c: "gray" },
      { t: "box", x: 206, y: 208, w: 74, h: 30, label: "工地使用", s: 9, c: "gray" },
      { t: "arrow", pts: [[280, 223], [300, 223]], c: "gray" },
      { t: "box", x: 302, y: 208, w: 86, h: 30, label: "零件保養", s: 9, c: "orange" }, { t: "badge", x: 302, y: 206, n: 8, c: "orange" },
      { t: "arrow", pts: [[345, 238], [345, 250], [51, 250], [51, 240]], c: "orange", dash: true, label: "十幾年都要換零件", lx: 198, ly: 247 },
      { t: "legend", x: 14, y: 272, items: [["purple", "液壓"], ["red", "引擎"], ["yellow", "電力"]] },
    ] },
    how: [
      ["在做什麼", "製造蓋路挖地的營建機械、礦場用的大型卡車、農夫用的曳引機與收割機，以及卡車引擎、柴油發電機組和燃氣渦輪等大型設備。"],
      ["怎麼運作", "引擎帶動液壓泵，高壓油推動液壓缸，讓動臂、鏟斗做出大力氣的動作。政府基建、礦業公司、農民與電力業者下單，機械廠組裝後透過各地經銷商銷售與維修；機器動輒用十幾年，期間不斷更換零件與保養。"],
      ["關鍵名詞", "經銷商網路：負責銷售、租賃與維修的在地夥伴。售後市場：零件與服務。積壓訂單（backlog）：已接但還沒交貨的訂單。發電機組：資料中心的備用電源。"],
      ["景氣看什麼", "基建法案與政府預算、銅鐵等商品價格（影響礦業投資）、農產品價格與農民收入、利率、經銷商庫存，以及資料中心帶來的發電設備訂單。"],
      ["代表公司", "Caterpillar（營建礦業機械與發電機組）、Deere（農機）、Cummins（引擎）、PACCAR（卡車）、GE Vernova（燃氣渦輪），以及設備租賃商 United Rentals。台灣有供應零件、液壓件與鑄件的廠商。"],
    ],
    trends: [
      "資料中心帶動備用發電機組與燃氣發電設備需求，成為重工機械的新成長來源",
      "機械加裝感測器與聯網，廠商靠遠端監控、預測保養與軟體訂閱提高售後收入",
      "農機導入自動駕駛與精準農業，用影像辨識精準噴藥、施肥",
      "營建與礦業設備逐步電動化與混合動力化，減少柴油用量與排放",
    ],
    chain: [
      { tier: "上游", title: "關鍵零組件", items: [
        { name: "引擎與動力系統", desc: "柴油、天然氣引擎與傳動系統，是機器的心臟", c: [["CMI", "Cummins", "引擎與動力系統"]] },
        { name: "液壓與傳動元件", desc: "液壓泵、液壓缸、閥件與管路", c: [["PH", "Parker-Hannifin", "液壓與運動控制"]] },
      ] },
      { tier: "中游", title: "整機製造", items: [
        { name: "營建與礦業機械", desc: "挖土機、裝載機、礦用卡車", c: [["CAT", "Caterpillar", "營建與礦業機械"]] },
        { name: "農業機械", desc: "曳引機、收割機與精準農業設備", c: [["DE", "Deere", "農業機械"], ["AGCO", "AGCO", "農業機械"]] },
        { name: "重型卡車", desc: "長途運輸與工程用重卡", c: [["PCAR", "PACCAR", "重型卡車"]] },
        { name: "發電設備", desc: "發電機組與燃氣渦輪，供電網與資料中心", c: [["GEV", "GE Vernova", "燃氣渦輪"], ["CAT", "Caterpillar", "發電機組"], ["CMI", "Cummins", "發電機組"]] },
      ] },
      { tier: "下游", title: "通路與服務", items: [
        { name: "經銷與租賃", desc: "在地銷售、出租設備給工程公司", c: [["URI", "United Rentals", "設備租賃"]] },
        { name: "售後零件與服務", desc: "機器使用十幾年，持續更換零件與保養", c: [["CAT", "Caterpillar", "零件與服務"], ["DE", "Deere", "零件與服務"]] },
      ] },
    ] },

  { id: "jp-nand", mk: "jp", cat: "記憶體", name: "日本 NAND 記憶體", icon: "memory",
    desc: "NAND 快閃記憶體斷電後資料不會消失，做成 SSD 和手機儲存；日本鎧俠和美國 SanDisk 共同營運大型晶圓廠，並以 3D 堆疊技術提高容量。",
    flow: ["晶圓", "3D 堆疊儲存單元", "封裝與控制器", "SSD 與記憶卡", "資料中心、手機"],
    segs: [{ n: "NAND 製造", c: [["285A.T", "鎧俠（Kioxia）", "NAND 快閃記憶體"], ["SNDK", "SanDisk", "美國合資夥伴"]] },
      { n: "設備與材料", c: [["8035.T", "東京威力科創", "蝕刻與沉積設備"], ["4186.T", "東京應化", "光阻劑"], ["3436.T", "SUMCO", "矽晶圓"]] }],
    peers: ["us-memory", "kr-memory"],
    fig: { w: 400, h: 280, alt: "3D NAND：矽晶圓上交錯堆疊上百層字元線，垂直深孔打穿各層形成通道，側邊做成階梯接點；每個儲存單元的電荷存在環狀陷阱層；晶片堆疊封裝後和控制器組成 SSD", items: [
      { t: "wafer", x: 32, y: 60, r: 22, c: "gray", label: "矽晶圓" },
      { t: "badge", x: 12, y: 32, n: 1, c: "gray" },
      { t: "arrow", pts: [[56, 60], [66, 60]], c: "gray" },
      { t: "rect", x: 70, y: 40, w: 130, h: 102, c: "gray", fill: 0.06, stroke: false },
      { t: "path", d: "M70 46H200M70 54H203M70 62H206M70 70H209M70 78H212M70 86H215M70 94H218M70 102H221M70 110H224M70 118H227M70 126H230M70 134H233", c: "blue", w: 3.5 },
      { t: "path", d: "M205 62V34M214 86V34M223 110V34M232 134V34", c: "yellow", w: 1.2 },
      { t: "rect", x: 84, y: 36, w: 8, h: 106, c: "purple", fill: 0.45 }, { t: "rect", x: 112, y: 36, w: 8, h: 106, c: "purple", fill: 0.45 },
      { t: "rect", x: 140, y: 36, w: 8, h: 106, c: "purple", fill: 0.45 }, { t: "rect", x: 168, y: 36, w: 8, h: 106, c: "purple", fill: 0.45 },
      { t: "rect", x: 66, y: 142, w: 172, h: 8, c: "gray", fill: 0.4 },
      { t: "text", x: 150, y: 164, s: 8.5, b: true, label: "上百層堆疊" },
      { t: "badge", x: 72, y: 26, n: 2, c: "red" }, { t: "text", x: 82, y: 29, s: 8, a: "start", label: "深孔蝕刻" },
      { t: "badge", x: 134, y: 26, n: 3, c: "pink" }, { t: "text", x: 144, y: 29, s: 8, a: "start", label: "薄膜材料" },
      { t: "text", x: 220, y: 26, s: 8, label: "階梯接點", muted: true },
      { t: "badge", x: 60, y: 120, n: 4, c: "blue" },
      // 放大：單一儲存單元
      { t: "circle", x: 300, y: 72, r: 34, c: "blue", fill: 0.15 },
      { t: "circle", x: 300, y: 72, r: 22, c: "gray", fill: 0.12 },
      { t: "circle", x: 300, y: 72, r: 15, c: "orange", fill: 0.35 },
      { t: "circle", x: 300, y: 72, r: 7, c: "purple", fill: 0.55 },
      { t: "text", x: 300, y: 120, s: 8, label: "單一儲存單元（俯視）", muted: true },
      { t: "text", x: 300, y: 133, s: 7.5, label: "電荷存在橘色陷阱層", muted: true },
      { t: "badge", x: 268, y: 42, n: 4, c: "blue" },
      { t: "text", x: 362, y: 46, s: 7.5, a: "start", label: "閘極", muted: true }, { t: "line", pts: [[332, 60], [360, 46]], c: "gray", w: 0.8 },
      { t: "text", x: 362, y: 100, s: 7.5, a: "start", label: "通道", muted: true }, { t: "line", pts: [[304, 76], [360, 98]], c: "gray", w: 0.8 },
      // 封裝、SSD、應用
      { t: "stack", x: 16, y: 186, w: 56, h: 34, n: 8, c: "blue" },
      { t: "path", d: "M72 190q10 6 8 30", c: "yellow", w: 0.9 },
      { t: "rect", x: 12, y: 222, w: 72, h: 6, c: "green", fill: 0.4 },
      { t: "text", x: 48, y: 242, s: 8, label: "晶片堆疊封裝", muted: true },
      { t: "badge", x: 12, y: 182, n: 6, c: "green" },
      { t: "arrow", pts: [[88, 208], [104, 208]], c: "gray" },
      { t: "pcb", x: 106, y: 182, w: 150, h: 50, label: "SSD" },
      { t: "rect", x: 114, y: 190, w: 26, h: 26, c: "blue", fill: 0.5 }, { t: "rect", x: 146, y: 190, w: 26, h: 26, c: "blue", fill: 0.5 }, { t: "rect", x: 178, y: 190, w: 26, h: 26, c: "blue", fill: 0.5 },
      { t: "chip", x: 216, y: 192, w: 28, h: 22, label: "控制", c: "purple" },
      { t: "badge", x: 252, y: 178, n: 5, c: "purple" },
      { t: "arrow", pts: [[258, 207], [284, 207]], c: "gray" },
      { t: "rack", x: 288, y: 178, w: 40, h: 56, n: 6, c: "gray", label: "資料中心" },
      { t: "icon", x: 346, y: 188, s: 26, k: "phone", c: "gray", label: "手機" },
      { t: "legend", x: 14, y: 270, items: [["blue", "字元線（閘極）"], ["purple", "垂直通道"], ["yellow", "接點導線"]] },
    ] },
    how: [
      ["在做什麼", "NAND 快閃記憶體是「斷電也記得住」的儲存晶片，做成資料中心的 SSD、筆電硬碟、手機儲存空間和記憶卡。它和 DRAM（工作記憶體）是記憶體的兩大類。"],
      ["怎麼運作", "在晶圓上交錯沉積上百層薄膜，形成一層層字元線；再用深孔蝕刻從上往下打穿，孔裡填入陷阱層與通道，每一層和孔交會處就是一個儲存單元。做好的晶片疊起來封裝，搭配控制器管理讀寫與壽命，組成 SSD。"],
      ["關鍵名詞", "3D NAND：垂直堆疊的快閃記憶體，層數越多容量越大。控制器：SSD 的大腦。QLC／TLC：每個單元存 4 或 3 位元。企業級 SSD：資料中心用、容量與耐用度更高。"],
      ["景氣看什麼", "NAND 合約價、廠商減產或擴產、資料中心 SSD 需求（AI 推論與儲存）、手機與 PC 出貨；記憶體價格常大起大落，是典型的景氣循環產業。"],
      ["和台灣的關係", "鎧俠（東證代號 285A）與 SanDisk 合資在日本四日市與北上營運晶圓廠；台灣群聯、慧榮設計 NAND 控制器，威剛等做記憶體模組，力成等封測廠承接封裝測試。"],
    ],
    trends: [
      "堆疊層數持續往上加，並把周邊電路做在另一片晶圓再接合，以提高密度與速度",
      "AI 推論與資料湖帶動大容量企業級 SSD，QLC 高容量產品逐步取代部分傳統硬碟",
      "深孔蝕刻與薄膜沉積越來越難，設備與材料在 NAND 資本支出中的角色加重",
      "NAND 廠更重視資本紀律，以調整稼動率與擴產節奏來穩定報價",
    ],
    chain: [
      { tier: "上游", title: "材料與設備", items: [
        { name: "矽晶圓", desc: "高純度 300mm 矽晶圓，NAND 的基底", c: [["3436.T", "SUMCO", "矽晶圓"], ["4063.T", "信越化學", "矽晶圓"]] },
        { name: "沉積與蝕刻設備", desc: "沉積上百層薄膜、打出又深又直的通道孔", c: [["8035.T", "東京威力科創", "蝕刻與沉積設備"], ["LRCX", "科林研發", "高深寬比蝕刻"]] },
        { name: "光阻與製程材料", desc: "光阻劑與各種薄膜、化學材料", c: [["4186.T", "東京應化", "光阻劑"]] },
      ] },
      { tier: "中游", title: "晶圓製造與控制", items: [
        { name: "3D NAND 晶圓製造", desc: "堆疊儲存單元做成快閃記憶體晶片（鎧俠為東證 285A）", c: [["SNDK", "SanDisk", "與鎧俠合資營運晶圓廠"], ["005930.KS", "三星電子", "競爭對手"], ["000660.KS", "SK 海力士", "競爭對手"]] },
        { name: "NAND 控制器", desc: "管理讀寫、錯誤更正與壽命的 SSD 大腦", c: [["8299", "群聯", "NAND 控制器與模組"], ["SIMO", "慧榮", "NAND 控制器"]] },
      ] },
      { tier: "下游", title: "封裝模組與應用", items: [
        { name: "封測與記憶體模組", desc: "把晶片堆疊封裝，再做成 SSD、記憶卡與隨身碟", c: [["6239", "力成", "記憶體封測"], ["3260", "威剛", "記憶體模組"]] },
      ] },
    ] },

  { id: "jp-copperfoil", mk: "jp", cat: "PCB", name: "日本銅箔", icon: "layers",
    desc: "銅箔是銅箔基板與印刷電路板的導電層；AI 伺服器與高速交換器需要表面極平滑的高階銅箔來降低訊號損耗，日本廠在高階與載板用極薄銅箔具優勢。",
    flow: ["銅原料", "電解析出", "表面處理", "銅箔基板 CCL", "PCB 與載板"],
    segs: [{ n: "銅箔", c: [["5706.T", "三井金屬", "載板用極薄銅箔"], ["5801.T", "古河電工", "電解銅箔"], ["5016.T", "JX 金屬", "壓延銅箔與半導體材料"]] }],
    peers: ["tw-ccl", "tw-pcb"],
    fig: { w: 400, h: 280, alt: "銅箔：銅溶成電解液，通電後銅在旋轉的鈦滾筒上析出成薄片，剝下後表面處理再捲起；高速板要表面平滑的 HVLP 銅箔降低損耗；銅箔壓上玻纖樹脂成 CCL，再做成 AI 伺服器板", items: [
      { t: "box", x: 12, y: 20, w: 56, h: 28, label: "銅原料", s: 9, c: "orange" },
      { t: "badge", x: 12, y: 18, n: 1, c: "orange" },
      { t: "arrow", pts: [[40, 48], [40, 106]], c: "orange" }, { t: "text", x: 46, y: 80, s: 8, a: "start", label: "溶解", muted: true },
      { t: "path", d: "M20 100V170H200V100", c: "cyan", w: 1.4 },
      { t: "rect", x: 21, y: 110, w: 178, h: 59, c: "cyan", fill: 0.15, stroke: false },
      { t: "circle", x: 110, y: 96, r: 44, c: "gray", fill: 0.15 }, { t: "circle", x: 110, y: 96, r: 6, c: "gray", fill: 0.5 },
      { t: "text", x: 110, y: 80, s: 8, label: "鈦滾筒（陰極）" },
      { t: "path", d: "M66 128A54 54 0 0 0 154 128", c: "red", w: 3 },
      { t: "circle", x: 84, y: 145, r: 2, c: "orange", fill: 0.9 }, { t: "circle", x: 110, y: 146, r: 2, c: "orange", fill: 0.9 }, { t: "circle", x: 136, y: 145, r: 2, c: "orange", fill: 0.9 },
      { t: "text", x: 110, y: 164, s: 8, label: "陽極", c: "red" },
      { t: "text", x: 110, y: 184, s: 8, label: "硫酸銅電解液", muted: true },
      { t: "path", d: "M138 62C156 48 176 42 200 42H264", c: "orange", w: 2.2 },
      { t: "badge", x: 172, y: 30, n: 2, c: "orange" },
      { t: "circle", x: 220, y: 50, r: 7, c: "gray", fill: 0.3 }, { t: "circle", x: 244, y: 50, r: 7, c: "gray", fill: 0.3 },
      { t: "text", x: 232, y: 70, s: 8, label: "粗化／防鏽", muted: true },
      { t: "circle", x: 282, y: 52, r: 18, c: "orange", fill: 0.35 }, { t: "circle", x: 282, y: 52, r: 5, c: "orange", fill: 0.7 },
      { t: "text", x: 282, y: 84, s: 8, label: "銅箔捲", muted: true },
      // 壓延
      { t: "circle", x: 352, y: 34, r: 11, c: "gray", fill: 0.3 }, { t: "circle", x: 352, y: 70, r: 11, c: "gray", fill: 0.3 },
      { t: "rect", x: 312, y: 47, w: 40, h: 10, c: "orange", fill: 0.5 }, { t: "rect", x: 352, y: 50, w: 38, h: 4, c: "orange", fill: 0.8 },
      { t: "text", x: 352, y: 94, s: 8, label: "壓延銅箔", muted: true },
      { t: "badge", x: 384, y: 24, n: 4, c: "orange" },
      // 表面粗糙度
      { t: "group", x: 214, y: 100, w: 178, h: 72, label: "表面越平滑，損耗越小", c: "gray" },
      { t: "wave", x: 226, y: 124, w: 70, n: 3, a: 3, c: "red" }, { t: "wave", x: 312, y: 124, w: 70, n: 3, a: 3, c: "green" },
      { t: "rect", x: 226, y: 140, w: 70, h: 14, c: "orange", fill: 0.45 },
      { t: "path", d: "M226 140l5-6 5 6 5-6 5 6 5-6 5 6 5-6 5 6 5-6 5 6 5-6 5 6 5-6 5 6", c: "orange", w: 1.2 },
      { t: "rect", x: 312, y: 140, w: 70, h: 14, c: "orange", fill: 0.45 },
      { t: "path", d: "M312 140q4.4-2 8.75 0t8.75 0 8.75 0 8.75 0 8.75 0 8.75 0 8.75 0 8.75 0", c: "orange", w: 1.2 },
      { t: "text", x: 261, y: 166, s: 8, label: "一般銅箔", muted: true }, { t: "text", x: 347, y: 166, s: 8, b: true, label: "HVLP" },
      { t: "badge", x: 384, y: 112, n: 2, c: "orange" },
      // 下排：極薄銅箔、CCL、PCB
      { t: "rect", x: 14, y: 198, w: 92, h: 12, c: "orange", fill: 0.25 },
      { t: "rect", x: 14, y: 210, w: 92, h: 3, c: "gray", fill: 0.6, stroke: false },
      { t: "rect", x: 14, y: 213, w: 92, h: 4, c: "orange", fill: 0.8 },
      { t: "text", x: 60, y: 230, s: 8, label: "附載體極薄銅箔", muted: true }, { t: "text", x: 60, y: 242, s: 7.5, label: "做載板細線路", muted: true },
      { t: "badge", x: 14, y: 192, n: 3, c: "pink" },
      { t: "rect", x: 140, y: 196, w: 100, h: 5, c: "orange", fill: 0.7 },
      { t: "rect", x: 140, y: 201, w: 100, h: 18, c: "green", fill: 0.2 },
      { t: "path", d: "M142 207q6-4 12 0t12 0 12 0 12 0 12 0 12 0 12 0 12 0M142 213q6 4 12 0t12 0 12 0 12 0 12 0 12 0 12 0 12 0", c: "green", w: 0.8 },
      { t: "rect", x: 140, y: 219, w: 100, h: 5, c: "orange", fill: 0.7 },
      { t: "text", x: 190, y: 238, s: 8, label: "CCL：銅＋玻纖樹脂", muted: true },
      { t: "badge", x: 134, y: 190, n: 5, c: "green" },
      { t: "arrow", pts: [[242, 210], [268, 210]], c: "gray" },
      { t: "pcb", x: 272, y: 200, w: 116, h: 34 },
      { t: "chip", x: 312, y: 184, w: 36, h: 14, label: "GPU", s: 8, c: "purple" },
      { t: "text", x: 330, y: 248, s: 8, label: "AI 伺服器板", muted: true },
      { t: "badge", x: 272, y: 194, n: 6, c: "blue" },
      { t: "legend", x: 14, y: 270, items: [["orange", "銅"], ["green", "玻纖樹脂"], ["red", "高頻訊號"]] },
    ] },
    how: [
      ["在做什麼", "銅箔是一層比頭髮還薄的銅片，貼在玻纖布與樹脂上做成銅箔基板（CCL），再蝕刻成印刷電路板上的線路。訊號和電流都靠它傳遞。"],
      ["怎麼運作", "把銅溶成電解液，通電後銅會在旋轉的鈦滾筒上析出成連續的薄片，剝下來後做表面處理（粗化、防鏽）再捲起。另一種壓延銅箔則是把銅塊反覆輾薄，柔軟耐彎折，多用在軟板。"],
      ["關鍵名詞", "HVLP：超低輪廓銅箔，表面極平滑，用於高速板。集膚效應：高頻訊號只走在導體表面，所以表面粗糙會增加損耗。極薄銅箔：附載體的超薄銅箔，用於 IC 載板細線路。"],
      ["景氣看什麼", "AI 伺服器與 800G／1.6T 交換器出貨（帶動高階 CCL）、高階銅箔的產能與加工費、銅價、IC 載板需求；一般消費電子用銅箔則競爭激烈。"],
      ["和台灣的關係", "台灣的台光電、聯茂、台燿等 CCL 廠是高階銅箔的主要買家，金居等台廠也生產高階銅箔；日本廠在載板用極薄銅箔等領域較具優勢。"],
    ],
    trends: [
      "AI 伺服器與高速交換器的傳輸速度提高，HVLP 銅箔一代比一代平滑，規格持續升級",
      "高階銅箔產能擴充慢、認證時間長，加工費比一般銅箔更有支撐",
      "IC 載板線路越來越細，帶動附載體極薄銅箔需求",
      "CCL 廠與銅箔廠更早共同開發材料，銅箔、樹脂與玻纖布要一起搭配調整",
    ],
    chain: [
      { tier: "上游", title: "銅原料", items: [
        { name: "電解銅與銅原料", desc: "冶煉精煉出的高純度銅，溶解成電解液", c: [["5713.T", "住友金屬礦山", "銅冶煉"]] },
      ] },
      { tier: "中游", title: "銅箔製造", items: [
        { name: "電解銅箔（HVLP）", desc: "滾筒電鍍析出，表面越平滑越適合高速板", c: [["5706.T", "三井金屬", "高階電解銅箔"], ["5801.T", "古河電工", "電解銅箔"], ["8358", "金居", "高階電解銅箔"]] },
        { name: "載板用極薄銅箔", desc: "附載體的超薄銅箔，用來做 IC 載板細線路", c: [["5706.T", "三井金屬", "載板用極薄銅箔"]] },
        { name: "壓延銅箔", desc: "把銅反覆輾薄，柔軟耐彎折，用於軟板", c: [["5016.T", "JX 金屬", "壓延銅箔"]] },
      ] },
      { tier: "下游", title: "基板與電路板", items: [
        { name: "銅箔基板（CCL）", desc: "銅箔壓上玻纖布與樹脂，是 PCB 的原料", c: [["2383", "台光電", "高速 CCL"], ["6213", "聯茂", "CCL"], ["6274", "台燿", "高速 CCL"]] },
        { name: "PCB 與 IC 載板", desc: "把 CCL 蝕刻成線路，做成伺服器板與載板", c: [["3037", "欣興", "IC 載板與 PCB"], ["2368", "金像電", "伺服器 PCB"]] },
      ] },
    ] },

  { id: "kr-components", mk: "kr", cat: "電子零組件", name: "韓國電子元件", icon: "layers",
    desc: "韓國的被動元件、IC 載板與相機模組廠，以三星電機和 LG Innotek 為代表，客戶包括手機品牌、AI 伺服器與汽車，與日本、台灣廠商在同一市場競爭。",
    flow: ["陶瓷與樹脂材料", "MLCC 與載板", "相機模組", "手機、伺服器、汽車"],
    segs: [{ n: "元件與載板", c: [["009150.KS", "三星電機", "MLCC、FC-BGA 載板、相機模組"], ["011070.KS", "LG Innotek", "相機模組、載板"], ["007660.KS", "ISU Petasys", "AI 伺服器多層板"]] }],
    peers: ["jp-mlcc", "tw-passive", "tw-substrate"],
    fig: { w: 400, h: 280, alt: "韓國電子元件：MLCC 內部陶瓷與電極交錯疊上百層；FC-BGA 載板用增層膜做細線路連接晶片和主機板；相機模組由鏡片、對焦馬達與感測器組成；AI 伺服器用高層數多層板；客戶是手機、伺服器與汽車", items: [
      // MLCC
      { t: "text", x: 72, y: 22, s: 8, label: "MLCC 剖面", muted: true },
      { t: "rect", x: 24, y: 36, w: 96, h: 52, c: "yellow", fill: 0.18 },
      { t: "rect", x: 14, y: 34, w: 12, h: 56, c: "gray", fill: 0.55 }, { t: "rect", x: 118, y: 34, w: 12, h: 56, c: "gray", fill: 0.55 },
      { t: "path", d: "M26 42h80M26 54h80M26 66h80M26 78h80", c: "blue", w: 2 },
      { t: "path", d: "M38 48h80M38 60h80M38 72h80M38 84h80", c: "red", w: 2 },
      { t: "text", x: 72, y: 104, s: 8, label: "陶瓷與電極疊上百層", muted: true },
      { t: "badge", x: 138, y: 40, n: 2, c: "orange" },
      // FC-BGA
      { t: "chip", x: 196, y: 30, w: 66, h: 18, label: "晶片", c: "purple" },
      { t: "path", d: "M204 54v4M214 54v4M224 54v4M234 54v4M244 54v4M254 54v4", c: "yellow", w: 3 },
      { t: "rect", x: 166, y: 58, w: 126, h: 10, c: "pink", fill: 0.3 },
      { t: "rect", x: 166, y: 68, w: 126, h: 14, c: "gray", fill: 0.35 },
      { t: "rect", x: 166, y: 82, w: 126, h: 10, c: "pink", fill: 0.3 },
      { t: "path", d: "M170 63h118M170 87h118", c: "pink", w: 0.6 },
      { t: "path", d: "M200 58v34M230 58v34M260 58v34", c: "orange", w: 2 },
      { t: "path", d: "M176 98h.1M194 98h.1M212 98h.1M230 98h.1M248 98h.1M266 98h.1M284 98h.1", c: "gray", w: 6 },
      { t: "text", x: 229, y: 116, s: 8, label: "FC-BGA 載板", muted: true },
      { t: "badge", x: 160, y: 75, n: 3, c: "purple" },
      { t: "badge", x: 298, y: 63, n: 1, c: "pink" },
      // 相機模組
      { t: "rect", x: 322, y: 26, w: 64, h: 76, c: "gray", fill: 0.06 },
      { t: "path", d: "M330 42q24-8 48 0q-24 8-48 0zM332 56q22-7 44 0q-22 7-44 0zM334 70q20-6 40 0q-20 6-40 0z", c: "cyan", fill: 0.3 },
      { t: "rect", x: 323, y: 34, w: 5, h: 44, c: "orange", fill: 0.5 }, { t: "rect", x: 380, y: 34, w: 5, h: 44, c: "orange", fill: 0.5 },
      { t: "rect", x: 336, y: 84, w: 36, h: 8, c: "purple", fill: 0.6 },
      { t: "rect", x: 322, y: 94, w: 64, h: 6, c: "green", fill: 0.5 },
      { t: "text", x: 354, y: 116, s: 8, label: "相機模組", muted: true },
      { t: "badge", x: 386, y: 20, n: 5, c: "cyan" },
      // 多層板與 ABF
      { t: "stack", x: 24, y: 132, w: 120, h: 40, n: 10, c: "green" },
      { t: "path", d: "M60 132v40M100 132v40", c: "orange", w: 2 },
      { t: "text", x: 84, y: 186, s: 8, label: "高層數多層板", muted: true },
      { t: "badge", x: 16, y: 128, n: 4, c: "green" },
      { t: "box", x: 168, y: 136, w: 64, h: 32, label: "ABF 膜", sub: "增層材料", c: "pink" },
      { t: "badge", x: 168, y: 136, n: 1, c: "pink" },
      // 客戶
      { t: "rect", x: 262, y: 130, w: 34, h: 62, r: 6, c: "gray", fill: 0.08 },
      { t: "path", d: "M270 150h.1M276 150h.1M282 150h.1M270 158h.1M276 158h.1M282 158h.1M288 158h.1M270 166h.1M276 166h.1", c: "yellow", w: 3 },
      { t: "circle", x: 288, y: 140, r: 3, c: "cyan", fill: 0.5 },
      { t: "text", x: 279, y: 206, s: 8, label: "手機", muted: true },
      { t: "badge", x: 256, y: 126, n: 6, c: "gray" },
      { t: "rack", x: 310, y: 130, w: 30, h: 62, n: 6, c: "blue" }, { t: "text", x: 325, y: 206, s: 8, label: "伺服器", muted: true },
      { t: "icon", x: 354, y: 150, s: 32, k: "car", c: "blue" }, { t: "text", x: 370, y: 206, s: 8, label: "汽車", muted: true },
      { t: "badge", x: 370, y: 140, n: 7, c: "blue" },
      // MLCC 製程
      { t: "box", x: 10, y: 216, w: 66, h: 26, label: "陶瓷薄片", s: 9, c: "yellow" }, { t: "arrow", pts: [[76, 229], [86, 229]], c: "gray" },
      { t: "box", x: 88, y: 216, w: 66, h: 26, label: "印刷電極", s: 9, c: "blue" }, { t: "arrow", pts: [[154, 229], [164, 229]], c: "gray" },
      { t: "box", x: 166, y: 216, w: 66, h: 26, label: "疊層壓合", s: 9, c: "orange" }, { t: "arrow", pts: [[232, 229], [242, 229]], c: "gray" },
      { t: "box", x: 244, y: 216, w: 66, h: 26, label: "高溫燒結", s: 9, c: "red" }, { t: "arrow", pts: [[310, 229], [320, 229]], c: "gray" },
      { t: "box", x: 322, y: 216, w: 66, h: 26, label: "端電極", s: 9, c: "gray" },
      { t: "legend", x: 14, y: 270, items: [["yellow", "陶瓷"], ["pink", "增層膜"], ["cyan", "鏡片"], ["orange", "導通孔"]] },
    ] },
    how: [
      ["在做什麼", "韓國電子元件廠生產三類關鍵零件：調節電流的 MLCC 積層陶瓷電容、承載晶片的 IC 封裝載板，以及手機與汽車用的相機模組，主要客戶是全球手機品牌、伺服器與車廠。"],
      ["怎麼運作", "MLCC 把陶瓷薄片印上電極、疊上數百層再燒結；FC-BGA 載板用 ABF 增層膜做出細線路，連接晶片和主機板；相機模組把鏡頭、感測器與對焦馬達組裝在一起；AI 伺服器則用層數很高的多層板。"],
      ["關鍵名詞", "MLCC：最常見的被動元件，一支手機用上千顆。FC-BGA：高階處理器用的封裝載板。ABF：日本味之素開發的增層絕緣膜。多層板：AI 伺服器與交換器用、層數很高的 PCB。車規：汽車用、要求更嚴格的品質等級。"],
      ["景氣看什麼", "手機新機出貨、AI 伺服器與 AI 晶片的載板需求、車用電子比重、MLCC 庫存與報價，以及韓元匯率。"],
      ["和台灣的關係", "MLCC 對手是台灣國巨、華新科與日本村田；載板對手是欣興、南電、景碩；相機鏡頭則有大立光、玉晶光。看韓國廠的財報與展望，可以推估同業景氣。"],
    ],
    trends: [
      "AI 伺服器用的 MLCC 需要更高容值與耐溫，高階規格比重提升",
      "AI 晶片封裝越做越大，FC-BGA 載板層數與面積增加，並評估玻璃基板等新材料",
      "相機模組從手機延伸到車用與機器人，車用鏡頭與感測模組比重提高",
      "AI 伺服器與交換器的多層板層數更高，帶動高階 PCB 與材料規格升級",
    ],
    chain: [
      { tier: "上游", title: "材料", items: [
        { name: "增層材料（ABF）", desc: "載板細線路用的絕緣增層膜", c: [["2802.T", "味之素", "ABF 增層膜"]] },
      ] },
      { tier: "中游", title: "元件與模組", items: [
        { name: "MLCC 積層陶瓷電容", desc: "陶瓷與電極疊上百層，穩定電壓、濾除雜訊", c: [["009150.KS", "三星電機", "MLCC"], ["6981.T", "村田製作所", "MLCC 競爭對手"], ["2327", "國巨", "MLCC 競爭對手"]] },
        { name: "FC-BGA 載板", desc: "高階處理器用的封裝載板，連接晶片和主機板", c: [["009150.KS", "三星電機", "FC-BGA 載板"], ["011070.KS", "LG Innotek", "載板"], ["4062.T", "揖斐電", "FC-BGA 競爭對手"], ["3037", "欣興", "FC-BGA 競爭對手"]] },
        { name: "高層數多層板", desc: "AI 伺服器與交換器用的高層數 PCB", c: [["007660.KS", "ISU Petasys", "AI 伺服器多層板"], ["2368", "金像電", "競爭對手"]] },
        { name: "相機模組", desc: "鏡頭、感測器與對焦馬達組成的模組", c: [["011070.KS", "LG Innotek", "手機相機模組"], ["009150.KS", "三星電機", "相機模組"], ["3008", "大立光", "鏡頭（台灣）"]] },
      ] },
      { tier: "下游", title: "終端客戶", items: [
        { name: "手機品牌", desc: "旗艦手機是 MLCC 與相機模組最大的客戶", c: [["AAPL", "蘋果", "手機品牌"], ["005930.KS", "三星電子", "手機品牌"]] },
        { name: "AI 伺服器與汽車", desc: "AI 晶片帶動載板與多層板，車用電子帶動車規元件", c: [["NVDA", "輝達", "AI 晶片與伺服器平台"], ["005380.KS", "現代汽車", "車用元件需求"]] },
      ] },
    ] },
);
