/* 精細版（新題材）：量子運算、企業軟體 SaaS、資料平台與可觀測性、資安防護、系統整合與委外、電信與數位媒體、數位廣告 AdTech、交易所與金融資料、另類資產與私募信貸、金融科技與支付。圖上的編號圓點對應 chain 第 n 段。 */
INDUSTRY_PACK.push(
  { id: "us-quantum", mk: "us", cat: "量子運算", name: "量子運算", icon: "chip",
    desc: "用量子位元取代一般的 0 與 1 來計算，目標是解決傳統電腦算不完的化學、材料與最佳化問題；目前仍在研發與早期商用階段。",
    flow: ["量子位元晶片", "極低溫冷卻", "微波控制與讀出", "錯誤更正", "雲端提供算力"],
    segs: [{ n: "量子硬體新創", c: [["IONQ", "IonQ", "離子阱量子電腦"], ["RGTI", "Rigetti Computing", "超導量子電腦"], ["QBTS", "D-Wave Quantum", "量子退火"]] },
      { n: "大型科技公司", c: [["IBM", "IBM", "超導量子電腦與雲端平台"], ["GOOGL", "Alphabet", "Google 量子 AI 晶片"], ["HON", "Honeywell", "持有 Quantinuum"]] }],
    fig: { w: 400, h: 280, alt: "量子運算：量子位元晶片放在一層層降溫的稀釋冷凍機底部，控制電子送微波脈衝進去、讀出訊號送出來，古典電腦與 GPU 解碼錯誤，再透過雲端提供算力；另有離子阱與量子退火等路線", items: [
      // 微波線與讀出線（冷凍機外）
      { t: "arrow", pts: [[244, 34], [244, 18], [72, 18], [72, 40]], c: "orange", label: "微波脈衝", lx: 150, ly: 13 },
      { t: "arrow", pts: [[86, 40], [86, 25], [212, 25], [212, 32]], c: "blue" },
      // 稀釋冷凍機
      { t: "group", x: 8, y: 30, w: 166, h: 196, label: "稀釋冷凍機", c: "cyan" },
      { t: "rect", x: 22, y: 46, w: 120, h: 5, c: "gray", fill: 0.5 },
      { t: "rect", x: 30, y: 76, w: 104, h: 5, c: "cyan", fill: 0.35 },
      { t: "rect", x: 38, y: 104, w: 88, h: 5, c: "cyan", fill: 0.5 },
      { t: "rect", x: 46, y: 130, w: 72, h: 5, c: "cyan", fill: 0.65 },
      { t: "rect", x: 52, y: 154, w: 60, h: 5, c: "blue", fill: 0.8 },
      { t: "path", d: "M30 51V76M134 51V76M38 81V104M126 81V104M46 109V130M118 109V130M54 135V154M110 135V154", c: "gray", w: 1 },
      { t: "text", x: 148, y: 52, s: 7.5, a: "start", label: "室溫", muted: true },
      { t: "text", x: 148, y: 82, s: 7.5, a: "start", label: "4K", muted: true },
      { t: "text", x: 148, y: 110, s: 7.5, a: "start", label: "0.8K", muted: true },
      { t: "text", x: 148, y: 136, s: 7.5, a: "start", label: "0.1K", muted: true },
      { t: "text", x: 148, y: 160, s: 7.5, a: "start", label: "10mK", muted: true },
      { t: "path", d: "M72 40V168", c: "orange", w: 1.4 },
      { t: "path", d: "M86 40V168", c: "blue", w: 1.4 },
      { t: "rect", x: 69, y: 58, w: 6, h: 9, c: "orange", fill: 0.7 }, { t: "rect", x: 69, y: 88, w: 6, h: 9, c: "orange", fill: 0.7 }, { t: "rect", x: 69, y: 116, w: 6, h: 9, c: "orange", fill: 0.7 },
      { t: "path", d: "M82 98h8l-4-8z", c: "blue", fill: 0.7 },
      { t: "text", x: 98, y: 66, s: 7.5, a: "start", label: "衰減器", muted: true },
      { t: "text", x: 98, y: 96, s: 7.5, a: "start", label: "放大器", muted: true },
      { t: "chip", x: 56, y: 172, w: 52, h: 24, label: "量子位元", s: 8, c: "purple" },
      { t: "badge", x: 130, y: 184, n: 2, c: "purple" },
      { t: "rect", x: 46, y: 164, w: 72, h: 40, c: "cyan", fill: 0.04, dash: true },
      { t: "callout", x: 46, y: 190, tx: 43, ty: 196, label: "磁屏蔽", c: "cyan", a: "end" },
      { t: "text", x: 82, y: 214, s: 8, label: "接近 -273°C", muted: true },
      { t: "hatch", x: 12, y: 46, w: 4, h: 150, c: "gray", gap: 3 },
      { t: "grad", x: 168, y: 48, w: 3, h: 114, c: "orange", c2: "blue", o: 0.85 },
      { t: "rect", x: 142, y: 33, w: 14, h: 10, c: "cyan", fill: 0.4 },
      { t: "text", x: 138, y: 42, s: 7, a: "end", label: "脈衝管預冷", muted: true },
      { t: "path", d: "M79 40V168", c: "gray", w: 0.8 },
      { t: "rect", x: 83, y: 138, w: 6, h: 8, c: "blue", fill: 0.7 },
      { t: "callout", x: 89, y: 142, tx: 94, ty: 124, label: "隔離器", c: "blue" },
      { t: "callout", x: 72, y: 120, tx: 44, ty: 123, label: "同軸線", c: "orange", a: "end" },
      { t: "callout", x: 100, y: 157, tx: 120, ty: 150, label: "混合腔", c: "blue" },
      // 邏輯位元
      { t: "text", x: 14, y: 238, s: 7.5, a: "start", label: "多個實體位元", muted: true },
      { t: "rect", x: 12, y: 241, w: 50, h: 18, c: "purple", fill: 0.05, dash: true },
      { t: "dots", x: 14, y: 242, w: 46, h: 16, n: 14, sz: 1.8, c: "purple" },
      { t: "arrow", pts: [[66, 250], [98, 250]], c: "purple", label: "錯誤更正", lx: 83, ly: 244 },
      { t: "circle", x: 110, y: 250, r: 7, c: "purple", fill: 0.55 },
      { t: "text", x: 121, y: 253, s: 8.5, a: "start", b: true, label: "1 個邏輯位元" },
      // 控制、古典運算、雲端
      { t: "box", x: 196, y: 34, w: 84, h: 40, label: "控制電子", sub: "脈衝與讀出", c: "orange" },
      { t: "badge", x: 196, y: 34, n: 1, c: "orange" },
      { t: "wave", x: 178, y: 11, w: 40, n: 3, a: 2.5, c: "orange", sw: 1.2 },
      { t: "path", d: "M280 47H286M280 65H286", c: "orange", w: 1 },
      { t: "chip", x: 290, y: 40, w: 26, h: 13, label: "DAC", s: 7, c: "orange" },
      { t: "chip", x: 290, y: 58, w: 26, h: 13, label: "ADC", s: 7, c: "blue" },
      { t: "callout", x: 262, y: 136, tx: 300, ty: 148, label: "即時解碼錯誤", c: "gray" },
      { t: "icon", x: 300, y: 78, s: 15, k: "laptop", c: "purple" },
      { t: "icon", x: 320, y: 78, s: 15, k: "laptop", c: "purple" },
      { t: "path", d: "M336 82L348 73", c: "purple", w: 0.8, dash: true },
      { t: "text", x: 318, y: 106, s: 7.5, label: "研究團隊", muted: true },
      { t: "rect", x: 296, y: 111, w: 7, h: 10, c: "purple", fill: 0.5 }, { t: "rect", x: 306, y: 111, w: 7, h: 10, c: "purple", fill: 0.5 }, { t: "rect", x: 316, y: 111, w: 7, h: 10, c: "purple", fill: 0.5 },
      { t: "arrow", pts: [[238, 74], [238, 94]], c: "gray" },
      { t: "box", x: 196, y: 96, w: 84, h: 40, label: "古典電腦", sub: "解碼・錯誤更正", c: "gray" },
      { t: "path", d: "M238 136V148", c: "green", w: 1.4 },
      { t: "chip", x: 220, y: 150, w: 36, h: 20, label: "GPU", c: "green" },
      { t: "text", x: 264, y: 164, s: 7.5, a: "start", label: "模擬與混合運算", muted: true },
      { t: "badge", x: 210, y: 160, n: 5, c: "green" },
      { t: "arrow", pts: [[280, 116], [357, 116], [357, 82]], c: "purple" },
      { t: "icon", x: 340, y: 40, s: 34, k: "cloud", c: "purple" },
      { t: "text", x: 357, y: 34, s: 8, label: "雲端存取", muted: true },
      { t: "badge", x: 384, y: 50, n: 6, c: "purple" },
      { t: "text", x: 318, y: 130, s: 7.5, label: "按使用量付費", muted: true },
      // 技術路線
      { t: "group", x: 186, y: 194, w: 206, h: 62, label: "三種主要路線", c: "purple" },
      { t: "box", x: 194, y: 212, w: 60, h: 36, label: "超導", sub: "極低溫晶片", c: "purple" },
      { t: "box", x: 260, y: 212, w: 60, h: 36, label: "離子阱", sub: "雷射操控", c: "pink" },
      { t: "box", x: 326, y: 212, w: 60, h: 36, label: "量子退火", sub: "找最佳解", c: "blue" },
      { t: "badge", x: 252, y: 212, n: 2, c: "purple" }, { t: "badge", x: 318, y: 212, n: 3, c: "pink" }, { t: "badge", x: 384, y: 212, n: 4, c: "blue" },
      { t: "legend", x: 14, y: 272, items: [["orange", "控制微波"], ["blue", "讀出訊號"], ["purple", "算力交付"]] },
    ] },
    how: [
      ["在做什麼", "一般電腦用 0 或 1 計算，量子電腦用「量子位元」，可以同時處在多種狀態的疊加，適合模擬分子、材料或找最佳解這類傳統電腦要算非常久的問題。"],
      ["怎麼運作", "超導路線的量子位元晶片放在稀釋冷凍機最底層，一層層降到接近絕對零度；外面的控制電子把微波脈衝經過衰減器送進去操作位元，讀出訊號再經放大器傳出來，交給古典電腦與 GPU 解碼。另有離子阱、光子、中性原子與量子退火等路線。"],
      ["關鍵名詞", "量子位元（qubit）：計算的基本單位。退相干：量子狀態被雜訊破壞。錯誤更正：用很多實體位元組成一個穩定的「邏輯位元」，是能否實用的關鍵。稀釋冷凍機：把晶片降到毫開爾文等級的低溫設備。"],
      ["景氣看什麼", "邏輯位元數量與錯誤率的進展、政府與大企業的研發預算、雲端量子服務的使用量；目前多數公司仍在虧損、靠募資推進，股價隨技術消息大幅波動。"],
      ["代表公司", "IBM、Google、Rigetti 走超導路線，IonQ 與 Honeywell 持有的 Quantinuum 走離子阱，D-Wave 做量子退火；輝達提供 GPU 混合運算平台，亞馬遜、微軟提供雲端量子服務。台灣仍以學研機構研發為主。"],
    ],
    trends: [
      "研發重點由增加實體位元數量，轉向降低錯誤率、做出能長時間運算的邏輯位元",
      "量子電腦和 GPU 超級電腦混合運算，由古典電腦即時解碼錯誤並分擔部分計算",
      "超導、離子阱、中性原子、光子多條路線並行競爭，尚未出現勝出的標準架構",
      "各國推動後量子密碼，提前替換未來可能被量子電腦破解的加密方式",
    ],
    chain: [
      { tier: "上游", title: "控制與量測", items: [
        { name: "控制與量測電子", desc: "產生精準的微波脈衝操作量子位元，並讀出量測結果", c: [["KEYS", "Keysight", "量子控制與量測系統"]] },
      ] },
      { tier: "中游", title: "量子電腦系統", items: [
        { name: "超導量子電腦", desc: "在極低溫晶片上做量子位元，速度快但要大型冷凍機", c: [["IBM", "IBM", "超導量子電腦"], ["GOOGL", "Alphabet", "Google 量子 AI 晶片"], ["RGTI", "Rigetti Computing", "超導量子電腦"]] },
        { name: "離子阱量子電腦", desc: "用雷射操控懸浮的帶電原子，位元品質高、速度較慢", c: [["IONQ", "IonQ", "離子阱量子電腦"], ["HON", "Honeywell", "持有 Quantinuum 股權"]] },
        { name: "量子退火", desc: "專門解最佳化問題的量子機器，已有早期商用案例", c: [["QBTS", "D-Wave Quantum", "量子退火與閘道式系統"]] },
      ] },
      { tier: "下游", title: "算力交付與應用", items: [
        { name: "GPU 混合運算", desc: "用 GPU 模擬量子電路、即時解碼錯誤，與量子電腦分工", c: [["NVDA", "輝達", "CUDA-Q 混合運算平台"]] },
        { name: "雲端量子服務", desc: "企業與研究單位透過雲端按使用量存取量子電腦", c: [["AMZN", "亞馬遜", "Amazon Braket"], ["MSFT", "微軟", "Azure Quantum"], ["IBM", "IBM", "IBM Quantum 平台"]] },
      ] },
    ] },

  { id: "us-saas", mk: "us", cat: "軟體", name: "企業軟體與 SaaS", icon: "code",
    desc: "把企業軟體做成線上服務按月或按年收訂閱費，客戶不用自己裝伺服器；收入可預期、毛利高，近年再加上 AI 助理功能加價收費。",
    flow: ["開發軟體平台", "放上雲端", "企業訂閱", "續約與加購", "AI 功能加值"],
    segs: [{ n: "企業應用", c: [["CRM", "Salesforce", "客戶關係管理"], ["NOW", "ServiceNow", "IT 與企業流程"], ["WDAY", "Workday", "人資與財務"], ["SAP", "SAP", "企業資源規劃 ERP"]] },
      { n: "其他軟體", c: [["ADBE", "Adobe", "創意與文件軟體"], ["INTU", "Intuit", "會計與報稅"], ["ORCL", "甲骨文", "資料庫與 ERP"]] }],
    fig: { w: 400, h: 280, alt: "SaaS：員工用瀏覽器登入，AI 代理層與各種應用模組跑在同一套多租戶平台上，平台再跑在公有雲；收入靠訂閱，同一客戶續約加購讓收入逐年墊高", items: [
      // 使用者
      { t: "icon", x: 20, y: 10, s: 18, k: "person", c: "gray" }, { t: "icon", x: 40, y: 10, s: 18, k: "person", c: "gray" }, { t: "icon", x: 60, y: 10, s: 18, k: "person", c: "gray" },
      { t: "icon", x: 86, y: 9, s: 20, k: "laptop", c: "blue" },
      { t: "text", x: 114, y: 23, s: 8, a: "start", label: "員工用瀏覽器登入", muted: true },
      { t: "path", d: "M50 32V50M96 32V50", c: "gray", w: 1.2, dash: true },
      // AI 代理層
      { t: "rect", x: 16, y: 52, w: 228, h: 24, c: "pink", fill: 0.16, r: 4 },
      { t: "icon", x: 22, y: 54, s: 20, k: "robot", c: "pink" },
      { t: "text", x: 136, y: 68, s: 8.5, b: true, label: "AI 代理：自動處理工單" },
      { t: "badge", x: 244, y: 52, n: 7, c: "pink" },
      // 應用模組
      { t: "box", x: 16, y: 86, w: 40, h: 30, label: "CRM", s: 9, c: "blue" },
      { t: "box", x: 62, y: 86, w: 40, h: 30, label: "ITSM", s: 9, c: "cyan" },
      { t: "box", x: 108, y: 86, w: 40, h: 30, label: "人資", s: 9, c: "green" },
      { t: "box", x: 154, y: 86, w: 40, h: 30, label: "ERP", s: 9, c: "orange" },
      { t: "box", x: 200, y: 86, w: 44, h: 30, label: "設計", s: 9, c: "purple" },
      { t: "badge", x: 16, y: 86, n: 3, c: "blue" }, { t: "badge", x: 62, y: 86, n: 4, c: "cyan" }, { t: "badge", x: 108, y: 86, n: 5, c: "green" }, { t: "badge", x: 154, y: 86, n: 5, c: "orange" }, { t: "badge", x: 244, y: 86, n: 6, c: "purple" },
      { t: "path", d: "M36 116V128M82 116V128M128 116V128M174 116V128M222 116V128", c: "gray", w: 1.2 },
      // 多租戶平台
      { t: "rect", x: 16, y: 128, w: 228, h: 48, c: "purple", fill: 0.08, r: 4 },
      { t: "text", x: 24, y: 142, s: 8.5, a: "start", b: true, label: "多租戶平台" },
      { t: "box", x: 24, y: 150, w: 44, h: 18, label: "客戶A", s: 8, c: "gray" },
      { t: "box", x: 74, y: 150, w: 44, h: 18, label: "客戶B", s: 8, c: "gray" },
      { t: "box", x: 124, y: 150, w: 44, h: 18, label: "客戶C", s: 8, c: "gray" },
      { t: "path", d: "M168 159H190", c: "purple", w: 1.2 },
      { t: "cyl", x: 192, y: 134, w: 40, h: 36, c: "purple" },
      { t: "text", x: 150, y: 142, s: 7.5, label: "共用資料庫", muted: true },
      { t: "badge", x: 244, y: 128, n: 2, c: "purple" },
      // 公有雲
      { t: "rect", x: 16, y: 186, w: 228, h: 46, c: "gray", fill: 0.08, r: 4 },
      { t: "rack", x: 26, y: 192, w: 26, h: 34, n: 4, c: "gray" }, { t: "rack", x: 58, y: 192, w: 26, h: 34, n: 4, c: "gray" }, { t: "rack", x: 90, y: 192, w: 26, h: 34, n: 4, c: "gray" },
      { t: "text", x: 194, y: 206, s: 9, b: true, label: "公有雲 IaaS" },
      { t: "text", x: 194, y: 220, s: 7.5, label: "伺服器・儲存・網路", muted: true },
      { t: "badge", x: 244, y: 186, n: 1, c: "orange" },
      { t: "text", x: 130, y: 250, s: 8.5, b: true, label: "一套程式，所有客戶共用" },
      // 收入成長
      { t: "group", x: 262, y: 12, w: 130, h: 150, label: "同客戶收入", c: "green" },
      { t: "path", d: "M272 140H384M272 140V36", c: "gray", w: 1 },
      { t: "rect", x: 280, y: 110, w: 18, h: 30, c: "blue", fill: 0.45 },
      { t: "rect", x: 306, y: 110, w: 18, h: 30, c: "blue", fill: 0.45 }, { t: "rect", x: 306, y: 98, w: 18, h: 12, c: "green", fill: 0.45 },
      { t: "rect", x: 332, y: 110, w: 18, h: 30, c: "blue", fill: 0.45 }, { t: "rect", x: 332, y: 98, w: 18, h: 12, c: "green", fill: 0.45 }, { t: "rect", x: 332, y: 84, w: 18, h: 14, c: "green", fill: 0.3 },
      { t: "rect", x: 358, y: 110, w: 18, h: 30, c: "blue", fill: 0.45 }, { t: "rect", x: 358, y: 98, w: 18, h: 12, c: "green", fill: 0.45 }, { t: "rect", x: 358, y: 84, w: 18, h: 14, c: "green", fill: 0.3 }, { t: "rect", x: 358, y: 68, w: 18, h: 16, c: "pink", fill: 0.4 },
      { t: "text", x: 289, y: 152, s: 7.5, label: "Y1", muted: true }, { t: "text", x: 315, y: 152, s: 7.5, label: "Y2", muted: true }, { t: "text", x: 341, y: 152, s: 7.5, label: "Y3", muted: true }, { t: "text", x: 367, y: 152, s: 7.5, label: "Y4", muted: true },
      { t: "text", x: 306, y: 50, s: 7.5, label: "越用越多＝", muted: true }, { t: "text", x: 306, y: 62, s: 7.5, label: "淨留存率", muted: true },
      // 訂閱循環
      { t: "box", x: 268, y: 178, w: 50, h: 26, label: "簽約", s: 8.5, c: "blue" },
      { t: "box", x: 336, y: 178, w: 50, h: 26, label: "導入使用", s: 8.5, c: "cyan" },
      { t: "box", x: 336, y: 224, w: 50, h: 26, label: "續約", s: 8.5, c: "green" },
      { t: "box", x: 268, y: 224, w: 50, h: 26, label: "加購模組", s: 8.5, c: "pink" },
      { t: "arrow", pts: [[318, 191], [334, 191]], c: "gray" }, { t: "arrow", pts: [[361, 204], [361, 222]], c: "gray" },
      { t: "arrow", pts: [[336, 237], [320, 237]], c: "gray" }, { t: "arrow", pts: [[293, 224], [293, 206]], c: "gray" },
      { t: "text", x: 327, y: 218, s: 7.5, label: "年年收", muted: true },
      // 細節：登入加密、租戶隔離、自動擴充、收入結構
      { t: "icon", x: 104, y: 34, s: 12, k: "lock", c: "blue" },
      { t: "text", x: 120, y: 44, s: 7, a: "start", label: "加密連線", muted: true },
      { t: "dots", x: 47, y: 35, w: 6, h: 13, n: 3, sz: 1.4, c: "blue" },
      { t: "path", d: "M71 151V167M121 151V167", c: "purple", w: 0.8, dash: true },
      { t: "callout", x: 71, y: 151, tx: 80, ty: 142, label: "邏輯隔離", c: "purple" },
      { t: "dots", x: 198, y: 148, w: 28, h: 16, n: 9, sz: 1.5, c: "purple" },
      { t: "rect", x: 122, y: 192, w: 26, h: 34, c: "gray", fill: 0.03, dash: true },
      { t: "text", x: 135, y: 213, s: 10, label: "＋", muted: true },
      { t: "dim", x1: 384, y1: 140, x2: 384, y2: 68, c: "green" },
      { t: "callout", x: 358, y: 76, tx: 354, ty: 77, label: "AI 加價", c: "pink", a: "end" },
      { t: "callout", x: 306, y: 104, tx: 302, ty: 92, label: "加購", c: "green", a: "end" },
      { t: "arrow", pts: [[376, 250], [376, 261]], c: "red", dash: true },
      { t: "text", x: 376, y: 272, s: 7.5, label: "少數流失", muted: true },
      { t: "legend", x: 14, y: 272, items: [["blue", "既有合約"], ["green", "加購擴張"], ["pink", "AI 加值"]] },
    ] },
    how: [
      ["在做什麼", "以前企業買軟體要一次付一大筆授權費、自己裝在機房；SaaS（軟體即服務）改成放在雲端，企業用瀏覽器登入就能用，按人數或用量每月、每年付訂閱費。"],
      ["怎麼運作", "軟體公司開發一套平台，很多客戶共用同一套程式與資料庫、資料彼此隔開（多租戶），平台通常跑在 AWS、Azure 等公有雲上；客戶先買一個模組，用順了再加購人數與其他模組，近年再加上 AI 代理功能另外收費。"],
      ["關鍵名詞", "ARR：年度經常性收入。淨留存率：老客戶今年比去年多付多少，超過 100% 代表老客戶越用越多。流失率：取消訂閱的比例。多租戶：所有客戶共用一套系統，維護成本低、毛利高。"],
      ["景氣看什麼", "企業 IT 預算、新客戶簽約與續約狀況、淨留存率、剩餘履約義務（已簽約未認列的收入）；也要看 AI 是否讓客戶需要的帳號數變少，或反過來帶來新的加購收入。"],
      ["代表公司", "Salesforce 與 HubSpot（CRM）、ServiceNow（IT 流程）、Workday（人資財務）、SAP 與甲骨文（ERP）、Adobe（創意軟體）、Intuit（會計報稅）；台灣上市公司多是代理或系統整合，較少大型 SaaS。"],
    ],
    trends: [
      "計價方式由按帳號收費，逐步加入按用量或按 AI 代理完成的工作量收費",
      "AI 代理直接在軟體裡處理客服、工單與報表，讓 SaaS 從工具變成能代替人做事",
      "客戶想減少供應商數量，大型平台靠整合多個模組與共用資料搶下更多預算",
      "資料與流程留在同一平台上，讓客戶轉換成本更高，續約與加購更穩定",
    ],
    chain: [
      { tier: "上游", title: "雲端與平台基礎", items: [
        { name: "公有雲基礎設施", desc: "提供伺服器、儲存與網路，多數 SaaS 跑在上面", c: [["AMZN", "亞馬遜", "AWS"], ["MSFT", "微軟", "Azure"], ["GOOGL", "Alphabet", "Google Cloud"]] },
        { name: "資料庫與開發平台", desc: "讓軟體存放客戶資料、在同一平台上開發新功能", c: [["ORCL", "甲骨文", "資料庫與雲端平台"], ["MSFT", "微軟", "資料庫與開發工具"]] },
      ] },
      { tier: "中游", title: "企業應用軟體", items: [
        { name: "CRM 客戶關係管理", desc: "管理業務、行銷與客服，記錄每位客戶的往來", c: [["CRM", "Salesforce", "CRM 平台"], ["HUBS", "HubSpot", "中小企業 CRM 與行銷"]] },
        { name: "IT 與流程管理", desc: "把 IT 維修、員工申請、客服工單做成自動化流程", c: [["NOW", "ServiceNow", "IT 與企業流程平台"]] },
        { name: "人資財務與 ERP", desc: "薪資、人事、會計、採購與庫存等企業核心系統", c: [["WDAY", "Workday", "人資與財務"], ["SAP", "SAP", "ERP"], ["ORCL", "甲骨文", "雲端 ERP"]] },
        { name: "創意與專業軟體", desc: "設計、文件、會計報稅等以訂閱制收費的專業工具", c: [["ADBE", "Adobe", "創意與文件軟體"], ["INTU", "Intuit", "會計與報稅"]] },
      ] },
      { tier: "下游", title: "AI 加值", items: [
        { name: "AI 助理與代理", desc: "在既有軟體裡加上能自動執行任務的 AI，另外收費", c: [["CRM", "Salesforce", "Agentforce"], ["NOW", "ServiceNow", "AI 代理"], ["MSFT", "微軟", "Copilot"]] },
      ] },
    ],
    peers: ["us-cloud"] },

  { id: "us-dataplat", mk: "us", cat: "軟體", name: "資料平台與可觀測性", icon: "server",
    desc: "資料平台幫企業把散在各處的資料集中、整理、查詢並拿去訓練 AI；可觀測性軟體則即時監控系統的日誌與指標，出事時第一時間告警。",
    flow: ["蒐集資料", "存進資料湖倉", "查詢分析", "AI 應用", "監控與告警"],
    segs: [{ n: "資料平台", c: [["SNOW", "Snowflake", "雲端資料倉儲"], ["MDB", "MongoDB", "文件型資料庫"], ["PLTR", "Palantir", "資料整合與分析平台"]] },
      { n: "可觀測性", c: [["DDOG", "Datadog", "雲端監控"], ["DT", "Dynatrace", "應用程式監控"], ["ESTC", "Elastic", "搜尋與日誌分析"]] }],
    fig: { w: 400, h: 280, alt: "資料平台：App、感測器與交易系統的資料匯入湖倉，從原始資料清洗成分析用表格，再拿去做報表、訓練 AI 與搜尋；下方的可觀測性軟體收集每台機器的日誌、指標與追蹤，超過閾值就告警", items: [
      // 資料來源
      { t: "icon", x: 16, y: 20, s: 20, k: "phone", c: "blue", label: "App" },
      { t: "icon", x: 16, y: 62, s: 20, k: "factory", c: "orange", label: "感測器" },
      { t: "icon", x: 16, y: 104, s: 20, k: "db", c: "cyan", label: "交易系統" },
      { t: "badge", x: 48, y: 100, n: 3, c: "cyan" },
      { t: "path", d: "M40 30H64V114H40M40 72H64", c: "gray", w: 1.2 },
      { t: "arrow", pts: [[64, 72], [98, 72]], c: "gray", label: "匯入", lx: 82, ly: 66 },
      // 湖倉
      { t: "group", x: 100, y: 16, w: 128, h: 150, label: "湖倉 Lakehouse", c: "blue" },
      { t: "rect", x: 112, y: 34, w: 104, h: 24, c: "orange", fill: 0.18 },
      { t: "text", x: 164, y: 50, s: 8.5, label: "原始資料" },
      { t: "arrow", pts: [[164, 58], [164, 68]], c: "gray" },
      { t: "rect", x: 112, y: 70, w: 104, h: 24, c: "gray", fill: 0.2 },
      { t: "text", x: 164, y: 86, s: 8.5, label: "清洗整理" },
      { t: "arrow", pts: [[164, 94], [164, 104]], c: "gray" },
      { t: "rect", x: 112, y: 106, w: 104, h: 24, c: "yellow", fill: 0.25 },
      { t: "text", x: 164, y: 122, s: 8.5, label: "分析用表格" },
      { t: "cyl", x: 134, y: 136, w: 60, h: 24, c: "blue" }, { t: "text", x: 164, y: 155, s: 7.5, label: "物件儲存", muted: true },
      { t: "badge", x: 228, y: 16, n: 2, c: "blue" },
      // 輸出
      { t: "arrow", pts: [[230, 46], [250, 42]], c: "green" },
      { t: "box", x: 252, y: 22, w: 66, h: 38, label: "SQL 報表", sub: "BI 儀表板", c: "green" },
      { t: "rect", x: 328, y: 44, w: 7, h: 14, c: "green", fill: 0.5 }, { t: "rect", x: 338, y: 36, w: 7, h: 22, c: "green", fill: 0.5 }, { t: "rect", x: 348, y: 30, w: 7, h: 28, c: "green", fill: 0.5 },
      { t: "arrow", pts: [[230, 96], [250, 99]], c: "purple" },
      { t: "box", x: 252, y: 80, w: 66, h: 38, label: "AI 模型", sub: "訓練・推論", c: "purple" },
      { t: "icon", x: 330, y: 86, s: 24, k: "robot", c: "purple" },
      { t: "badge", x: 252, y: 80, n: 5, c: "purple" },
      { t: "arrow", pts: [[230, 145], [250, 145]], c: "cyan" },
      { t: "box", x: 252, y: 130, w: 66, h: 30, label: "全文搜尋", s: 9, c: "cyan" },
      { t: "badge", x: 252, y: 130, n: 4, c: "cyan" },
      { t: "text", x: 358, y: 148, s: 7.5, label: "找日誌找文件", muted: true },
      // 雲端底座
      { t: "rect", x: 100, y: 172, w: 292, h: 18, c: "gray", fill: 0.1 },
      { t: "text", x: 246, y: 185, s: 8, label: "全部跑在 AWS・Azure・Google Cloud", muted: true },
      { t: "badge", x: 100, y: 181, n: 1, c: "orange" },
      // 可觀測性
      { t: "group", x: 8, y: 198, w: 384, h: 64, label: "可觀測性：監控每台機器", c: "red" },
      { t: "rack", x: 20, y: 218, w: 24, h: 38, n: 4, c: "gray" }, { t: "rack", x: 50, y: 218, w: 24, h: 38, n: 4, c: "gray" }, { t: "rack", x: 80, y: 218, w: 24, h: 38, n: 4, c: "gray" },
      { t: "circle", x: 44, y: 218, r: 3, c: "yellow", fill: 0.8 }, { t: "circle", x: 74, y: 218, r: 3, c: "yellow", fill: 0.8 }, { t: "circle", x: 104, y: 218, r: 3, c: "yellow", fill: 0.8 },
      { t: "arrow", pts: [[108, 224], [194, 224]], c: "orange" }, { t: "text", x: 116, y: 221, s: 7.5, a: "start", label: "日誌", muted: true },
      { t: "arrow", pts: [[108, 238], [194, 238]], c: "green" }, { t: "text", x: 116, y: 235, s: 7.5, a: "start", label: "指標", muted: true },
      { t: "arrow", pts: [[108, 252], [194, 252]], c: "cyan" }, { t: "text", x: 116, y: 249, s: 7.5, a: "start", label: "追蹤", muted: true },
      { t: "rect", x: 198, y: 210, w: 92, h: 46, c: "red", fill: 0.06 },
      { t: "path", d: "M204 234H286", c: "yellow", w: 1, dash: true },
      { t: "path", d: "M204 248L216 246L228 247L240 244L252 220L258 246L270 247L284 245", c: "red", w: 1.4 },
      { t: "badge", x: 198, y: 210, n: 6, c: "red" },
      { t: "arrow", pts: [[290, 233], [316, 233]], c: "red" },
      { t: "icon", x: 320, y: 220, s: 20, k: "person", c: "red" },
      { t: "text", x: 366, y: 236, s: 8, label: "通知工程師", muted: true },
      // 細節：資料由亂到整齊、即時串流、監控封包、根因分析
      { t: "dots", x: 68, y: 75, w: 26, h: 5, n: 4, sz: 1.5, c: "gray" },
      { t: "text", x: 67, y: 90, s: 7, a: "start", label: "即時串流", muted: true },
      { t: "grad", x: 104, y: 34, w: 4, h: 96, c: "orange", c2: "yellow", o: 0.7 },
      { t: "dots", x: 116, y: 38, w: 26, h: 16, n: 8, sz: 1.5, c: "orange" }, { t: "dots", x: 186, y: 38, w: 26, h: 16, n: 8, sz: 1.5, c: "orange" },
      { t: "path", d: "M118 74H136L129 82V90L125 88V82Z", c: "gray", fill: 0.3, w: 1 },
      { t: "rect", x: 115, y: 110, w: 22, h: 16, c: "yellow", fill: 0.15 },
      { t: "path", d: "M115 115.3H137M115 120.6H137M122 110V126M130 110V126", c: "yellow", w: 0.6 },
      { t: "text", x: 210, y: 152, s: 7, label: "低成本", muted: true },
      { t: "path", d: "M324 58.5H360", c: "gray", w: 1 },
      { t: "text", x: 342, y: 122, s: 7, label: "預測・生成", muted: true },
      { t: "stack", x: 328, y: 126, w: 22, h: 12, n: 3, c: "cyan" },
      { t: "text", x: 356, y: 135, s: 7, a: "start", label: "索引", muted: true },
      { t: "dots", x: 140, y: 222, w: 40, h: 4, n: 4, sz: 1.5, c: "orange" }, { t: "dots", x: 140, y: 236, w: 40, h: 4, n: 4, sz: 1.5, c: "green" }, { t: "dots", x: 140, y: 250, w: 40, h: 4, n: 4, sz: 1.5, c: "cyan" },
      { t: "callout", x: 252, y: 222, tx: 246, ty: 220, label: "超出閾值", c: "red", a: "end" },
      { t: "text", x: 206, y: 231, s: 7, a: "start", label: "閾值", muted: true },
      { t: "icon", x: 362, y: 241, s: 12, k: "phone", c: "red" },
      { t: "callout", x: 290, y: 250, tx: 300, ty: 258, label: "AI 協助找原因", c: "red" },
      { t: "legend", x: 14, y: 274, items: [["gray", "資料流"], ["yellow", "監控探針與閾值"], ["red", "異常告警"]] },
    ] },
    how: [
      ["在做什麼", "企業的資料散在交易系統、App、網站、感測器裡。資料平台把它們集中整理，讓人能查詢、做報表、訓練 AI；可觀測性軟體則盯著每台伺服器與程式，確保服務不當機。"],
      ["怎麼運作", "資料先匯入雲端的資料湖倉，從原始資料一步步清洗成分析用的表格，再用 SQL 查詢、做儀表板或拿去訓練模型。監控端則在每台伺服器裝探針，持續送出日誌、指標與追蹤紀錄，平台一發現數值超過閾值就通知工程師。"],
      ["關鍵名詞", "資料倉儲：整理好的結構化資料庫。資料湖：先存原始資料再說，兩者合稱湖倉。營運資料庫：App 即時讀寫用的資料庫。日誌（log）、指標（metric）、追蹤（trace）：可觀測性的三種訊號。"],
      ["景氣看什麼", "多數平台按用量計費，要看企業雲端用量是否成長、AI 專案帶來的資料量與查詢量；景氣差時客戶會先優化用量，營收成長就會放慢。"],
      ["代表公司", "Snowflake 做雲端資料倉儲，MongoDB 與甲骨文做資料庫，Palantir 做資料整合與 AI 決策平台，Elastic 做搜尋與日誌，Datadog、Dynatrace 做監控；它們大多跑在 AWS、Azure、Google Cloud 上。"],
    ],
    trends: [
      "資料倉儲與資料湖合併成湖倉架構，並採用開放的表格格式，讓不同引擎都能讀同一份資料",
      "AI 應用需要即時、乾淨的企業資料，資料平台加入向量搜尋與模型服務功能",
      "可觀測性由事後查問題走向用 AI 自動找出根因，並開始監控 AI 模型本身的表現",
      "按用量計費成為主流，客戶的雲端用量與優化節奏直接反映在營收上",
    ],
    chain: [
      { tier: "上游", title: "雲端基礎", items: [
        { name: "雲端基礎設施", desc: "提供運算、儲存與網路，資料平台與監控軟體都跑在上面", c: [["AMZN", "亞馬遜", "AWS"], ["MSFT", "微軟", "Azure"], ["GOOGL", "Alphabet", "Google Cloud"]] },
      ] },
      { tier: "中游", title: "資料儲存與查詢", items: [
        { name: "雲端資料倉儲與湖倉", desc: "集中存放並整理企業資料，提供 SQL 查詢與分析", c: [["SNOW", "Snowflake", "雲端資料倉儲"]] },
        { name: "營運資料庫", desc: "App 與交易系統即時讀寫資料的地方", c: [["MDB", "MongoDB", "文件型資料庫"], ["ORCL", "甲骨文", "關聯式資料庫"]] },
        { name: "搜尋與日誌分析", desc: "在大量文件與日誌裡快速找到需要的內容", c: [["ESTC", "Elastic", "搜尋與日誌分析"]] },
      ] },
      { tier: "下游", title: "分析、AI 與監控", items: [
        { name: "資料整合與 AI 決策", desc: "把各系統資料串起來，給企業與政府做分析與 AI 決策", c: [["PLTR", "Palantir", "資料整合與 AI 平台"]] },
        { name: "可觀測性", desc: "收集日誌、指標與追蹤，監控系統健康並即時告警", c: [["DDOG", "Datadog", "雲端監控"], ["DT", "Dynatrace", "應用程式監控"], ["ESTC", "Elastic", "日誌監控"]] },
      ] },
    ],
    peers: ["us-cloud"] },

  { id: "us-security", mk: "us", cat: "資安", name: "資安防護", icon: "code",
    desc: "保護企業的網路、帳號、電腦與雲端資料不被駭客入侵或勒索；從防火牆、身分驗證到端點防護層層把關，再由資安監控中心集中分析告警。",
    flow: ["網路防火牆", "身分驗證", "端點防護", "雲端安全", "監控與應變"],
    segs: [{ n: "平台與網路", c: [["PANW", "Palo Alto Networks", "防火牆與資安平台"], ["FTNT", "Fortinet", "防火牆設備"], ["CHKP", "Check Point", "防火牆"], ["NET", "Cloudflare", "網路安全與 CDN"]] },
      { n: "端點與身分", c: [["CRWD", "CrowdStrike", "端點防護"], ["ZS", "Zscaler", "雲端安全存取"], ["OKTA", "Okta", "身分驗證"]] }],
    fig: { w: 400, h: 280, alt: "資安縱深防禦：防火牆擋下惡意流量，遠端員工經雲端閘道連線，進門前要多因素驗證，每台電腦與雲端主機都有防護，所有告警送到資安監控中心由 AI 與分析師處置", items: [
      // 外部
      { t: "icon", x: 16, y: 38, s: 24, k: "person", c: "red", label: "駭客" },
      { t: "arrow", pts: [[42, 51], [110, 51]], c: "red", dash: true },
      { t: "path", d: "M90 45l10 10M100 45l-10 10", c: "red", w: 2.2 },
      { t: "text", x: 68, y: 68, s: 7.5, label: "擋下惡意流量", muted: true },
      { t: "icon", x: 70, y: 76, s: 24, k: "globe", c: "gray" },
      { t: "text", x: 82, y: 114, s: 7.5, label: "網際網路", muted: true },
      // 防火牆
      { t: "rect", x: 112, y: 26, w: 18, h: 70, c: "orange", fill: 0.25, r: 1 },
      { t: "path", d: "M112 40h18M112 54h18M112 68h18M112 82h18M121 26v14M117 40v14M125 40v14M121 54v14M117 68v14M125 68v14M121 82v14", c: "orange", w: 0.9 },
      { t: "text", x: 121, y: 20, s: 8, label: "防火牆", muted: true },
      { t: "badge", x: 140, y: 30, n: 1, c: "orange" },
      { t: "arrow", pts: [[94, 89], [158, 89]], c: "green" },
      // 遠端員工與 SASE
      { t: "icon", x: 14, y: 140, s: 24, k: "laptop", c: "green", label: "遠端員工" },
      { t: "arrow", pts: [[40, 152], [50, 152]], c: "green" },
      { t: "box", x: 52, y: 132, w: 62, h: 38, label: "SASE", sub: "雲端閘道", c: "cyan" },
      { t: "badge", x: 52, y: 132, n: 2, c: "cyan" },
      { t: "arrow", pts: [[114, 151], [158, 151]], c: "green" },
      // 身分驗證門
      { t: "rect", x: 160, y: 40, w: 40, h: 120, c: "yellow", fill: 0.12, r: 4 },
      { t: "icon", x: 168, y: 50, s: 24, k: "lock", c: "yellow" },
      { t: "icon", x: 170, y: 92, s: 20, k: "phone", c: "yellow" },
      { t: "text", x: 180, y: 128, s: 8, b: true, label: "MFA" },
      { t: "text", x: 180, y: 146, s: 7.5, label: "零信任", muted: true },
      { t: "badge", x: 200, y: 40, n: 3, c: "yellow" },
      { t: "arrow", pts: [[200, 100], [222, 100]], c: "green" },
      // 企業內部
      { t: "group", x: 214, y: 14, w: 178, h: 146, label: "企業內部與雲端", c: "blue" },
      { t: "icon", x: 228, y: 34, s: 24, k: "laptop", c: "blue" }, { t: "icon", x: 246, y: 52, s: 12, k: "shield", c: "green" },
      { t: "icon", x: 266, y: 34, s: 24, k: "laptop", c: "blue" }, { t: "icon", x: 284, y: 52, s: 12, k: "shield", c: "green" },
      { t: "rack", x: 304, y: 30, w: 24, h: 38, n: 4, c: "blue" }, { t: "icon", x: 324, y: 56, s: 12, k: "shield", c: "green" },
      { t: "badge", x: 350, y: 40, n: 4, c: "green" },
      { t: "text", x: 286, y: 86, s: 8, label: "每台裝 EDR 偵測", muted: true },
      { t: "rect", x: 230, y: 100, w: 40, h: 26, c: "red", fill: 0.08, dash: true },
      { t: "circle", x: 250, y: 113, r: 5, c: "red", fill: 0.5 },
      { t: "text", x: 250, y: 140, s: 7.5, label: "可疑程式隔離", muted: true },
      { t: "icon", x: 316, y: 96, s: 30, k: "cloud", c: "purple" },
      { t: "text", x: 331, y: 140, s: 7.5, label: "雲端設定檢查", muted: true },
      { t: "badge", x: 362, y: 100, n: 5, c: "purple" },
      // SOC
      { t: "arrow", pts: [[104, 170], [104, 200]], c: "gray", dash: true },
      { t: "arrow", pts: [[180, 160], [180, 198]], c: "gray", dash: true },
      { t: "arrow", pts: [[300, 160], [300, 172], [244, 172], [244, 198]], c: "gray", dash: true },
      { t: "group", x: 8, y: 184, w: 384, h: 74, label: "資安監控中心 SOC", c: "red" },
      { t: "text", x: 46, y: 224, s: 9, b: true, label: "SIEM" },
      { t: "text", x: 46, y: 238, s: 7.5, label: "收集所有告警", muted: true },
      { t: "rect", x: 128, y: 202, w: 124, h: 48, c: "red", fill: 0.06 },
      { t: "rect", x: 134, y: 208, w: 6, h: 5, c: "red", fill: 0.9, stroke: false }, { t: "rect", x: 144, y: 208, w: 80, h: 5, c: "gray", fill: 0.4, stroke: false },
      { t: "rect", x: 134, y: 217, w: 6, h: 5, c: "orange", fill: 0.9, stroke: false }, { t: "rect", x: 144, y: 217, w: 64, h: 5, c: "gray", fill: 0.4, stroke: false },
      { t: "rect", x: 134, y: 226, w: 6, h: 5, c: "yellow", fill: 0.9, stroke: false }, { t: "rect", x: 144, y: 226, w: 90, h: 5, c: "gray", fill: 0.4, stroke: false },
      { t: "rect", x: 134, y: 235, w: 6, h: 5, c: "gray", fill: 0.9, stroke: false }, { t: "rect", x: 144, y: 235, w: 54, h: 5, c: "gray", fill: 0.4, stroke: false },
      { t: "badge", x: 128, y: 202, n: 6, c: "red" },
      { t: "icon", x: 262, y: 204, s: 22, k: "robot", c: "purple" }, { t: "text", x: 273, y: 240, s: 7.5, label: "AI 先篩", muted: true },
      { t: "icon", x: 300, y: 204, s: 22, k: "person", c: "blue" }, { t: "text", x: 311, y: 240, s: 7.5, label: "分析師", muted: true },
      { t: "arrow", pts: [[326, 215], [340, 215]], c: "red" },
      { t: "box", x: 342, y: 202, w: 44, h: 28, label: "應變", s: 9, c: "green" },
      { t: "text", x: 364, y: 242, s: 7.5, label: "隔離・復原", muted: true },
      // 細節：封包、加密通道、端點、雲端設定、告警分級、自動處置
      { t: "dots", x: 46, y: 49, w: 38, h: 4, n: 4, sz: 1.6, c: "red" },
      { t: "dots", x: 133, y: 87, w: 22, h: 4, n: 3, sz: 1.6, c: "green" },
      { t: "text", x: 28, y: 84, s: 7, label: "勒索・釣魚", muted: true },
      { t: "callout", x: 170, y: 104, tx: 156, ty: 122, label: "密碼＋手機", c: "yellow", a: "end" },
      { t: "path", d: "M116 147H154M116 155H154", c: "cyan", w: 0.7 },
      { t: "text", x: 136, y: 143, s: 7, label: "加密通道", muted: true },
      { t: "callout", x: 328, y: 60, tx: 340, ty: 72, label: "伺服器", c: "blue" },
      { t: "hatch", x: 232, y: 102, w: 36, h: 22, c: "red", gap: 5, stroke: false },
      { t: "path", d: "M366 116H386M366 122H386M366 128H386", c: "gray", w: 1 },
      { t: "rect", x: 359, y: 114.5, w: 4, h: 3, c: "green", fill: 0.9, stroke: false }, { t: "rect", x: 359, y: 120.5, w: 4, h: 3, c: "red", fill: 0.9, stroke: false }, { t: "rect", x: 359, y: 126.5, w: 4, h: 3, c: "green", fill: 0.9, stroke: false },
      { t: "cyl", x: 76, y: 206, w: 22, h: 30, c: "red" },
      { t: "arrow", pts: [[98, 221], [126, 221]], c: "gray" },
      { t: "callout", x: 131, y: 237, tx: 124, ty: 252, label: "依嚴重度排序", c: "red", a: "end" },
      { t: "arrow", pts: [[378, 202], [378, 162]], c: "green", label: "自動處置", lx: 352, ly: 180 },
      { t: "legend", x: 14, y: 274, items: [["red", "攻擊"], ["green", "允許的連線"], ["gray", "告警回傳", true]] },
    ] },
    how: [
      ["在做什麼", "企業的帳號、電腦、伺服器和雲端資料都可能被駭客入侵、竊取或勒索加密。資安公司提供軟體和設備，在每一層把關，並在出事時快速找出、隔離問題。"],
      ["怎麼運作", "網路入口用防火牆過濾流量；在外地上班的員工改經雲端閘道（SASE）連線；登入時用多因素驗證確認身分；每台電腦與伺服器裝端點防護偵測異常程式；雲端再檢查設定與權限。各層告警送到資安監控中心，由 AI 先篩選、分析師判斷並隔離處置。"],
      ["關鍵名詞", "零信任：不因為在公司內網就信任，每次存取都要驗證。EDR：端點偵測與回應。SASE：把網路與資安服務搬到雲端。SIEM：集中收集與分析告警的系統。勒索軟體：把資料加密後要贖金。"],
      ["景氣看什麼", "重大資安事件（通常會帶動預算）、企業 IT 預算、法規要求、平台整合趨勢（客戶想少用幾家廠商），以及訂閱收入、續約率與新簽約金額。"],
      ["代表公司", "Palo Alto Networks、Fortinet、Check Point 做防火牆與平台，CrowdStrike、SentinelOne 做端點防護，Zscaler 與 Cloudflare 做雲端存取，Okta 做身分驗證，思科旗下的 Splunk 做告警分析。台灣也有資安股，但規模小很多。"],
    ],
    trends: [
      "客戶想減少資安供應商，平台型廠商把防火牆、端點、雲端與監控整合成一套賣",
      "攻擊者也用 AI 寫釣魚信與惡意程式，防守端用 AI 自動分析告警、縮短應變時間",
      "遠端辦公與雲端應用普及，防護重心由公司網路邊界轉向身分與雲端存取",
      "企業開始部署 AI 代理，如何管理 AI 的帳號權限與資料存取成為新的資安需求",
    ],
    chain: [
      { tier: "上游", title: "網路邊界", items: [
        { name: "新世代防火牆", desc: "在網路入口檢查每一筆流量，擋下惡意連線與攻擊", c: [["PANW", "Palo Alto Networks", "防火牆與資安平台"], ["FTNT", "Fortinet", "防火牆與安全晶片"], ["CHKP", "Check Point", "防火牆"]] },
        { name: "雲端安全存取（SASE）", desc: "員工在任何地方上網都先經過雲端節點檢查", c: [["ZS", "Zscaler", "雲端安全存取"], ["NET", "Cloudflare", "網路安全與 CDN"], ["PANW", "Palo Alto Networks", "Prisma SASE"]] },
      ] },
      { tier: "中游", title: "身分與端點", items: [
        { name: "身分驗證", desc: "確認登入的人是本人，管理誰能存取哪些系統", c: [["OKTA", "Okta", "身分驗證與單一登入"], ["MSFT", "微軟", "Entra 身分管理"]] },
        { name: "端點防護（EDR）", desc: "在每台電腦與伺服器上偵測異常程式並隔離", c: [["CRWD", "CrowdStrike", "端點防護平台"], ["S", "SentinelOne", "端點防護"], ["MSFT", "微軟", "Defender"]] },
      ] },
      { tier: "下游", title: "雲端與監控應變", items: [
        { name: "雲端安全", desc: "檢查雲端主機與帳號的設定、權限與漏洞", c: [["PANW", "Palo Alto Networks", "Prisma Cloud"], ["CRWD", "CrowdStrike", "雲端工作負載防護"]] },
        { name: "資安監控與應變（SOC）", desc: "集中收集告警、分析事件並指揮處置", c: [["CSCO", "思科", "旗下 Splunk SIEM"], ["PANW", "Palo Alto Networks", "Cortex 監控平台"], ["CRWD", "CrowdStrike", "託管偵測與應變"]] },
      ] },
    ] },

  { id: "us-itservice", mk: "us", cat: "軟體", name: "系統整合與委外", icon: "link",
    desc: "幫企業規劃、導入並維運資訊系統的顧問與委外公司，把新舊系統、雲端與 AI 串在一起；靠大量工程師的人力與多年合約賺錢。",
    flow: ["顧問規劃", "系統整合", "導入雲端與 AI", "委外維運", "長期續約"],
    segs: [{ n: "顧問與整合", c: [["ACN", "Accenture", "全球最大 IT 顧問之一"], ["IBM", "IBM", "顧問與混合雲"]] },
      { n: "委外與開發", c: [["CTSH", "Cognizant", "IT 委外"], ["INFY", "Infosys", "印度 IT 委外"], ["EPAM", "EPAM Systems", "軟體開發外包"]] }],
    fig: { w: 400, h: 280, alt: "IT 服務：一個轉型專案從顧問規劃、設計、建置整合到上線後轉成多年委外維運，人力在建置期最多；整合層把舊主機與 ERP、CRM、雲端 AI 串起來；少數顧問在客戶端、多數工程師在離岸交付中心", items: [
      // 專案時程
      { t: "path", d: "M10 22h64l10 14-10 14h-64l10-14z", c: "purple", fill: 0.18 },
      { t: "path", d: "M86 22h64l10 14-10 14h-64l10-14z", c: "blue", fill: 0.18 },
      { t: "path", d: "M162 22h64l10 14-10 14h-64l10-14z", c: "cyan", fill: 0.18 },
      { t: "path", d: "M238 22h64l10 14-10 14h-64l10-14z", c: "green", fill: 0.18 },
      { t: "path", d: "M314 22h64l10 14-10 14h-64l10-14z", c: "orange", fill: 0.18 },
      { t: "text", x: 47, y: 39, s: 8.5, b: true, label: "顧問規劃" }, { t: "text", x: 123, y: 39, s: 8.5, b: true, label: "系統設計" },
      { t: "text", x: 199, y: 39, s: 8.5, b: true, label: "建置整合" }, { t: "text", x: 275, y: 39, s: 8.5, b: true, label: "上線切換" },
      { t: "text", x: 351, y: 39, s: 8.5, b: true, label: "委外維運" },
      { t: "badge", x: 14, y: 18, n: 2, c: "purple" }, { t: "badge", x: 166, y: 18, n: 3, c: "cyan" }, { t: "badge", x: 318, y: 18, n: 5, c: "orange" },
      { t: "rect", x: 38, y: 74, w: 18, h: 6, c: "purple", fill: 0.45 },
      { t: "rect", x: 114, y: 66, w: 18, h: 14, c: "blue", fill: 0.45 },
      { t: "rect", x: 190, y: 56, w: 18, h: 24, c: "cyan", fill: 0.45 },
      { t: "rect", x: 266, y: 64, w: 18, h: 16, c: "green", fill: 0.45 },
      { t: "rect", x: 342, y: 68, w: 18, h: 12, c: "orange", fill: 0.45 },
      { t: "path", d: "M10 80H390", c: "gray", w: 0.8 },
      { t: "text", x: 10, y: 66, s: 7.5, a: "start", label: "投入人力", muted: true },
      { t: "text", x: 370, y: 62, s: 7.5, label: "多年合約", muted: true },
      // 系統整合
      { t: "group", x: 8, y: 94, w: 250, h: 96, label: "把新舊系統串起來", c: "blue" },
      { t: "rack", x: 20, y: 112, w: 30, h: 46, n: 5, c: "gray", label: "舊主機" },
      { t: "path", d: "M50 141H98", c: "cyan", w: 1.6 },
      { t: "box", x: 100, y: 124, w: 64, h: 34, label: "整合層", sub: "API・資料", c: "cyan" },
      { t: "badge", x: 100, y: 124, n: 3, c: "cyan" },
      { t: "path", d: "M164 141H180V118H196M180 141H196M180 141V170H196", c: "cyan", w: 1.4 },
      { t: "box", x: 196, y: 108, w: 52, h: 20, label: "ERP", s: 8.5, c: "orange" },
      { t: "box", x: 196, y: 131, w: 52, h: 20, label: "CRM", s: 8.5, c: "blue" },
      { t: "box", x: 196, y: 160, w: 52, h: 20, label: "雲端 AI", s: 8.5, c: "purple" },
      { t: "badge", x: 248, y: 108, n: 1, c: "blue" },
      // 收費
      { t: "group", x: 268, y: 94, w: 124, h: 96, label: "怎麼收費", c: "green" },
      { t: "icon", x: 278, y: 112, s: 16, k: "person", c: "green" }, { t: "icon", x: 294, y: 112, s: 16, k: "person", c: "green" }, { t: "icon", x: 310, y: 112, s: 16, k: "person", c: "green" },
      { t: "text", x: 362, y: 124, s: 8, label: "人天計價" },
      { t: "icon", x: 282, y: 140, s: 20, k: "coin", c: "yellow" },
      { t: "text", x: 362, y: 154, s: 8, label: "固定總價" },
      { t: "text", x: 330, y: 182, s: 7.5, label: "簽約金額＝領先指標", muted: true },
      // 交付模式
      { t: "icon", x: 18, y: 208, s: 26, k: "bank", c: "blue", label: "企業・政府" },
      { t: "badge", x: 52, y: 208, n: 6, c: "blue" },
      { t: "arrow", pts: [[50, 230], [84, 230]], c: "gray" },
      { t: "path", d: "M120 204L170 256H70z", c: "purple", fill: 0.12 },
      { t: "path", d: "M103 222H137M86 239H154", c: "purple", w: 1 },
      { t: "text", x: 120, y: 219, s: 7.5, label: "顧問" }, { t: "text", x: 120, y: 236, s: 7.5, label: "架構師" }, { t: "text", x: 120, y: 252, s: 7.5, label: "工程師" },
      { t: "badge", x: 66, y: 250, n: 4, c: "purple" },
      { t: "arrow", pts: [[160, 238], [194, 226]], c: "green" },
      { t: "icon", x: 196, y: 210, s: 28, k: "globe", c: "green", label: "離岸交付中心" },
      { t: "badge", x: 232, y: 210, n: 5, c: "green" },
      { t: "text", x: 312, y: 222, s: 8, label: "印度・東歐工程師" },
      { t: "text", x: 312, y: 236, s: 7.5, label: "人數多、成本較低", muted: true },
      // 細節：人力曲線、收入性質、資料轉換、交付分工
      { t: "path", d: "M47 74L123 66L199 56L275 64L351 68", c: "gray", w: 0.9, dash: true },
      { t: "dim", x1: 10, y1: 90, x2: 310, y2: 90, label: "建置專案：一次性收入", c: "purple", ly: -2.5 },
      { t: "dim", x1: 314, y1: 90, x2: 388, y2: 90, label: "維運：年年續約", c: "orange", ly: -2.5 },
      { t: "dots", x: 56, y: 139, w: 38, h: 4, n: 4, sz: 1.5, c: "cyan" },
      { t: "path", d: "M192 116h4v4h-4zM192 139h4v4h-4zM192 168h4v4h-4z", c: "cyan", fill: 0.8, w: 0.8 },
      { t: "callout", x: 44, y: 120, tx: 58, ty: 118, label: "老舊系統", c: "gray" },
      { t: "callout", x: 132, y: 158, tx: 132, ty: 172, label: "資料格式轉換", c: "cyan", a: "middle" },
      { t: "text", x: 362, y: 135, s: 7, label: "工時×費率", muted: true },
      { t: "text", x: 362, y: 165, s: 7, label: "超支自己吸收", muted: true },
      { t: "text", x: 120, y: 200, s: 7, label: "客戶現場團隊", muted: true },
      { t: "callout", x: 124, y: 214, tx: 148, ty: 210, label: "單價高", c: "purple" },
      { t: "callout", x: 150, y: 250, tx: 176, ty: 262, label: "人數最多", c: "purple" },
      { t: "icon", x: 288, y: 196, s: 12, k: "laptop", c: "green" }, { t: "icon", x: 304, y: 196, s: 12, k: "laptop", c: "green" }, { t: "icon", x: 320, y: 196, s: 12, k: "laptop", c: "green" },
      { t: "text", x: 312, y: 250, s: 7.5, label: "跨時區接力開發", muted: true },
      { t: "path", d: "M82 52l3 3-3 3-3-3zM158 52l3 3-3 3-3-3zM234 52l3 3-3 3-3-3zM310 52l3 3-3 3-3-3z", c: "yellow", fill: 0.8, w: 0.8 },
      { t: "path", d: "M226 216Q256 200 284 202", c: "green", w: 0.9, dash: true },
      { t: "legend", x: 14, y: 274, items: [["purple", "顧問"], ["cyan", "整合"], ["green", "離岸交付"], ["orange", "維運"], ["yellow", "里程碑驗收"]] },
    ] },
    how: [
      ["在做什麼", "大企業的系統往往新舊混雜，自己沒有足夠工程師。IT 服務公司幫忙規劃要怎麼改、把 ERP、CRM、雲端、資料和 AI 串在一起，之後再接手長期維運。"],
      ["怎麼運作", "專案從顧問規劃、系統設計開始，建置整合期投入最多人力，上線後常轉成多年委外維運合約。整合層用 API 把舊主機和新系統接起來；少數顧問在客戶端，大量工程師放在印度、東歐等成本較低的離岸交付中心。"],
      ["關鍵名詞", "系統整合（SI）：把不同廠商的系統接起來。委外（outsourcing）：把 IT 工作整包交給外部公司。人天計價與固定總價：兩種收費方式。簽約金額（bookings）：未來營收的領先指標。"],
      ["景氣看什麼", "企業是否願意花錢做轉型專案、新簽約金額、員工使用率與人力成本、匯率；也要留意 AI 寫程式工具是否會減少按人力計價的工作量，或反過來帶來新的 AI 導入專案。"],
      ["代表公司", "Accenture、IBM 偏顧問與大型整合，Cognizant、Infosys、Wipro 偏離岸委外與維運，EPAM、Globant 做軟體開發外包，Booz Allen、Leidos 服務美國政府。台灣的系統整合商規模較小，多服務本地企業與政府。"],
    ],
    trends: [
      "企業導入生成式 AI 需要整合資料與流程，帶來新的顧問與系統整合專案",
      "AI 寫程式工具提高工程師產能，收費方式由按人力計價轉向按成果或固定總價",
      "大型專案集中在雲端遷移、ERP 升級與資料平台，IT 服務商與軟體平台深度合作",
      "交付中心持續往成本較低的地區分散，同時保留少數高階顧問在客戶當地",
    ],
    chain: [
      { tier: "上游", title: "平台與顧問", items: [
        { name: "雲端與企業軟體平台", desc: "被導入與整合的雲端、ERP、CRM 與 IT 流程軟體", c: [["MSFT", "微軟", "Azure 與企業軟體"], ["SAP", "SAP", "ERP"], ["NOW", "ServiceNow", "IT 流程平台"]] },
        { name: "策略與技術顧問", desc: "了解企業需求、規劃轉型藍圖與系統架構", c: [["ACN", "Accenture", "策略與技術顧問"], ["IBM", "IBM", "IBM Consulting"]] },
      ] },
      { tier: "中游", title: "建置與交付", items: [
        { name: "系統整合", desc: "把新舊系統、資料與雲端串接起來並導入上線", c: [["ACN", "Accenture", "大型系統整合"], ["IBM", "IBM", "混合雲整合"], ["DXC", "DXC Technology", "系統整合與維運"]] },
        { name: "軟體開發外包", desc: "替客戶開發客製化軟體、App 與數位產品", c: [["EPAM", "EPAM Systems", "軟體開發外包"], ["GLOB", "Globant", "數位產品開發"]] },
        { name: "離岸委外與維運", desc: "以離岸交付中心長期負責系統維護與升級", c: [["INFY", "Infosys", "印度 IT 委外"], ["CTSH", "Cognizant", "IT 委外"], ["WIT", "Wipro", "印度 IT 委外"]] },
      ] },
      { tier: "下游", title: "客戶", items: [
        { name: "政府與國防 IT", desc: "替政府機關與國防單位建置與維運資訊系統", c: [["BAH", "Booz Allen Hamilton", "政府顧問與 IT"], ["LDOS", "Leidos", "政府與國防 IT"]] },
      ] },
    ] },

  { id: "us-telecom", mk: "us", cat: "網通", name: "電信與數位媒體", icon: "wave",
    desc: "電信業者鋪設基地台與光纖收取每月通話與寬頻費，現金流穩定但投資龐大；數位媒體則製作內容，透過串流平台賺取訂閱與廣告收入。",
    flow: ["鋪設網路", "用戶月費", "內容製作", "串流平台", "訂閱與廣告"],
    segs: [{ n: "電信與寬頻", c: [["TMUS", "T-Mobile US", "行動通訊"], ["VZ", "Verizon", "行動與光纖"], ["T", "AT&T", "行動與光纖"], ["CMCSA", "Comcast", "有線寬頻與 NBC"]] },
      { n: "串流媒體", c: [["NFLX", "Netflix", "影音串流"], ["DIS", "迪士尼", "內容與串流"], ["SPOT", "Spotify", "音樂串流"]] }],
    fig: { w: 400, h: 280, alt: "電信與媒體：核心網路經光纖接到鐵塔上的 5G 基地台與家用寬頻，用戶每月付月費；串流平台把製作好的內容送到電視與手機，收訂閱費與廣告費；電信先投資後回收，串流靠會員成長攤平內容成本", items: [
      // 電信網路
      { t: "group", x: 8, y: 14, w: 236, h: 150, label: "電信網路", c: "blue" },
      { t: "rack", x: 20, y: 34, w: 28, h: 52, n: 5, c: "blue", label: "核心網路" },
      { t: "path", d: "M48 58H112", c: "yellow", w: 2.4 },
      { t: "path", d: "M48 76H80V130H150", c: "yellow", w: 2.4 },
      { t: "text", x: 80, y: 52, s: 7.5, label: "光纖", muted: true },
      { t: "icon", x: 108, y: 30, s: 40, k: "tower", c: "gray" },
      { t: "rect", x: 135, y: 38, w: 6, h: 11, c: "orange", fill: 0.7 },
      { t: "path", d: "M150 36a14 14 0 0 1 0 20M157 30a22 22 0 0 1 0 32", c: "cyan", w: 1.4 },
      { t: "badge", x: 108, y: 30, n: 2, c: "gray" },
      { t: "badge", x: 132, y: 26, n: 1, c: "orange" },
      { t: "text", x: 128, y: 84, s: 7.5, label: "5G 基地台", muted: true },
      { t: "text", x: 172, y: 84, s: 7.5, label: "頻譜", muted: true },
      { t: "icon", x: 182, y: 32, s: 20, k: "phone", c: "blue" }, { t: "icon", x: 204, y: 40, s: 20, k: "phone", c: "blue" },
      { t: "badge", x: 230, y: 32, n: 3, c: "blue" },
      { t: "icon", x: 150, y: 116, s: 26, k: "house", c: "green" },
      { t: "text", x: 163, y: 154, s: 7.5, label: "家用寬頻", muted: true },
      { t: "icon", x: 190, y: 118, s: 20, k: "wifi", c: "green" },
      { t: "badge", x: 224, y: 128, n: 4, c: "green" },
      { t: "icon", x: 20, y: 112, s: 22, k: "coin", c: "yellow" },
      { t: "text", x: 31, y: 148, s: 7.5, label: "每月收月費", muted: true },
      // 數位媒體
      { t: "group", x: 256, y: 14, w: 136, h: 150, label: "數位媒體", c: "pink" },
      { t: "icon", x: 266, y: 36, s: 24, k: "camera", c: "pink", label: "內容製作" },
      { t: "badge", x: 298, y: 36, n: 5, c: "pink" },
      { t: "arrow", pts: [[306, 50], [318, 50]], c: "pink" },
      { t: "box", x: 320, y: 30, w: 64, h: 32, label: "串流平台", s: 9, c: "purple" },
      { t: "badge", x: 384, y: 30, n: 6, c: "purple" },
      { t: "arrow", pts: [[352, 62], [352, 82]], c: "purple" },
      { t: "rect", x: 322, y: 84, w: 60, h: 36, c: "gray", fill: 0.15 },
      { t: "path", d: "M346 94l12 8-12 8z", c: "purple", fill: 0.5 },
      { t: "path", d: "M346 124h12", c: "gray", w: 2 },
      { t: "box", x: 262, y: 88, w: 44, h: 22, label: "訂閱費", s: 8, c: "green" },
      { t: "box", x: 262, y: 118, w: 44, h: 22, label: "廣告", s: 8, c: "orange" },
      { t: "arrow", pts: [[320, 99], [308, 99]], c: "green" },
      { t: "arrow", pts: [[320, 114], [308, 126]], c: "orange" },
      { t: "text", x: 336, y: 152, s: 7.5, label: "會員數×月費", muted: true },
      // 商業模式比較
      { t: "group", x: 8, y: 176, w: 186, h: 84, label: "電信：先投資後回收", c: "blue" },
      { t: "path", d: "M20 218H184M20 192V254", c: "gray", w: 1 },
      { t: "path", d: "M20 218C40 240 60 248 80 246C110 240 140 214 182 196", c: "blue", w: 1.8 },
      { t: "text", x: 60, y: 210, s: 7.5, label: "建網・買頻譜", muted: true },
      { t: "text", x: 150, y: 236, s: 7.5, label: "月費回收", muted: true },
      { t: "group", x: 206, y: 176, w: 186, h: 84, label: "串流：會員攤平成本", c: "pink" },
      { t: "path", d: "M218 252H384", c: "gray", w: 1 },
      { t: "rect", x: 226, y: 222, w: 12, h: 30, c: "red", fill: 0.35 }, { t: "rect", x: 240, y: 232, w: 12, h: 20, c: "green", fill: 0.45 },
      { t: "rect", x: 266, y: 218, w: 12, h: 34, c: "red", fill: 0.35 }, { t: "rect", x: 280, y: 220, w: 12, h: 32, c: "green", fill: 0.45 },
      { t: "rect", x: 306, y: 216, w: 12, h: 36, c: "red", fill: 0.35 }, { t: "rect", x: 320, y: 208, w: 12, h: 44, c: "green", fill: 0.45 },
      { t: "rect", x: 346, y: 214, w: 12, h: 38, c: "red", fill: 0.35 }, { t: "rect", x: 360, y: 196, w: 12, h: 56, c: "green", fill: 0.45 },
      // 細節：光纖剖面、到府、CDN、損益兩平
      { t: "dots", x: 54, y: 56, w: 30, h: 4, n: 4, sz: 1.5, c: "yellow" },
      { t: "circle", x: 112, y: 104, r: 9, c: "yellow", fill: 0.15 },
      { t: "circle", x: 112, y: 104, r: 3, c: "cyan", fill: 0.8 },
      { t: "callout", x: 112, y: 104, tx: 126, ty: 100, label: "纖芯傳光", c: "cyan" },
      { t: "text", x: 112, y: 124, s: 7, label: "光纖剖面", muted: true },
      { t: "callout", x: 40, y: 42, tx: 58, ty: 38, label: "交換・計費", c: "blue", s: 7 },
      { t: "text", x: 205, y: 70, s: 7, label: "手機用戶", muted: true },
      { t: "callout", x: 120, y: 130, tx: 104, ty: 146, label: "光纖到府", c: "yellow", a: "end" },
      { t: "rect", x: 190, y: 141, w: 20, h: 6, c: "green", fill: 0.3 },
      { t: "dots", x: 192, y: 143, w: 16, h: 2, n: 3, sz: 0.9, c: "green" },
      { t: "rack", x: 326, y: 64, w: 14, h: 18, n: 3, c: "purple" },
      { t: "text", x: 322, y: 76, s: 7, a: "end", label: "CDN", muted: true },
      { t: "rect", x: 328, y: 112, w: 48, h: 2, c: "gray", fill: 0.4, stroke: false },
      { t: "rect", x: 328, y: 112, w: 20, h: 2, c: "red", fill: 0.9, stroke: false },
      { t: "path", d: "M20 218C40 240 60 248 80 246C100 243 122 232 141 218Z", c: "red", fill: 0.15, stroke: false },
      { t: "path", d: "M141 218C155 210 168 203 182 196V218Z", c: "green", fill: 0.15, stroke: false },
      { t: "callout", x: 141, y: 218, tx: 141, ty: 202, label: "損益兩平", c: "blue", a: "middle" },
      { t: "text", x: 186, y: 228, s: 7, a: "end", label: "時間", muted: true },
      { t: "path", d: "M246 232L286 220L326 208L366 196", c: "green", w: 1, dash: true },
      { t: "callout", x: 232, y: 222, tx: 222, ty: 206, label: "內容先花錢", c: "red", a: "start" },
      { t: "callout", x: 366, y: 196, tx: 340, ty: 196, label: "規模攤平", c: "green", a: "end" },
      { t: "legend", x: 14, y: 274, items: [["yellow", "光纖"], ["green", "訂閱與廣告收入"], ["red", "內容成本"]] },
    ] },
    how: [
      ["在做什麼", "電信公司蓋基地台、拉光纖，把手機和家裡連上網路，每月收通話與上網費；數位媒體公司拍影集、買體育轉播權，放上串流平台賺訂閱費和廣告費。"],
      ["怎麼運作", "電信要先花大錢買頻譜、在鐵塔上裝 5G 基地台、把光纖拉進社區，之後靠數千萬用戶的月費慢慢回收，所以現金流穩、配息常見。串流平台則是先砸錢做內容吸引會員，會員夠多後內容成本被攤平，再漲價、加廣告方案。"],
      ["關鍵名詞", "ARPU：每個用戶平均每月貢獻多少錢。流失率：退租或退訂的比例。頻譜：政府拍賣的無線電頻段。鐵塔公司：把鐵塔空間出租給多家電信的業者。廣告方案：較便宜但會插廣告的訂閱等級。"],
      ["景氣看什麼", "電信看用戶淨增加數、資本支出與負債、價格競爭與光纖覆蓋；媒體看訂閱人數、漲價後是否流失、廣告市場景氣，以及熱門內容與體育轉播權的成本。"],
      ["代表公司", "設備有愛立信、諾基亞、思科，鐵塔有 American Tower、Crown Castle、SBA；電信有 T-Mobile、Verizon、AT&T，有線寬頻有 Comcast、Charter；串流有 Netflix、迪士尼、Spotify。台灣對應的是三大電信與網通設備廠。"],
    ],
    trends: [
      "電信業者加速把光纖拉到家，並用 5G 固定無線寬頻搶有線寬頻的用戶",
      "行動與寬頻綁約銷售成為主流，用戶同時用多項服務時流失率較低",
      "串流平台由搶會員數轉向追求獲利，靠漲價、廣告方案與打擊共用帳號提高 ARPU",
      "體育直播轉向串流平台，內容版權競爭從影集延伸到運動賽事",
    ],
    chain: [
      { tier: "上游", title: "網路設備與基礎設施", items: [
        { name: "基地台與網通設備", desc: "5G 基地台、核心網路與路由交換設備", c: [["ERIC", "愛立信", "基地台與核心網路"], ["NOK", "諾基亞", "基地台與光通訊"], ["CSCO", "思科", "路由與交換設備"]] },
        { name: "鐵塔與通訊基礎設施", desc: "建鐵塔、小型基地台，出租給多家電信公司掛設備", c: [["AMT", "American Tower", "通訊鐵塔"], ["CCI", "Crown Castle", "鐵塔與光纖"], ["SBAC", "SBA Communications", "通訊鐵塔"]] },
      ] },
      { tier: "中游", title: "電信營運商", items: [
        { name: "行動通訊", desc: "經營 4G／5G 行動網路，收手機門號月費", c: [["TMUS", "T-Mobile US", "行動通訊"], ["VZ", "Verizon", "行動與光纖"], ["T", "AT&T", "行動與光纖"]] },
        { name: "有線與光纖寬頻", desc: "把網路拉進家庭與企業，收寬頻月費", c: [["CMCSA", "Comcast", "有線寬頻"], ["CHTR", "Charter Communications", "有線寬頻"], ["VZ", "Verizon", "Fios 光纖"]] },
      ] },
      { tier: "下游", title: "內容與串流", items: [
        { name: "內容製作與版權", desc: "拍攝影集電影、取得體育轉播權，建立片庫", c: [["DIS", "迪士尼", "影視內容與體育"], ["CMCSA", "Comcast", "NBC 環球影業"]] },
        { name: "串流平台", desc: "把影音內容送到用戶裝置，收訂閱費與廣告費", c: [["NFLX", "Netflix", "影音串流"], ["DIS", "迪士尼", "Disney+ 串流"], ["SPOT", "Spotify", "音樂串流"]] },
      ] },
    ] },

  { id: "us-adtech", mk: "us", cat: "網路平台", name: "數位廣告 AdTech", icon: "globe",
    desc: "網路廣告的買賣系統：廣告主透過買方平台出價，媒體透過賣方平台提供版位，在不到一秒內完成即時競價；Google、Meta 等平台則在自家生態內一手包辦。",
    flow: ["廣告主預算", "買方平台 DSP", "即時競價", "媒體版位", "成效數據回饋"],
    segs: [{ n: "封閉平台", c: [["GOOGL", "Alphabet", "搜尋與 YouTube 廣告"], ["META", "Meta", "社群廣告"], ["AMZN", "亞馬遜", "電商廣告"]] },
      { n: "開放網路廣告", c: [["TTD", "The Trade Desk", "買方平台 DSP"], ["APP", "AppLovin", "行動 App 廣告"], ["MGNI", "Magnite", "賣方平台 SSP"]] }],
    fig: { w: 400, h: 280, alt: "即時競價：使用者打開網頁，賣方平台把廣告版位送進競價，多個買方平台替廣告主出價，最高價得標的廣告顯示在頁面上，成效數據再回饋調整出價；下方是一手包辦的封閉生態與聯網電視、零售媒體、App 等新版位", items: [
      // 網頁與版位
      { t: "text", x: 49, y: 14, s: 7.5, label: "使用者開網頁", muted: true },
      { t: "rect", x: 14, y: 20, w: 70, h: 92, c: "gray", fill: 0.08, r: 4 },
      { t: "rect", x: 14, y: 20, w: 70, h: 9, c: "gray", fill: 0.4, r: 2 },
      { t: "path", d: "M22 38h54M22 46h46M22 54h50M22 62h38", c: "gray", w: 1 },
      { t: "rect", x: 22, y: 70, w: 54, h: 26, c: "orange", fill: 0.2, dash: true },
      { t: "text", x: 49, y: 86, s: 7.5, label: "廣告版位" },
      { t: "path", d: "M22 102h40", c: "gray", w: 1 },
      // SSP
      { t: "arrow", pts: [[76, 83], [102, 83]], c: "orange" },
      { t: "box", x: 104, y: 64, w: 58, h: 38, label: "SSP", sub: "賣方平台", c: "orange" },
      { t: "badge", x: 104, y: 64, n: 4, c: "orange" },
      { t: "arrow", pts: [[162, 83], [178, 83]], c: "orange" },
      // 競價
      { t: "text", x: 213, y: 48, s: 7.5, label: "零點幾秒內完成", muted: true },
      { t: "rect", x: 180, y: 56, w: 66, h: 52, c: "yellow", fill: 0.1, r: 5 },
      { t: "text", x: 213, y: 70, s: 8.5, b: true, label: "即時競價" },
      { t: "rect", x: 188, y: 78, w: 22, h: 6, c: "blue", fill: 0.5, stroke: false },
      { t: "rect", x: 188, y: 87, w: 44, h: 6, c: "green", fill: 0.8, stroke: false },
      { t: "rect", x: 188, y: 96, w: 32, h: 6, c: "blue", fill: 0.5, stroke: false },
      { t: "path", d: "M246 82H258V38H272M258 82H272M258 82V122H272", c: "blue", w: 1.4 },
      { t: "box", x: 274, y: 26, w: 50, h: 24, label: "DSP A", s: 8.5, c: "blue" },
      { t: "box", x: 274, y: 70, w: 50, h: 24, label: "DSP B", s: 8.5, c: "green" },
      { t: "box", x: 274, y: 110, w: 50, h: 24, label: "DSP C", s: 8.5, c: "blue" },
      { t: "badge", x: 324, y: 70, n: 3, c: "green" },
      // 廣告主與衡量
      { t: "icon", x: 348, y: 30, s: 24, k: "factory", c: "purple", label: "廣告主" },
      { t: "arrow", pts: [[346, 50], [326, 58]], c: "purple" },
      { t: "badge", x: 384, y: 30, n: 1, c: "purple" },
      { t: "icon", x: 348, y: 96, s: 22, k: "eye", c: "cyan", label: "成效衡量" },
      { t: "arrow", pts: [[346, 110], [326, 118]], c: "cyan", dash: true },
      { t: "badge", x: 384, y: 98, n: 2, c: "cyan" },
      // 得標廣告送回頁面
      { t: "arrow", pts: [[213, 108], [213, 142], [49, 142], [49, 98]], c: "green" },
      { t: "text", x: 130, y: 156, s: 7.5, label: "得標廣告顯示在頁面", muted: true },
      // 封閉生態
      { t: "group", x: 8, y: 168, w: 200, h: 92, label: "封閉生態：自己一手包", c: "blue" },
      { t: "box", x: 16, y: 186, w: 58, h: 26, label: "搜尋影音", s: 8, c: "red" },
      { t: "box", x: 80, y: 186, w: 56, h: 26, label: "社群", s: 8, c: "blue" },
      { t: "box", x: 142, y: 186, w: 58, h: 26, label: "電商", s: 8, c: "orange" },
      { t: "rect", x: 16, y: 220, w: 184, h: 30, c: "blue", fill: 0.1 },
      { t: "text", x: 108, y: 239, s: 8, label: "自有用戶＋廣告系統＋資料" },
      { t: "badge", x: 208, y: 168, n: 6, c: "blue" },
      // 新版位
      { t: "group", x: 220, y: 168, w: 172, h: 92, label: "成長中的新版位", c: "purple" },
      { t: "rect", x: 232, y: 190, w: 40, h: 26, c: "gray", fill: 0.15 },
      { t: "path", d: "M246 220h12", c: "gray", w: 2 },
      { t: "text", x: 252, y: 234, s: 7.5, label: "聯網電視", muted: true },
      { t: "icon", x: 290, y: 190, s: 26, k: "truck", c: "orange" },
      { t: "text", x: 303, y: 234, s: 7.5, label: "零售媒體", muted: true },
      { t: "badge", x: 324, y: 190, n: 7, c: "orange" },
      { t: "icon", x: 346, y: 190, s: 26, k: "phone", c: "green" },
      { t: "text", x: 359, y: 234, s: 7.5, label: "手遊 App", muted: true },
      { t: "badge", x: 380, y: 190, n: 5, c: "green" },
      { t: "text", x: 306, y: 252, s: 7.5, label: "ROAS＝廣告帶回的營收", muted: true },
      // 細節：出價請求、各家出價、錢怎麼流、封閉生態的資料
      { t: "dots", x: 18, y: 22, w: 12, h: 5, n: 3, sz: 1.2, c: "gray" },
      { t: "icon", x: 88, y: 24, s: 12, k: "person", c: "gray" },
      { t: "text", x: 116, y: 56, s: 7, a: "start", label: "帶版位與受眾資訊", muted: true },
      { t: "text", x: 214, y: 84, s: 7, a: "start", label: "A", muted: true }, { t: "text", x: 236, y: 93, s: 7, a: "start", label: "B", muted: true }, { t: "text", x: 224, y: 102, s: 7, a: "start", label: "C", muted: true },
      { t: "dots", x: 260, y: 36, w: 10, h: 4, n: 2, sz: 1.3, c: "blue" }, { t: "dots", x: 260, y: 80, w: 10, h: 4, n: 2, sz: 1.3, c: "green" }, { t: "dots", x: 260, y: 120, w: 10, h: 4, n: 2, sz: 1.3, c: "blue" },
      { t: "callout", x: 230, y: 90, tx: 224, ty: 156, label: "最高價得標", c: "green" },
      { t: "text", x: 299, y: 20, s: 7, label: "演算法自動出價", muted: true },
      { t: "cyl", x: 340, y: 70, w: 18, h: 16, c: "blue" },
      { t: "text", x: 362, y: 82, s: 7, a: "start", label: "受眾資料", muted: true },
      { t: "text", x: 360, y: 140, s: 7, label: "點擊・購買", muted: true },
      { t: "arrow", pts: [[270, 128], [88, 128]], c: "yellow", dash: true, label: "廣告費一路往回付", lx: 150, ly: 124 },
      { t: "callout", x: 244, y: 128, tx: 250, ty: 142, label: "各層抽成", c: "yellow", s: 7 },
      { t: "text", x: 194, y: 180, s: 7, a: "end", label: "圍牆花園", muted: true },
      { t: "path", d: "M45 212V220M108 212V220M171 212V220", c: "blue", w: 1.2 },
      { t: "icon", x: 22, y: 228, s: 14, k: "lock", c: "blue" },
      { t: "dots", x: 166, y: 224, w: 30, h: 22, n: 9, sz: 1.5, c: "blue" },
      { t: "path", d: "M248 197l8 6-8 6z", c: "purple", fill: 0.6, w: 1 },
      { t: "callout", x: 303, y: 206, tx: 318, ty: 224, label: "購買資料", c: "orange", s: 7 },
      { t: "legend", x: 14, y: 274, items: [["orange", "賣方（媒體）"], ["blue", "買方出價"], ["green", "得標廣告"]] },
    ] },
    how: [
      ["在做什麼", "你打開網頁或 App 看到的廣告，大多是在你載入頁面的瞬間，由很多廣告主自動出價搶來的。AdTech 就是讓這場買賣自動化、精準化的系統。"],
      ["怎麼運作", "媒體把版位放上賣方平台（SSP）；廣告主把預算和目標客群設定在買方平台（DSP）；使用者一打開頁面，SSP 送出競價請求，多個 DSP 在零點幾秒內出價，最高價的廣告顯示在頁面上，之後的點擊與購買數據再回饋去調整出價。"],
      ["關鍵名詞", "DSP／SSP：買方與賣方平台。程式化購買：用系統自動買廣告。封閉生態：Google、Meta、亞馬遜自己有用戶、廣告系統和資料。ROAS：每花 1 元廣告帶回多少營收。零售媒體：電商與零售商用購物資料賣廣告。"],
      ["景氣看什麼", "整體廣告預算（跟景氣和消費高度相關）、AI 讓廣告投放更準的效果、隱私規則變化（例如追蹤限制），以及聯網電視、零售媒體等新版位的成長。"],
      ["代表公司", "Alphabet、Meta、亞馬遜是封閉生態的大廣告平台；The Trade Desk 是獨立買方平台，Magnite、PubMatic 是賣方平台，AppLovin 專攻手機遊戲與 App 廣告，Roku 經營聯網電視廣告，DoubleVerify 做廣告成效與品牌安全驗證。"],
    ],
    trends: [
      "AI 自動產生廣告素材並決定出價與投放對象，廣告主只需設定預算與目標",
      "瀏覽器與手機限制追蹤，擁有第一方登入與購物資料的平台更有優勢",
      "電視收視轉向串流，聯網電視成為程式化廣告成長最快的新版位之一",
      "零售商與外送平台用自家購物資料賣廣告，零售媒體成為新的廣告預算來源",
    ],
    chain: [
      { tier: "上游", title: "廣告主與衡量", items: [
        { name: "廣告主與代理商", desc: "決定廣告預算、目標客群與素材，代理商代為規劃投放", c: [["OMC", "Omnicom", "廣告代理集團"]] },
        { name: "成效衡量與驗證", desc: "檢查廣告是否真的被看到、出現在安全的內容旁", c: [["DV", "DoubleVerify", "廣告驗證與衡量"]] },
      ] },
      { tier: "中游", title: "程式化交易平台", items: [
        { name: "買方平台（DSP）", desc: "替廣告主在各家媒體自動出價購買版位", c: [["TTD", "The Trade Desk", "獨立買方平台"], ["AMZN", "亞馬遜", "Amazon DSP"]] },
        { name: "賣方平台（SSP）", desc: "替媒體把版位送進競價，賣到最好的價格", c: [["MGNI", "Magnite", "賣方平台"], ["PUBM", "PubMatic", "賣方平台"]] },
        { name: "行動 App 廣告", desc: "替手機遊戲與 App 買量，並用 AI 決定投放", c: [["APP", "AppLovin", "行動廣告平台"]] },
      ] },
      { tier: "下游", title: "媒體與版位", items: [
        { name: "封閉生態平台", desc: "自己擁有用戶、廣告系統與資料，一手包辦買賣", c: [["GOOGL", "Alphabet", "搜尋與 YouTube 廣告"], ["META", "Meta", "社群廣告"], ["AMZN", "亞馬遜", "電商廣告"]] },
        { name: "聯網電視與零售媒體", desc: "串流電視與零售商的購物資料帶來的新廣告版位", c: [["ROKU", "Roku", "聯網電視平台"], ["WMT", "沃爾瑪", "零售媒體廣告"], ["AMZN", "亞馬遜", "Prime Video 與零售廣告"]] },
      ] },
    ] },

  { id: "us-exchange", mk: "us", cat: "金融", name: "交易所與金融資料", icon: "link",
    desc: "股票、期貨、選擇權的交易所負責撮合買賣並收手續費，同時把即時報價、指數與信用評級賣給全世界的金融機構，資料授權收入越來越重要。",
    flow: ["投資人下單", "券商送單", "交易所撮合", "結算交割", "資料與指數授權"],
    segs: [{ n: "交易所", c: [["ICE", "洲際交易所", "紐約證交所與期貨"], ["CME", "CME Group", "期貨與選擇權"], ["NDAQ", "Nasdaq", "交易所與金融軟體"], ["CBOE", "Cboe Global Markets", "選擇權"]] },
      { n: "資料、指數與評級", c: [["SPGI", "標普全球", "指數與信用評級"], ["MCO", "穆迪", "信用評級"], ["MSCI", "MSCI", "指數與分析工具"]] }],
    fig: { w: 400, h: 280, alt: "交易所：投資人經券商下單，交易所的撮合引擎把買單與賣單依價格與時間配對成交，結算所站在買賣雙方中間完成交割；成交產生的報價、指數與評級再包裝成資料產品授權出去", items: [
      // 投資人與券商
      { t: "icon", x: 12, y: 26, s: 18, k: "person", c: "gray" }, { t: "icon", x: 12, y: 56, s: 18, k: "person", c: "gray" }, { t: "icon", x: 12, y: 86, s: 18, k: "person", c: "gray" },
      { t: "text", x: 22, y: 120, s: 7.5, label: "投資人", muted: true },
      { t: "path", d: "M31 35L44 56M31 65H44M31 95L44 80", c: "gray", w: 1.2 },
      { t: "box", x: 44, y: 46, w: 54, h: 44, label: "券商", sub: "下單・造市", c: "blue" },
      { t: "badge", x: 44, y: 46, n: 3, c: "blue" },
      { t: "arrow", pts: [[98, 68], [126, 68]], c: "blue" },
      // 撮合引擎
      { t: "group", x: 120, y: 14, w: 150, h: 136, label: "交易所撮合引擎", c: "purple" },
      { t: "badge", x: 270, y: 14, n: 1, c: "purple" },
      { t: "text", x: 168, y: 50, s: 8, label: "賣單", c: "red" },
      { t: "rect", x: 196, y: 32, w: 44, h: 7, c: "red", fill: 0.4 }, { t: "rect", x: 196, y: 42, w: 32, h: 7, c: "red", fill: 0.4 },
      { t: "rect", x: 196, y: 52, w: 24, h: 7, c: "red", fill: 0.4 }, { t: "rect", x: 196, y: 62, w: 14, h: 7, c: "red", fill: 0.6 },
      { t: "path", d: "M134 74H262", c: "yellow", w: 1, dash: true },
      { t: "circle", x: 204, y: 74, r: 4, c: "yellow", fill: 0.9 },
      { t: "text", x: 244, y: 71, s: 7.5, label: "成交", c: "yellow" },
      { t: "rect", x: 196, y: 79, w: 16, h: 7, c: "green", fill: 0.6 }, { t: "rect", x: 196, y: 89, w: 26, h: 7, c: "green", fill: 0.4 },
      { t: "rect", x: 196, y: 99, w: 34, h: 7, c: "green", fill: 0.4 }, { t: "rect", x: 196, y: 109, w: 44, h: 7, c: "green", fill: 0.4 },
      { t: "text", x: 168, y: 100, s: 8, label: "買單", c: "green" },
      { t: "path", d: "M192 32V116", c: "gray", w: 1 },
      { t: "text", x: 196, y: 130, s: 7.5, label: "股票・期貨・選擇權", muted: true },
      { t: "text", x: 196, y: 143, s: 7.5, label: "價格優先・時間優先", muted: true },
      { t: "badge", x: 140, y: 126, n: 2, c: "purple" },
      // 結算
      { t: "arrow", pts: [[196, 150], [196, 174]], c: "gray" },
      { t: "text", x: 202, y: 166, s: 7.5, a: "start", label: "成交後交割", muted: true },
      { t: "box", x: 150, y: 176, w: 92, h: 40, label: "結算所", sub: "站在買賣中間", c: "orange" },
      { t: "badge", x: 150, y: 176, n: 4, c: "orange" },
      { t: "box", x: 40, y: 182, w: 64, h: 28, label: "買方券商", s: 8, c: "green" },
      { t: "box", x: 288, y: 182, w: 64, h: 28, label: "賣方券商", s: 8, c: "red" },
      { t: "arrow", pts: [[104, 190], [148, 190]], c: "green" }, { t: "arrow", pts: [[148, 204], [104, 204]], c: "blue" },
      { t: "arrow", pts: [[288, 190], [244, 190]], c: "blue" }, { t: "arrow", pts: [[244, 204], [288, 204]], c: "green" },
      { t: "text", x: 196, y: 230, s: 7.5, label: "收保證金・擔保違約", muted: true },
      // 資料與授權
      { t: "arrow", pts: [[270, 60], [290, 60]], c: "cyan" },
      { t: "group", x: 282, y: 14, w: 110, h: 150, label: "資料與授權", c: "cyan" },
      { t: "wave", x: 294, y: 48, w: 40, n: 3, a: 3, c: "cyan" },
      { t: "text", x: 364, y: 51, s: 8, label: "即時報價" },
      { t: "badge", x: 384, y: 32, n: 7, c: "cyan" },
      { t: "icon", x: 294, y: 66, s: 22, k: "chart", c: "green" },
      { t: "text", x: 364, y: 82, s: 8, label: "指數" },
      { t: "text", x: 337, y: 102, s: 7.5, label: "ETF 付授權費", muted: true },
      { t: "badge", x: 384, y: 70, n: 5, c: "green" },
      { t: "box", x: 292, y: 112, w: 30, h: 18, label: "AAA", s: 7.5, c: "green" },
      { t: "box", x: 326, y: 112, w: 24, h: 18, label: "BB", s: 7.5, c: "orange" },
      { t: "text", x: 372, y: 124, s: 8, label: "評級" },
      { t: "badge", x: 298, y: 148, n: 6, c: "orange" },
      { t: "text", x: 346, y: 152, s: 7.5, label: "發債要評級", muted: true },
      { t: "text", x: 200, y: 254, s: 8.5, b: true, label: "波動大、成交多＝交易所旺季" },
      // 細節：委託簿價格、價差、低延遲、交割擔保、成交量
      { t: "text", x: 188, y: 38, s: 7, a: "end", label: "價高", muted: true },
      { t: "text", x: 188, y: 116, s: 7, a: "end", label: "價低", muted: true },
      { t: "callout", x: 214, y: 76, tx: 236, ty: 90, label: "價差", c: "yellow", s: 7 },
      { t: "rack", x: 52, y: 98, w: 20, h: 24, n: 3, c: "blue" },
      { t: "callout", x: 72, y: 104, tx: 80, ty: 116, label: "低延遲連線", c: "blue", s: 7 },
      { t: "text", x: 106, y: 62, s: 7, label: "交易費", muted: true },
      { t: "dots", x: 272, y: 58, w: 14, h: 4, n: 3, sz: 1.3, c: "cyan" },
      { t: "grad", x: 292, y: 133, w: 58, h: 3, c: "green", c2: "red", dir: "h", o: 0.8 },
      { t: "hatch", x: 110, y: 220, w: 34, h: 14, c: "orange", label: "違約基金" },
      { t: "text", x: 72, y: 222, s: 7, label: "美股 T+1 交割", muted: true },
      { t: "cyl", x: 252, y: 220, w: 26, h: 16, c: "orange" },
      { t: "text", x: 282, y: 232, s: 7, a: "start", label: "保證金", muted: true },
      { t: "text", x: 312, y: 228, s: 7, a: "start", label: "成交量與波動", muted: true },
      { t: "rect", x: 316, y: 254, w: 8, h: 8, c: "blue", fill: 0.4 }, { t: "rect", x: 328, y: 248, w: 8, h: 14, c: "blue", fill: 0.4 }, { t: "rect", x: 340, y: 240, w: 8, h: 22, c: "blue", fill: 0.4 },
      { t: "rect", x: 352, y: 250, w: 8, h: 12, c: "blue", fill: 0.4 }, { t: "rect", x: 364, y: 244, w: 8, h: 18, c: "blue", fill: 0.4 },
      { t: "path", d: "M312 262H378", c: "gray", w: 1 },
      { t: "path", d: "M320 248L332 240L344 232L356 244L368 236", c: "red", w: 1 },
      { t: "legend", x: 14, y: 274, items: [["green", "資金"], ["blue", "股票／部位"], ["red", "賣單"], ["cyan", "資料"]] },
    ] },
    how: [
      ["在做什麼", "交易所是買賣雙方見面的市場，負責把買單和賣單配對成交；它和指數、評級公司也把市場上產生的報價、指數和信用資訊包裝成資料產品，賣給基金和銀行。"],
      ["怎麼運作", "投資人透過券商下單，交易所的撮合引擎依「價格優先、時間優先」把最高買價與最低賣價配對成交；成交後由結算所站在買賣雙方中間，收保證金並確保錢和股票（或期貨部位）真的交割。過程中產生的即時報價、成交資料再賣給各金融機構。"],
      ["關鍵名詞", "撮合：把買賣單配對。買賣價差：最高買價與最低賣價的差距。結算所：站在買賣中間保證交割。造市商：持續掛出買賣報價提供流動性。指數授權：ETF 追蹤某個指數就要付費給指數公司。信用評級：替公司與債券的違約風險打分數。"],
      ["景氣看什麼", "市場成交量與波動度（波動大時交易多）、利率期貨等避險需求、ETF 資產規模（影響指數授權費）、企業發債量（影響評級收入），以及資料訂閱的續約與漲價。"],
      ["代表公司", "洲際交易所（旗下紐約證交所）、CME（期貨）、Nasdaq、Cboe（選擇權）；標普全球、穆迪、MSCI 做指數與評級，FactSet 做金融資料；嘉信、Robinhood、盈透是券商，Virtu 是造市商。台灣對應的是臺灣證交所與期交所。"],
    ],
    trends: [
      "交易所收入由交易手續費轉向資料、指數授權與軟體等經常性收入",
      "散戶選擇權交易熱絡，短天期合約的成交量明顯放大",
      "交易所延長交易時段、朝 24 小時交易發展，並推出代幣化資產等新商品",
      "主動式與被動式 ETF 持續成長，指數公司的授權收入跟著資產規模增加",
    ],
    chain: [
      { tier: "上游", title: "交易所", items: [
        { name: "股票與選擇權交易所", desc: "撮合股票、ETF 與選擇權買賣，收交易與上市費", c: [["ICE", "洲際交易所", "紐約證交所"], ["NDAQ", "Nasdaq", "股票交易所"], ["CBOE", "Cboe Global Markets", "選擇權交易所"]] },
        { name: "期貨交易所", desc: "提供利率、股價指數、原物料等期貨合約的交易", c: [["CME", "CME Group", "期貨與選擇權"], ["ICE", "洲際交易所", "能源與利率期貨"]] },
      ] },
      { tier: "中游", title: "券商與結算", items: [
        { name: "券商與造市", desc: "接受投資人下單，造市商持續提供買賣報價", c: [["SCHW", "嘉信理財", "券商"], ["HOOD", "Robinhood", "線上券商"], ["IBKR", "Interactive Brokers", "國際券商"], ["VIRT", "Virtu Financial", "造市商"]] },
        { name: "結算與交割", desc: "站在買賣雙方中間收保證金、確保交割完成", c: [["CME", "CME Group", "CME 結算所"], ["ICE", "洲際交易所", "ICE 結算所"]] },
      ] },
      { tier: "下游", title: "資料、指數與評級", items: [
        { name: "指數授權", desc: "編製股價指數，向追蹤指數的 ETF 與基金收授權費", c: [["SPGI", "標普全球", "標普道瓊指數"], ["MSCI", "MSCI", "全球股票指數"], ["NDAQ", "Nasdaq", "Nasdaq-100 指數"]] },
        { name: "信用評級", desc: "替公司與債券評估違約風險，發債時通常需要評級", c: [["SPGI", "標普全球", "標普信評"], ["MCO", "穆迪", "穆迪信評"]] },
        { name: "金融資料與分析", desc: "把即時報價、財務資料與分析工具賣給金融機構", c: [["FDS", "FactSet", "金融資料平台"], ["ICE", "洲際交易所", "資料服務"], ["MCO", "穆迪", "Moody's Analytics"]] },
      ] },
    ] },

  { id: "us-altasset", mk: "us", cat: "金融", name: "另類資產與私募信貸", icon: "layers",
    desc: "向退休基金、保險公司與富裕個人募資，投資未上市公司、直接放款給企業、買不動產與基礎建設（含資料中心），收取管理費與績效分成。",
    flow: ["向出資人募資", "成立基金", "投資或放款", "管理與退出", "收管理費與分成"],
    segs: [{ n: "另類資產管理", c: [["BX", "Blackstone", "私募股權、不動產"], ["KKR", "KKR", "私募股權與基礎建設"], ["APO", "Apollo", "私募信貸與保險"], ["ARES", "Ares Management", "私募信貸"], ["BAM", "Brookfield Asset Management", "基礎建設與再生能源"], ["OWL", "Blue Owl", "私募信貸、資料中心融資"]] }],
    fig: { w: 400, h: 280, alt: "另類資產：退休基金、保險公司與富裕個人出資給管理公司成立的基金，基金投資私募股權、放款、不動產與資料中心等基礎建設，回收的現金先還出資人本金與報酬，超額獲利再由管理公司抽績效分成", items: [
      // 出資人
      { t: "text", x: 40, y: 16, s: 8, b: true, label: "出資人 LP" },
      { t: "icon", x: 16, y: 26, s: 22, k: "bank", c: "blue", label: "退休基金" },
      { t: "icon", x: 16, y: 72, s: 22, k: "shield", c: "blue", label: "保險公司" },
      { t: "badge", x: 48, y: 76, n: 1, c: "blue" },
      { t: "icon", x: 16, y: 118, s: 22, k: "person", c: "blue", label: "富裕個人" },
      { t: "arrow", pts: [[40, 37], [94, 64]], c: "blue" },
      { t: "arrow", pts: [[58, 84], [94, 84]], c: "blue" },
      { t: "arrow", pts: [[40, 129], [94, 104]], c: "blue" },
      { t: "box", x: 12, y: 162, w: 70, h: 30, label: "上市 BDC", sub: "散戶買信貸", s: 8.5, c: "blue" },
      { t: "badge", x: 82, y: 162, n: 6, c: "blue" },
      // GP 與基金
      { t: "box", x: 100, y: 10, w: 84, h: 26, label: "管理公司 GP", s: 8.5, c: "pink" },
      { t: "arrow", pts: [[142, 50], [142, 38]], c: "pink" },
      { t: "text", x: 96, y: 30, s: 7.5, a: "end", label: "收管理費＋分成", muted: true },
      { t: "rect", x: 96, y: 50, w: 92, h: 70, c: "purple", fill: 0.1, r: 5 },
      { t: "text", x: 142, y: 64, s: 9, b: true, label: "私募基金" },
      { t: "text", x: 142, y: 76, s: 7.5, label: "資金鎖定多年", muted: true },
      { t: "path", d: "M104 96H182", c: "gray", w: 0.8 },
      { t: "path", d: "M104 96C114 112 126 112 138 102C150 92 166 86 182 82", c: "purple", w: 1.6 },
      // 投資標的
      { t: "line", pts: [[188, 85], [210, 85]], c: "purple" },
      { t: "line", pts: [[210, 37], [210, 169]], c: "purple" },
      { t: "arrow", pts: [[210, 37], [230, 37]], c: "purple" }, { t: "arrow", pts: [[210, 81], [230, 81]], c: "purple" },
      { t: "arrow", pts: [[210, 125], [230, 125]], c: "purple" }, { t: "arrow", pts: [[210, 169], [230, 169]], c: "purple" },
      { t: "box", x: 232, y: 20, w: 70, h: 34, label: "私募股權", sub: "買下公司", c: "purple" },
      { t: "box", x: 232, y: 64, w: 70, h: 34, label: "私募信貸", sub: "直接放款", c: "blue" },
      { t: "box", x: 232, y: 108, w: 70, h: 34, label: "不動產", sub: "收租", c: "orange" },
      { t: "box", x: 232, y: 152, w: 70, h: 34, label: "基礎建設", sub: "資料中心・電力", c: "green" },
      { t: "badge", x: 232, y: 20, n: 2, c: "purple" }, { t: "badge", x: 232, y: 64, n: 3, c: "blue" },
      { t: "badge", x: 232, y: 108, n: 4, c: "orange" }, { t: "badge", x: 232, y: 152, n: 5, c: "green" },
      { t: "icon", x: 310, y: 26, s: 22, k: "factory", c: "purple" },
      { t: "icon", x: 310, y: 70, s: 22, k: "coin", c: "blue" },
      { t: "icon", x: 310, y: 114, s: 22, k: "house", c: "orange" },
      { t: "rack", x: 310, y: 154, w: 22, h: 30, n: 4, c: "green" },
      { t: "path", d: "M336 37H360M336 81H360M336 125H360M336 169H360", c: "green", w: 1.2 },
      { t: "arrow", pts: [[360, 37], [360, 218]], c: "green" },
      { t: "text", x: 378, y: 100, s: 7.5, label: "回收", muted: true }, { t: "text", x: 378, y: 112, s: 7.5, label: "現金", muted: true },
      // 分配
      { t: "group", x: 8, y: 198, w: 384, h: 64, label: "回收的錢怎麼分（由右往左）", c: "green" },
      { t: "box", x: 300, y: 220, w: 84, h: 30, label: "出售・利息・租金", s: 8, c: "green" },
      { t: "arrow", pts: [[300, 235], [290, 235]], c: "green" },
      { t: "box", x: 204, y: 220, w: 84, h: 30, label: "先還 LP 本金", s: 8, c: "blue" },
      { t: "arrow", pts: [[204, 235], [194, 235]], c: "green" },
      { t: "box", x: 108, y: 220, w: 84, h: 30, label: "再給保底報酬", s: 8, c: "blue" },
      { t: "arrow", pts: [[108, 235], [98, 235]], c: "green" },
      { t: "box", x: 12, y: 220, w: 84, h: 30, label: "超額獲利分成", s: 8, c: "pink" },
      // 細節：J 曲線、分次撥款、各類資產怎麼賺、出場、分配順序
      { t: "path", d: "M104 96C114 112 126 112 138 102C141 99.5 143.5 97.6 146 96Z", c: "red", fill: 0.18, stroke: false },
      { t: "path", d: "M146 96C160 89 170 85 182 82V96Z", c: "green", fill: 0.18, stroke: false },
      { t: "callout", x: 128, y: 108, tx: 150, ty: 112, label: "J 曲線", c: "purple", s: 7 },
      { t: "icon", x: 168, y: 54, s: 12, k: "lock", c: "purple" },
      { t: "dim", x1: 96, y1: 128, x2: 188, y2: 128, label: "先投資、後收成", c: "purple", ly: 9 },
      { t: "text", x: 76, y: 76, s: 7, label: "分次撥款", muted: true },
      { t: "dots", x: 64, y: 82, w: 22, h: 4, n: 3, sz: 1.4, c: "blue" },
      { t: "text", x: 150, y: 46, s: 7, a: "start", label: "GP 也跟投", muted: true },
      { t: "text", x: 331, y: 59, s: 7, label: "槓桿收購", muted: true },
      { t: "text", x: 321, y: 103, s: 7, label: "收利息", muted: true },
      { t: "text", x: 321, y: 147, s: 7, label: "倉儲・公寓", muted: true },
      { t: "text", x: 321, y: 194, s: 7, label: "長約收費", muted: true },
      { t: "dots", x: 358, y: 150, w: 4, h: 60, n: 4, sz: 1.6, c: "green" },
      { t: "text", x: 364, y: 130, s: 7, a: "start", b: true, label: "出場：", muted: true },
      { t: "text", x: 364, y: 141, s: 7, a: "start", label: "上市", muted: true },
      { t: "text", x: 364, y: 152, s: 7, a: "start", label: "轉賣", muted: true },
      { t: "text", x: 88, y: 182, s: 7, a: "start", label: "每天可買賣", muted: true },
      { t: "grad", x: 12, y: 213, w: 372, h: 3, c: "pink", c2: "green", dir: "h", o: 0.7 },
      { t: "text", x: 342, y: 258, s: 7, label: "現金流入", muted: true }, { t: "text", x: 246, y: 258, s: 7, label: "最優先", muted: true },
      { t: "text", x: 150, y: 258, s: 7, label: "門檻報酬", muted: true }, { t: "text", x: 54, y: 258, s: 7, label: "GP 績效分成", muted: true },
      { t: "legend", x: 14, y: 274, items: [["blue", "出資人的錢"], ["purple", "投資出去"], ["green", "回收現金"], ["pink", "GP 收入"]] },
    ] },
    how: [
      ["在做什麼", "退休基金、保險公司和有錢人想找股票、公債以外的投資。另類資產管理公司替他們成立基金，去買未上市公司、直接放款給企業、買不動產和資料中心等基礎建設。"],
      ["怎麼運作", "管理公司（GP）向出資人（LP）募資成立基金，資金常鎖定好幾年；投資後慢慢改善公司、收租或收利息，最後賣出或到期回收。回收的錢先還出資人本金和約定的保底報酬，超額獲利再由 GP 抽績效分成；另外 GP 每年也收管理費。"],
      ["關鍵名詞", "私募股權：買下或入股未上市公司。私募信貸：不透過銀行、直接借錢給企業。AUM：管理資產規模。永續資本：保險資金等不用定期還給出資人的長期資金。BDC：在股市掛牌、專門放款給中型企業的投資公司。"],
      ["景氣看什麼", "募資速度與 AUM 成長、利率（影響信貸收益與資產估值）、併購與 IPO 市場是否熱絡（決定能不能順利退出）、私募信貸的違約率，以及資料中心與電力基礎建設的融資需求。"],
      ["代表公司", "Blackstone、KKR、Apollo、Ares、Carlyle、Brookfield、Blue Owl 是代表業者；Apollo 旗下 Athene、KKR 旗下 Global Atlantic 提供保險資金；Ares Capital、Blue Owl Capital Corp 是上市 BDC。台灣的壽險公司與退休基金也是這類基金常見的出資人。"],
    ],
    trends: [
      "資產管理公司併購或成立保險公司，用保單資金當長期、穩定的永續資本",
      "銀行放款受監管限制，私募信貸接手更多企業貸款與資產擔保融資",
      "AI 資料中心與電力建設需要龐大資金，另類資產公司成為主要的出資與放款者",
      "產品逐步開放給一般投資人，透過半流動基金、BDC 與退休帳戶募資",
    ],
    chain: [
      { tier: "上游", title: "資金來源", items: [
        { name: "保險與永續資本", desc: "旗下保險公司把保單資金交給集團長期投資", c: [["APO", "Apollo", "旗下 Athene 保險"], ["KKR", "KKR", "旗下 Global Atlantic 保險"], ["BN", "Brookfield Corporation", "旗下保險與財富業務"]] },
      ] },
      { tier: "中游", title: "另類資產管理（GP）", items: [
        { name: "私募股權", desc: "買下或入股未上市公司，改善經營後出售", c: [["BX", "Blackstone", "私募股權"], ["KKR", "KKR", "私募股權"], ["CG", "Carlyle", "私募股權"]] },
        { name: "私募信貸", desc: "不經銀行，直接放款給企業並收取利息", c: [["ARES", "Ares Management", "私募信貸"], ["APO", "Apollo", "私募信貸"], ["OWL", "Blue Owl", "私募信貸"], ["BX", "Blackstone", "私募信貸"]] },
        { name: "不動產", desc: "買進倉儲、公寓、辦公室等收租資產", c: [["BX", "Blackstone", "不動產基金"], ["BAM", "Brookfield Asset Management", "不動產"]] },
        { name: "基礎建設與資料中心", desc: "投資資料中心、電力、再生能源與交通基礎建設", c: [["BAM", "Brookfield Asset Management", "基礎建設與再生能源"], ["KKR", "KKR", "基礎建設"], ["BX", "Blackstone", "資料中心"], ["OWL", "Blue Owl", "資料中心融資"]] },
      ] },
      { tier: "下游", title: "散戶也能參與", items: [
        { name: "上市 BDC", desc: "在股市掛牌的放款投資公司，把利息大多配給股東", c: [["ARCC", "Ares Capital", "上市 BDC"], ["OBDC", "Blue Owl Capital Corp", "上市 BDC"]] },
      ] },
    ] },

  { id: "us-payment", mk: "us", cat: "金融", name: "金融科技與支付", icon: "link",
    desc: "刷卡、手機支付與線上付款背後的系統：卡組織提供清算網路，發卡銀行負責授權，收單與金流業者幫商店收款，每筆交易都會抽一小部分手續費。",
    flow: ["消費者付款", "商店收款", "收單機構", "卡組織網路", "發卡銀行授權"],
    segs: [{ n: "卡組織", c: [["V", "Visa", "全球卡片清算網路"], ["MA", "Mastercard", "全球卡片清算網路"], ["AXP", "American Express", "發卡兼網路"]] },
      { n: "金流與錢包", c: [["PYPL", "PayPal", "線上支付與錢包"], ["XYZ", "Block", "Square 收款與 Cash App"], ["AFRM", "Affirm", "先買後付"]] }],
    fig: { w: 400, h: 280, alt: "刷卡流程：消費者刷卡或用手機錢包，交易經商店刷卡機、收單機構、卡組織網路送到發卡銀行，銀行核准後幾秒內傳回，之後再清算撥款；商店付的手續費大部分是給發卡行的交換費", items: [
      // 消費者
      { t: "icon", x: 12, y: 34, s: 24, k: "person", c: "gray", label: "消費者" },
      { t: "rect", x: 42, y: 36, w: 32, h: 20, c: "blue", fill: 0.3, r: 3 },
      { t: "rect", x: 42, y: 41, w: 32, h: 4, c: "gray", fill: 0.8, stroke: false },
      { t: "rect", x: 46, y: 48, w: 7, h: 5, c: "yellow", fill: 0.8 },
      { t: "icon", x: 48, y: 64, s: 18, k: "phone", c: "green" },
      { t: "badge", x: 76, y: 70, n: 5, c: "green" },
      { t: "arrow", pts: [[76, 48], [98, 48]], c: "blue" },
      // 刷卡機
      { t: "rect", x: 100, y: 30, w: 40, h: 54, c: "purple", fill: 0.12, r: 4 },
      { t: "rect", x: 106, y: 36, w: 28, h: 14, c: "cyan", fill: 0.3 },
      { t: "path", d: "M108 60h4M117 60h4M126 60h4M108 67h4M117 67h4M126 67h4M108 74h4M117 74h4M126 74h4", c: "purple", w: 2.5 },
      { t: "badge", x: 100, y: 28, n: 3, c: "purple" },
      { t: "text", x: 128, y: 18, s: 7.5, label: "商店刷卡機", muted: true },
      // 收單、卡組織、發卡行
      { t: "arrow", pts: [[140, 56], [160, 56]], c: "blue" },
      { t: "box", x: 162, y: 36, w: 64, h: 40, label: "收單機構", sub: "幫商店收款", c: "cyan" },
      { t: "badge", x: 162, y: 36, n: 2, c: "cyan" },
      { t: "arrow", pts: [[226, 56], [248, 56]], c: "blue" },
      { t: "box", x: 250, y: 36, w: 64, h: 40, label: "卡組織", sub: "清算網路", c: "orange" },
      { t: "badge", x: 250, y: 36, n: 1, c: "orange" },
      { t: "arrow", pts: [[314, 56], [334, 56]], c: "blue" },
      { t: "box", x: 336, y: 36, w: 56, h: 40, label: "發卡銀行", sub: "查額度", c: "green" },
      { t: "badge", x: 336, y: 36, n: 4, c: "green" },
      { t: "text", x: 244, y: 22, s: 7.5, label: "授權請求", muted: true },
      // 核准與清算
      { t: "arrow", pts: [[364, 76], [364, 90], [120, 90], [120, 86]], c: "green", dash: true },
      { t: "text", x: 244, y: 102, s: 7.5, label: "核准回傳，只要幾秒", muted: true },
      { t: "arrow", pts: [[380, 76], [380, 128], [108, 128], [108, 87]], c: "green", w: 2.2 },
      { t: "icon", x: 196, y: 132, s: 18, k: "coin", c: "yellow" }, { t: "icon", x: 286, y: 132, s: 18, k: "coin", c: "yellow" },
      { t: "text", x: 244, y: 122, s: 7.5, label: "事後清算撥款給商店", muted: true },
      // 手續費拆分
      { t: "group", x: 8, y: 160, w: 238, h: 100, label: "商店手續費怎麼分", c: "orange" },
      { t: "rect", x: 20, y: 182, w: 130, h: 18, c: "green", fill: 0.5, r: 1 },
      { t: "rect", x: 150, y: 182, w: 30, h: 18, c: "orange", fill: 0.5, r: 1 },
      { t: "rect", x: 180, y: 182, w: 52, h: 18, c: "cyan", fill: 0.5, r: 1 },
      { t: "text", x: 85, y: 214, s: 7.5, label: "交換費" }, { t: "text", x: 85, y: 226, s: 7.5, label: "給發卡行", muted: true },
      { t: "text", x: 165, y: 214, s: 7.5, label: "網路費" }, { t: "text", x: 165, y: 226, s: 7.5, label: "給卡組織", muted: true },
      { t: "text", x: 206, y: 214, s: 7.5, label: "加價" }, { t: "text", x: 210, y: 226, s: 7.5, label: "給收單", muted: true },
      { t: "badge", x: 20, y: 182, n: 4, c: "green" }, { t: "badge", x: 165, y: 176, n: 1, c: "orange" }, { t: "badge", x: 232, y: 182, n: 2, c: "cyan" },
      { t: "text", x: 126, y: 248, s: 8, b: true, label: "商店負擔，消費者看不到" },
      // 新支付方式
      { t: "group", x: 256, y: 160, w: 136, h: 100, label: "新支付方式", c: "pink" },
      { t: "icon", x: 266, y: 180, s: 22, k: "phone", c: "green" },
      { t: "text", x: 277, y: 216, s: 7.5, label: "手機錢包", muted: true },
      { t: "badge", x: 296, y: 180, n: 5, c: "green" },
      { t: "circle", x: 326, y: 192, r: 6, c: "pink", fill: 0.8 }, { t: "circle", x: 342, y: 192, r: 6, c: "pink", fill: 0.55 },
      { t: "circle", x: 358, y: 192, r: 6, c: "pink", fill: 0.35 }, { t: "circle", x: 374, y: 192, r: 6, c: "pink", fill: 0.15 },
      { t: "text", x: 350, y: 216, s: 7.5, label: "先買後付", muted: true },
      { t: "badge", x: 384, y: 176, n: 6, c: "pink" },
      { t: "text", x: 324, y: 244, s: 7.5, label: "錢包多半仍走卡網路", muted: true },
      // 細節：晶片與感應、代碼化、風控、商店入帳、費用去向、分期
      { t: "callout", x: 49, y: 50, tx: 44, ty: 28, label: "晶片加密", c: "yellow", s: 7, a: "start" },
      { t: "path", d: "M87 69a6 6 0 0 1 0 10M91 66a10 10 0 0 1 0 16", c: "green", w: 1 },
      { t: "text", x: 57, y: 94, s: 7, label: "代碼取代卡號", muted: true },
      { t: "dots", x: 142, y: 49, w: 14, h: 4, n: 2, sz: 1.4, c: "blue" }, { t: "dots", x: 229, y: 49, w: 14, h: 4, n: 2, sz: 1.4, c: "blue" }, { t: "dots", x: 316, y: 49, w: 14, h: 4, n: 2, sz: 1.4, c: "blue" },
      { t: "callout", x: 350, y: 40, tx: 330, ty: 26, label: "防盜刷風控", c: "green", s: 7, a: "end" },
      { t: "icon", x: 128, y: 98, s: 16, k: "house", c: "purple" },
      { t: "text", x: 148, y: 112, s: 7, a: "start", label: "商店入帳", muted: true },
      { t: "text", x: 250, y: 145, s: 7, label: "扣掉手續費", muted: true },
      { t: "text", x: 85, y: 194, s: 7, label: "最大一塊" },
      { t: "text", x: 100, y: 178, s: 7, a: "start", label: "多用於卡友回饋", muted: true },
      { t: "text", x: 326, y: 194.5, s: 7, label: "1" }, { t: "text", x: 342, y: 194.5, s: 7, label: "2" }, { t: "text", x: 358, y: 194.5, s: 7, label: "3" }, { t: "text", x: 374, y: 194.5, s: 7, label: "4" },
      { t: "text", x: 324, y: 230, s: 7, label: "即時轉帳・穩定幣", muted: true },
      { t: "legend", x: 14, y: 274, items: [["blue", "授權請求"], ["green", "核准與撥款"], ["orange", "網路費"]] },
    ] },
    how: [
      ["在做什麼", "你刷卡或用手機付款時，錢要從你的銀行帳戶安全地移到商店手上。支付產業提供這條「金流高速公路」，每經過一筆交易就收一點過路費。"],
      ["怎麼運作", "商店的刷卡機或網店把交易送給收單機構，再經 Visa、Mastercard 等卡組織的網路傳到你的發卡銀行，銀行確認額度後核准，幾秒內傳回；之後幾天再完成實際的資金清算，把錢撥給商店。商店付的手續費大部分是給發卡行的交換費，卡組織收網路費，收單機構賺加價。"],
      ["關鍵名詞", "發卡行：發信用卡給你的銀行。收單機構：幫商店收款的業者。交換費：商店手續費中付給發卡行的部分。代碼化（token）：手機錢包用代碼取代真實卡號。先買後付（BNPL）：把一筆消費分期、通常免息。"],
      ["景氣看什麼", "消費支出與通膨、跨境旅遊交易量（手續費較高）、現金轉數位的速度、各國對手續費的監管，以及即時轉帳、穩定幣等新支付方式的競爭。"],
      ["代表公司", "Visa、Mastercard、American Express 是卡組織；Global Payments、PayPal 做收單與線上金流，Block（Square）、Toast 做商家收款系統；摩根大通、Capital One 是大型發卡行；Apple Pay、PayPal、Cash App 是錢包，Affirm、Klarna 做先買後付。"],
    ],
    trends: [
      "手機錢包與代碼化支付普及，實體卡號逐漸被裝置裡的代碼取代",
      "跨境電商與旅遊帶動跨境交易，這類交易手續費較高，是卡組織的成長來源",
      "即時轉帳與穩定幣興起，卡組織與金流業者也開始支援這些新支付通道",
      "收款系統整合點餐、庫存、薪資與貸款，金流業者從收手續費延伸到軟體訂閱",
    ],
    chain: [
      { tier: "上游", title: "支付網路", items: [
        { name: "卡組織清算網路", desc: "連接全球發卡行與收單機構，傳遞授權並清算", c: [["V", "Visa", "全球卡片網路"], ["MA", "Mastercard", "全球卡片網路"], ["AXP", "American Express", "發卡兼網路"]] },
      ] },
      { tier: "中游", title: "收單、商家與發卡", items: [
        { name: "收單與線上金流", desc: "幫實體商店與網店收款，把交易送進卡組織網路", c: [["GPN", "Global Payments", "商家收單"], ["PYPL", "PayPal", "線上金流與 Braintree"]] },
        { name: "商家收款系統", desc: "刷卡機與 POS 系統，整合點餐、庫存與收款", c: [["XYZ", "Block", "Square 收款系統"], ["TOST", "Toast", "餐廳 POS 系統"]] },
        { name: "發卡銀行", desc: "發卡給消費者、核准交易並承擔信用風險", c: [["JPM", "摩根大通", "信用卡發卡行"], ["COF", "Capital One", "信用卡發卡行"], ["AXP", "American Express", "自家發卡"]] },
      ] },
      { tier: "下游", title: "消費者支付工具", items: [
        { name: "數位錢包", desc: "把卡片存進手機或帳戶，一鍵付款與轉帳", c: [["AAPL", "蘋果", "Apple Pay"], ["PYPL", "PayPal", "PayPal 與 Venmo"], ["XYZ", "Block", "Cash App"]] },
        { name: "先買後付（BNPL）", desc: "結帳時把一筆消費拆成幾期付款", c: [["AFRM", "Affirm", "先買後付"], ["KLAR", "Klarna", "先買後付"]] },
      ] },
    ] },
);
